// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: api/packagebridge/v1/package_bridge.proto

package packagebridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelPackageBridge_Invoke_FullMethodName           = "/anixops.packagebridge.v1.KernelPackageBridge/Invoke"
	KernelPackageBridge_OpenWebSocket_FullMethodName    = "/anixops.packagebridge.v1.KernelPackageBridge/OpenWebSocket"
	KernelPackageBridge_GetPackageConfig_FullMethodName = "/anixops.packagebridge.v1.KernelPackageBridge/GetPackageConfig"
	KernelPackageBridge_LeaseStorage_FullMethodName     = "/anixops.packagebridge.v1.KernelPackageBridge/LeaseStorage"
)

// KernelPackageBridgeClient is the client API for KernelPackageBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KernelPackageBridge is a private, per-host channel. It exposes named
// kernel operations only; package hosts never receive kernel database or
// signing credentials.
//
// Invoke and OpenWebSocket require a single-use capability minted for one
// request. Session-scoped RPCs (GetPackageConfig) need no capability: the
// inherited socket is bound to one package id, version and lifecycle
// generation, and the kernel fences every call against the current
// installation.
type KernelPackageBridgeClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	OpenWebSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame], error)
	GetPackageConfig(ctx context.Context, in *GetPackageConfigRequest, opts ...grpc.CallOption) (*GetPackageConfigResponse, error)
	// LeaseStorage issues database credentials for the calling package's own
	// least-privilege storage. Like GetPackageConfig it is authorized by the
	// session identity and fenced against the installation.
	LeaseStorage(ctx context.Context, in *LeaseStorageRequest, opts ...grpc.CallOption) (*LeaseStorageResponse, error)
}

type kernelPackageBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelPackageBridgeClient(cc grpc.ClientConnInterface) KernelPackageBridgeClient {
	return &kernelPackageBridgeClient{cc}
}

func (c *kernelPackageBridgeClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, KernelPackageBridge_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelPackageBridgeClient) OpenWebSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelPackageBridge_ServiceDesc.Streams[0], KernelPackageBridge_OpenWebSocket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WebSocketFrame, WebSocketFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelPackageBridge_OpenWebSocketClient = grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame]

func (c *kernelPackageBridgeClient) GetPackageConfig(ctx context.Context, in *GetPackageConfigRequest, opts ...grpc.CallOption) (*GetPackageConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPackageConfigResponse)
	err := c.cc.Invoke(ctx, KernelPackageBridge_GetPackageConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelPackageBridgeClient) LeaseStorage(ctx context.Context, in *LeaseStorageRequest, opts ...grpc.CallOption) (*LeaseStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseStorageResponse)
	err := c.cc.Invoke(ctx, KernelPackageBridge_LeaseStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelPackageBridgeServer is the server API for KernelPackageBridge service.
// All implementations must embed UnimplementedKernelPackageBridgeServer
// for forward compatibility.
//
// KernelPackageBridge is a private, per-host channel. It exposes named
// kernel operations only; package hosts never receive kernel database or
// signing credentials.
//
// Invoke and OpenWebSocket require a single-use capability minted for one
// request. Session-scoped RPCs (GetPackageConfig) need no capability: the
// inherited socket is bound to one package id, version and lifecycle
// generation, and the kernel fences every call against the current
// installation.
type KernelPackageBridgeServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	OpenWebSocket(grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]) error
	GetPackageConfig(context.Context, *GetPackageConfigRequest) (*GetPackageConfigResponse, error)
	// LeaseStorage issues database credentials for the calling package's own
	// least-privilege storage. Like GetPackageConfig it is authorized by the
	// session identity and fenced against the installation.
	LeaseStorage(context.Context, *LeaseStorageRequest) (*LeaseStorageResponse, error)
	mustEmbedUnimplementedKernelPackageBridgeServer()
}

// UnimplementedKernelPackageBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelPackageBridgeServer struct{}

func (UnimplementedKernelPackageBridgeServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedKernelPackageBridgeServer) OpenWebSocket(grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]) error {
	return status.Error(codes.Unimplemented, "method OpenWebSocket not implemented")
}
func (UnimplementedKernelPackageBridgeServer) GetPackageConfig(context.Context, *GetPackageConfigRequest) (*GetPackageConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageConfig not implemented")
}
func (UnimplementedKernelPackageBridgeServer) LeaseStorage(context.Context, *LeaseStorageRequest) (*LeaseStorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseStorage not implemented")
}
func (UnimplementedKernelPackageBridgeServer) mustEmbedUnimplementedKernelPackageBridgeServer() {}
func (UnimplementedKernelPackageBridgeServer) testEmbeddedByValue()                             {}

// UnsafeKernelPackageBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelPackageBridgeServer will
// result in compilation errors.
type UnsafeKernelPackageBridgeServer interface {
	mustEmbedUnimplementedKernelPackageBridgeServer()
}

func RegisterKernelPackageBridgeServer(s grpc.ServiceRegistrar, srv KernelPackageBridgeServer) {
	// If the following call panics, it indicates UnimplementedKernelPackageBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelPackageBridge_ServiceDesc, srv)
}

func _KernelPackageBridge_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelPackageBridgeServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelPackageBridge_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelPackageBridgeServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelPackageBridge_OpenWebSocket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KernelPackageBridgeServer).OpenWebSocket(&grpc.GenericServerStream[WebSocketFrame, WebSocketFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelPackageBridge_OpenWebSocketServer = grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]

func _KernelPackageBridge_GetPackageConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelPackageBridgeServer).GetPackageConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelPackageBridge_GetPackageConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelPackageBridgeServer).GetPackageConfig(ctx, req.(*GetPackageConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelPackageBridge_LeaseStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelPackageBridgeServer).LeaseStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelPackageBridge_LeaseStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelPackageBridgeServer).LeaseStorage(ctx, req.(*LeaseStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KernelPackageBridge_ServiceDesc is the grpc.ServiceDesc for KernelPackageBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelPackageBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anixops.packagebridge.v1.KernelPackageBridge",
	HandlerType: (*KernelPackageBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _KernelPackageBridge_Invoke_Handler,
		},
		{
			MethodName: "GetPackageConfig",
			Handler:    _KernelPackageBridge_GetPackageConfig_Handler,
		},
		{
			MethodName: "LeaseStorage",
			Handler:    _KernelPackageBridge_LeaseStorage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenWebSocket",
			Handler:       _KernelPackageBridge_OpenWebSocket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/packagebridge/v1/package_bridge.proto",
}
