// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: api/modulepki/v1/module_pki.proto

package modulepkiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModulePKI_Enroll_FullMethodName         = "/anixops.modulepki.v1.ModulePKI/Enroll"
	ModulePKI_Renew_FullMethodName          = "/anixops.modulepki.v1.ModulePKI/Renew"
	ModulePKI_GetTrustBundle_FullMethodName = "/anixops.modulepki.v1.ModulePKI/GetTrustBundle"
)

// ModulePKIClient is the client API for ModulePKI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModulePKI issues the mTLS certificates of remote modules. It is served on
// the kernel's module listener. Enroll is the only RPC accepted without a
// client certificate; Renew and GetTrustBundle require the module's current
// certificate.
//
// Certificates carry one URI SAN: spiffe://anixops/<cluster>/module/<package>
// for modules and spiffe://anixops/<cluster>/kernel for the kernel.
type ModulePKIClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error)
	GetTrustBundle(ctx context.Context, in *GetTrustBundleRequest, opts ...grpc.CallOption) (*GetTrustBundleResponse, error)
}

type modulePKIClient struct {
	cc grpc.ClientConnInterface
}

func NewModulePKIClient(cc grpc.ClientConnInterface) ModulePKIClient {
	return &modulePKIClient{cc}
}

func (c *modulePKIClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, ModulePKI_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modulePKIClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewResponse)
	err := c.cc.Invoke(ctx, ModulePKI_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modulePKIClient) GetTrustBundle(ctx context.Context, in *GetTrustBundleRequest, opts ...grpc.CallOption) (*GetTrustBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrustBundleResponse)
	err := c.cc.Invoke(ctx, ModulePKI_GetTrustBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModulePKIServer is the server API for ModulePKI service.
// All implementations must embed UnimplementedModulePKIServer
// for forward compatibility.
//
// ModulePKI issues the mTLS certificates of remote modules. It is served on
// the kernel's module listener. Enroll is the only RPC accepted without a
// client certificate; Renew and GetTrustBundle require the module's current
// certificate.
//
// Certificates carry one URI SAN: spiffe://anixops/<cluster>/module/<package>
// for modules and spiffe://anixops/<cluster>/kernel for the kernel.
type ModulePKIServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	Renew(context.Context, *RenewRequest) (*RenewResponse, error)
	GetTrustBundle(context.Context, *GetTrustBundleRequest) (*GetTrustBundleResponse, error)
	mustEmbedUnimplementedModulePKIServer()
}

// UnimplementedModulePKIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModulePKIServer struct{}

func (UnimplementedModulePKIServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedModulePKIServer) Renew(context.Context, *RenewRequest) (*RenewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedModulePKIServer) GetTrustBundle(context.Context, *GetTrustBundleRequest) (*GetTrustBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrustBundle not implemented")
}
func (UnimplementedModulePKIServer) mustEmbedUnimplementedModulePKIServer() {}
func (UnimplementedModulePKIServer) testEmbeddedByValue()                   {}

// UnsafeModulePKIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModulePKIServer will
// result in compilation errors.
type UnsafeModulePKIServer interface {
	mustEmbedUnimplementedModulePKIServer()
}

func RegisterModulePKIServer(s grpc.ServiceRegistrar, srv ModulePKIServer) {
	// If the following call panics, it indicates UnimplementedModulePKIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModulePKI_ServiceDesc, srv)
}

func _ModulePKI_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModulePKIServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModulePKI_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModulePKIServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModulePKI_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModulePKIServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModulePKI_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModulePKIServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModulePKI_GetTrustBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrustBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModulePKIServer).GetTrustBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModulePKI_GetTrustBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModulePKIServer).GetTrustBundle(ctx, req.(*GetTrustBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModulePKI_ServiceDesc is the grpc.ServiceDesc for ModulePKI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModulePKI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anixops.modulepki.v1.ModulePKI",
	HandlerType: (*ModulePKIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _ModulePKI_Enroll_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _ModulePKI_Renew_Handler,
		},
		{
			MethodName: "GetTrustBundle",
			Handler:    _ModulePKI_GetTrustBundle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/modulepki/v1/module_pki.proto",
}
