// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: api/grpc/v2board.proto

package v2boardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserChangeNotification_ChangeType int32

const (
	UserChangeNotification_UNKNOWN       UserChangeNotification_ChangeType = 0
	UserChangeNotification_CREATED       UserChangeNotification_ChangeType = 1
	UserChangeNotification_UPDATED       UserChangeNotification_ChangeType = 2
	UserChangeNotification_DELETED       UserChangeNotification_ChangeType = 3
	UserChangeNotification_TRAFFIC_RESET UserChangeNotification_ChangeType = 4
	UserChangeNotification_BANNED        UserChangeNotification_ChangeType = 5
	UserChangeNotification_UNBANNED      UserChangeNotification_ChangeType = 6
)

// Enum value maps for UserChangeNotification_ChangeType.
var (
	UserChangeNotification_ChangeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATED",
		2: "UPDATED",
		3: "DELETED",
		4: "TRAFFIC_RESET",
		5: "BANNED",
		6: "UNBANNED",
	}
	UserChangeNotification_ChangeType_value = map[string]int32{
		"UNKNOWN":       0,
		"CREATED":       1,
		"UPDATED":       2,
		"DELETED":       3,
		"TRAFFIC_RESET": 4,
		"BANNED":        5,
		"UNBANNED":      6,
	}
)

func (x UserChangeNotification_ChangeType) Enum() *UserChangeNotification_ChangeType {
	p := new(UserChangeNotification_ChangeType)
	*p = x
	return p
}

func (x UserChangeNotification_ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserChangeNotification_ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v2board_proto_enumTypes[0].Descriptor()
}

func (UserChangeNotification_ChangeType) Type() protoreflect.EnumType {
	return &file_api_grpc_v2board_proto_enumTypes[0]
}

func (x UserChangeNotification_ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserChangeNotification_ChangeType.Descriptor instead.
func (UserChangeNotification_ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{12, 0}
}

type ConfigChangeNotification_ChangeType int32

const (
	ConfigChangeNotification_UNKNOWN         ConfigChangeNotification_ChangeType = 0
	ConfigChangeNotification_NODE_CONFIG     ConfigChangeNotification_ChangeType = 1 // 节点配置变更
	ConfigChangeNotification_USER_LIST       ConfigChangeNotification_ChangeType = 2 // 用户列表变更
	ConfigChangeNotification_PROTOCOL_CONFIG ConfigChangeNotification_ChangeType = 3 // 协议配置变更
)

// Enum value maps for ConfigChangeNotification_ChangeType.
var (
	ConfigChangeNotification_ChangeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NODE_CONFIG",
		2: "USER_LIST",
		3: "PROTOCOL_CONFIG",
	}
	ConfigChangeNotification_ChangeType_value = map[string]int32{
		"UNKNOWN":         0,
		"NODE_CONFIG":     1,
		"USER_LIST":       2,
		"PROTOCOL_CONFIG": 3,
	}
)

func (x ConfigChangeNotification_ChangeType) Enum() *ConfigChangeNotification_ChangeType {
	p := new(ConfigChangeNotification_ChangeType)
	*p = x
	return p
}

func (x ConfigChangeNotification_ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigChangeNotification_ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v2board_proto_enumTypes[1].Descriptor()
}

func (ConfigChangeNotification_ChangeType) Type() protoreflect.EnumType {
	return &file_api_grpc_v2board_proto_enumTypes[1]
}

func (x ConfigChangeNotification_ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigChangeNotification_ChangeType.Descriptor instead.
func (ConfigChangeNotification_ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{20, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v2board_proto_enumTypes[2].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_api_grpc_v2board_proto_enumTypes[2]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{22, 0}
}

// 空响应
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_grpc_v2board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{0}
}

// 状态响应
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_grpc_v2board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 节点注册请求
type NodeRegisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AuthKey            string                 `protobuf:"bytes,1,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`                                  // 授权密钥
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                       // 节点名称
	Host               string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`                                                       // 节点地址
	Port               int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                                      // API端口
	ServerVersion      string                 `protobuf:"bytes,5,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`                // 节点版本
	ServerOs           string                 `protobuf:"bytes,6,opt,name=server_os,json=serverOs,proto3" json:"server_os,omitempty"`                               // 操作系统
	SupportedProtocols []string               `protobuf:"bytes,7,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"` // 支持的协议列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeRegisterRequest) Reset() {
	*x = NodeRegisterRequest{}
	mi := &file_api_grpc_v2board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterRequest) ProtoMessage() {}

func (x *NodeRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterRequest.ProtoReflect.Descriptor instead.
func (*NodeRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{2}
}

func (x *NodeRegisterRequest) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *NodeRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeRegisterRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeRegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeRegisterRequest) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *NodeRegisterRequest) GetServerOs() string {
	if x != nil {
		return x.ServerOs
	}
	return ""
}

func (x *NodeRegisterRequest) GetSupportedProtocols() []string {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

// 节点注册响应
type NodeRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 节点ID
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`  // API密钥
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`                // 共享密钥
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegisterResponse) Reset() {
	*x = NodeRegisterResponse{}
	mi := &file_api_grpc_v2board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterResponse) ProtoMessage() {}

func (x *NodeRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterResponse.ProtoReflect.Descriptor instead.
func (*NodeRegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{3}
}

func (x *NodeRegisterResponse) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeRegisterResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *NodeRegisterResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *NodeRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 节点配置请求
type NodeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfigRequest) Reset() {
	*x = NodeConfigRequest{}
	mi := &file_api_grpc_v2board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfigRequest) ProtoMessage() {}

func (x *NodeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfigRequest.ProtoReflect.Descriptor instead.
func (*NodeConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{4}
}

func (x *NodeConfigRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// 节点配置响应
type NodeConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeType        string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // 与 node_type 一致
	Host            string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	ServerPort      int32                  `protobuf:"varint,4,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	ServerName      string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Tls             int32                  `protobuf:"varint,6,opt,name=tls,proto3" json:"tls,omitempty"` // 0=无, 1=TLS, 2=Reality
	TlsSettings     map[string]string      `protobuf:"bytes,7,rep,name=tls_settings,json=tlsSettings,proto3" json:"tls_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Network         string                 `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"` // tcp, ws, grpc, etc.
	NetworkSettings map[string]string      `protobuf:"bytes,9,rep,name=network_settings,json=networkSettings,proto3" json:"network_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cipher          string                 `protobuf:"bytes,10,opt,name=cipher,proto3" json:"cipher,omitempty"`                        // SS加密方式
	Flow            string                 `protobuf:"bytes,11,opt,name=flow,proto3" json:"flow,omitempty"`                            // VLESS flow
	ServerKey       string                 `protobuf:"bytes,12,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"` // SS2022服务器密钥
	BaseConfig      *BaseConfig            `protobuf:"bytes,13,opt,name=base_config,json=baseConfig,proto3" json:"base_config,omitempty"`
	Routes          []*Route               `protobuf:"bytes,14,rep,name=routes,proto3" json:"routes,omitempty"`
	SendThrough     string                 `protobuf:"bytes,15,opt,name=send_through,json=sendThrough,proto3" json:"send_through,omitempty"`
	Extra           map[string]string      `protobuf:"bytes,16,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展配置
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeConfigResponse) Reset() {
	*x = NodeConfigResponse{}
	mi := &file_api_grpc_v2board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfigResponse) ProtoMessage() {}

func (x *NodeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfigResponse.ProtoReflect.Descriptor instead.
func (*NodeConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{5}
}

func (x *NodeConfigResponse) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeConfigResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeConfigResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeConfigResponse) GetServerPort() int32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *NodeConfigResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *NodeConfigResponse) GetTls() int32 {
	if x != nil {
		return x.Tls
	}
	return 0
}

func (x *NodeConfigResponse) GetTlsSettings() map[string]string {
	if x != nil {
		return x.TlsSettings
	}
	return nil
}

func (x *NodeConfigResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NodeConfigResponse) GetNetworkSettings() map[string]string {
	if x != nil {
		return x.NetworkSettings
	}
	return nil
}

func (x *NodeConfigResponse) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *NodeConfigResponse) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *NodeConfigResponse) GetServerKey() string {
	if x != nil {
		return x.ServerKey
	}
	return ""
}

func (x *NodeConfigResponse) GetBaseConfig() *BaseConfig {
	if x != nil {
		return x.BaseConfig
	}
	return nil
}

func (x *NodeConfigResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NodeConfigResponse) GetSendThrough() string {
	if x != nil {
		return x.SendThrough
	}
	return ""
}

func (x *NodeConfigResponse) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 基础配置
type BaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushInterval  int32                  `protobuf:"varint,1,opt,name=push_interval,json=pushInterval,proto3" json:"push_interval,omitempty"` // 流量上报间隔(秒)
	PullInterval  int32                  `protobuf:"varint,2,opt,name=pull_interval,json=pullInterval,proto3" json:"pull_interval,omitempty"` // 配置拉取间隔(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseConfig) Reset() {
	*x = BaseConfig{}
	mi := &file_api_grpc_v2board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseConfig) ProtoMessage() {}

func (x *BaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseConfig.ProtoReflect.Descriptor instead.
func (*BaseConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{6}
}

func (x *BaseConfig) GetPushInterval() int32 {
	if x != nil {
		return x.PushInterval
	}
	return 0
}

func (x *BaseConfig) GetPullInterval() int32 {
	if x != nil {
		return x.PullInterval
	}
	return 0
}

// 路由配置
type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         string                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_grpc_v2board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{7}
}

func (x *Route) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *Route) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// 节点状态上报请求
type NodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage     float64                `protobuf:"fixed64,4,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Uptime        int64                  `protobuf:"varint,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	OnlineUsers   int32                  `protobuf:"varint,6,opt,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty"`
	Upload        int64                  `protobuf:"varint,7,opt,name=upload,proto3" json:"upload,omitempty"`     // 本次上报的上传流量增量
	Download      int64                  `protobuf:"varint,8,opt,name=download,proto3" json:"download,omitempty"` // 本次上报的下载流量增量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_api_grpc_v2board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{8}
}

func (x *NodeStatusRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeStatusRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeStatusRequest) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *NodeStatusRequest) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *NodeStatusRequest) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *NodeStatusRequest) GetOnlineUsers() int32 {
	if x != nil {
		return x.OnlineUsers
	}
	return 0
}

func (x *NodeStatusRequest) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *NodeStatusRequest) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

// 用户列表请求
type UserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_api_grpc_v2board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{9}
}

func (x *UserListRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UserListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 用户信息
type UserInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid           string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SpeedLimit     int64                  `protobuf:"varint,3,opt,name=speed_limit,json=speedLimit,proto3" json:"speed_limit,omitempty"`                                              // 速度限制 (bytes/s)
	DeviceLimit    int32                  `protobuf:"varint,4,opt,name=device_limit,json=deviceLimit,proto3" json:"device_limit,omitempty"`                                           // 设备限制
	ExpiredAt      int64                  `protobuf:"varint,5,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`                                                 // 过期时间
	TransferEnable int64                  `protobuf:"varint,6,opt,name=transfer_enable,json=transferEnable,proto3" json:"transfer_enable,omitempty"`                                  // 总流量
	UsedUpload     int64                  `protobuf:"varint,7,opt,name=used_upload,json=usedUpload,proto3" json:"used_upload,omitempty"`                                              // 已用上传
	UsedDownload   int64                  `protobuf:"varint,8,opt,name=used_download,json=usedDownload,proto3" json:"used_download,omitempty"`                                        // 已用下载
	Extra          map[string]string      `protobuf:"bytes,9,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_grpc_v2board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{10}
}

func (x *UserInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserInfo) GetSpeedLimit() int64 {
	if x != nil {
		return x.SpeedLimit
	}
	return 0
}

func (x *UserInfo) GetDeviceLimit() int32 {
	if x != nil {
		return x.DeviceLimit
	}
	return 0
}

func (x *UserInfo) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *UserInfo) GetTransferEnable() int64 {
	if x != nil {
		return x.TransferEnable
	}
	return 0
}

func (x *UserInfo) GetUsedUpload() int64 {
	if x != nil {
		return x.UsedUpload
	}
	return 0
}

func (x *UserInfo) GetUsedDownload() int64 {
	if x != nil {
		return x.UsedDownload
	}
	return 0
}

func (x *UserInfo) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 用户列表响应
type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 数据更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_api_grpc_v2board_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{11}
}

func (x *UserListResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserListResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 用户变更通知
type UserChangeNotification struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Type          UserChangeNotification_ChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=v2board.UserChangeNotification_ChangeType" json:"type,omitempty"`
	User          *UserInfo                         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp     int64                             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserChangeNotification) Reset() {
	*x = UserChangeNotification{}
	mi := &file_api_grpc_v2board_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChangeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChangeNotification) ProtoMessage() {}

func (x *UserChangeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChangeNotification.ProtoReflect.Descriptor instead.
func (*UserChangeNotification) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{12}
}

func (x *UserChangeNotification) GetType() UserChangeNotification_ChangeType {
	if x != nil {
		return x.Type
	}
	return UserChangeNotification_UNKNOWN
}

func (x *UserChangeNotification) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserChangeNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 流量上报请求
type TrafficReportRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	NodeId        uint32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Traffics      map[uint32]*TrafficData `protobuf:"bytes,2,rep,name=traffics,proto3" json:"traffics,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 用户ID -> 流量数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReportRequest) Reset() {
	*x = TrafficReportRequest{}
	mi := &file_api_grpc_v2board_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReportRequest) ProtoMessage() {}

func (x *TrafficReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReportRequest.ProtoReflect.Descriptor instead.
func (*TrafficReportRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{13}
}

func (x *TrafficReportRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *TrafficReportRequest) GetTraffics() map[uint32]*TrafficData {
	if x != nil {
		return x.Traffics
	}
	return nil
}

// 流量数据
type TrafficData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upload        int64                  `protobuf:"varint,1,opt,name=upload,proto3" json:"upload,omitempty"`     // 上传流量 (bytes)
	Download      int64                  `protobuf:"varint,2,opt,name=download,proto3" json:"download,omitempty"` // 下载流量 (bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficData) Reset() {
	*x = TrafficData{}
	mi := &file_api_grpc_v2board_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficData) ProtoMessage() {}

func (x *TrafficData) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficData.ProtoReflect.Descriptor instead.
func (*TrafficData) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{14}
}

func (x *TrafficData) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *TrafficData) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

// 流量上报响应
type TrafficReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Balances      map[uint32]int64       `protobuf:"bytes,3,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 用户ID -> 更新后的余额(可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReportResponse) Reset() {
	*x = TrafficReportResponse{}
	mi := &file_api_grpc_v2board_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReportResponse) ProtoMessage() {}

func (x *TrafficReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReportResponse.ProtoReflect.Descriptor instead.
func (*TrafficReportResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{15}
}

func (x *TrafficReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrafficReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TrafficReportResponse) GetBalances() map[uint32]int64 {
	if x != nil {
		return x.Balances
	}
	return nil
}

// 在线状态上报请求
type OnlineReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Online        map[uint32]*OnlineData `protobuf:"bytes,2,rep,name=online,proto3" json:"online,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 用户ID -> 在线数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineReportRequest) Reset() {
	*x = OnlineReportRequest{}
	mi := &file_api_grpc_v2board_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReportRequest) ProtoMessage() {}

func (x *OnlineReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReportRequest.ProtoReflect.Descriptor instead.
func (*OnlineReportRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{16}
}

func (x *OnlineReportRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *OnlineReportRequest) GetOnline() map[uint32]*OnlineData {
	if x != nil {
		return x.Online
	}
	return nil
}

// 在线数据
type OnlineData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`              // 在线IP列表
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineData) Reset() {
	*x = OnlineData{}
	mi := &file_api_grpc_v2board_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineData) ProtoMessage() {}

func (x *OnlineData) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineData.ProtoReflect.Descriptor instead.
func (*OnlineData) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{17}
}

func (x *OnlineData) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *OnlineData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 配置同步请求
type ConfigSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LastSyncTime  int64                  `protobuf:"varint,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"` // 上次同步时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSyncRequest) Reset() {
	*x = ConfigSyncRequest{}
	mi := &file_api_grpc_v2board_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSyncRequest) ProtoMessage() {}

func (x *ConfigSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSyncRequest.ProtoReflect.Descriptor instead.
func (*ConfigSyncRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigSyncRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ConfigSyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

// 配置同步响应
type ConfigSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasChanges    bool                   `protobuf:"varint,1,opt,name=has_changes,json=hasChanges,proto3" json:"has_changes,omitempty"`
	Config        *NodeConfigResponse    `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`                      // 如果有变更
	Users         []*UserInfo            `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`                        // 用户列表(全量或增量)
	SyncTime      int64                  `protobuf:"varint,4,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"` // 当前同步时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSyncResponse) Reset() {
	*x = ConfigSyncResponse{}
	mi := &file_api_grpc_v2board_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSyncResponse) ProtoMessage() {}

func (x *ConfigSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSyncResponse.ProtoReflect.Descriptor instead.
func (*ConfigSyncResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigSyncResponse) GetHasChanges() bool {
	if x != nil {
		return x.HasChanges
	}
	return false
}

func (x *ConfigSyncResponse) GetConfig() *NodeConfigResponse {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigSyncResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ConfigSyncResponse) GetSyncTime() int64 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

// 配置变更通知
type ConfigChangeNotification struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Type          ConfigChangeNotification_ChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=v2board.ConfigChangeNotification_ChangeType" json:"type,omitempty"`
	NodeId        uint32                              `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                               `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                              `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // 变更内容(JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeNotification) Reset() {
	*x = ConfigChangeNotification{}
	mi := &file_api_grpc_v2board_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeNotification) ProtoMessage() {}

func (x *ConfigChangeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeNotification.ProtoReflect.Descriptor instead.
func (*ConfigChangeNotification) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigChangeNotification) GetType() ConfigChangeNotification_ChangeType {
	if x != nil {
		return x.Type
	}
	return ConfigChangeNotification_UNKNOWN
}

func (x *ConfigChangeNotification) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ConfigChangeNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConfigChangeNotification) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_grpc_v2board_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HealthCheckRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=v2board.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	ServerVersion string                            `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Timestamp     int64                             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_grpc_v2board_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v2board_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v2board_proto_rawDescGZIP(), []int{22}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_grpc_v2board_proto protoreflect.FileDescriptor

const file_api_grpc_v2board_proto_rawDesc = "" +
	"\n" +
	"\x16api/grpc/v2board.proto\x12\av2board\"\a\n" +
	"\x05Empty\"X\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"\xe1\x01\n" +
	"\x13NodeRegisterRequest\x12\x19\n" +
	"\bauth_key\x18\x01 \x01(\tR\aauthKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12%\n" +
	"\x0eserver_version\x18\x05 \x01(\tR\rserverVersion\x12\x1b\n" +
	"\tserver_os\x18\x06 \x01(\tR\bserverOs\x12/\n" +
	"\x13supported_protocols\x18\a \x03(\tR\x12supportedProtocols\"z\n" +
	"\x14NodeRegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\",\n" +
	"\x11NodeConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\"\xbd\x06\n" +
	"\x12NodeConfigResponse\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1f\n" +
	"\vserver_port\x18\x04 \x01(\x05R\n" +
	"serverPort\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x12\x10\n" +
	"\x03tls\x18\x06 \x01(\x05R\x03tls\x12O\n" +
	"\ftls_settings\x18\a \x03(\v2,.v2board.NodeConfigResponse.TlsSettingsEntryR\vtlsSettings\x12\x18\n" +
	"\anetwork\x18\b \x01(\tR\anetwork\x12[\n" +
	"\x10network_settings\x18\t \x03(\v20.v2board.NodeConfigResponse.NetworkSettingsEntryR\x0fnetworkSettings\x12\x16\n" +
	"\x06cipher\x18\n" +
	" \x01(\tR\x06cipher\x12\x12\n" +
	"\x04flow\x18\v \x01(\tR\x04flow\x12\x1d\n" +
	"\n" +
	"server_key\x18\f \x01(\tR\tserverKey\x124\n" +
	"\vbase_config\x18\r \x01(\v2\x13.v2board.BaseConfigR\n" +
	"baseConfig\x12&\n" +
	"\x06routes\x18\x0e \x03(\v2\x0e.v2board.RouteR\x06routes\x12!\n" +
	"\fsend_through\x18\x0f \x01(\tR\vsendThrough\x12<\n" +
	"\x05extra\x18\x10 \x03(\v2&.v2board.NodeConfigResponse.ExtraEntryR\x05extra\x1a>\n" +
	"\x10TlsSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14NetworkSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\n" +
	"BaseConfig\x12#\n" +
	"\rpush_interval\x18\x01 \x01(\x05R\fpushInterval\x12#\n" +
	"\rpull_interval\x18\x02 \x01(\x05R\fpullInterval\"5\n" +
	"\x05Route\x12\x14\n" +
	"\x05match\x18\x01 \x01(\tR\x05match\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xfa\x01\n" +
	"\x11NodeStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x04 \x01(\x01R\tdiskUsage\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\x03R\x06uptime\x12!\n" +
	"\fonline_users\x18\x06 \x01(\x05R\vonlineUsers\x12\x16\n" +
	"\x06upload\x18\a \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\b \x01(\x03R\bdownload\"[\n" +
	"\x0fUserListRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xee\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vspeed_limit\x18\x03 \x01(\x03R\n" +
	"speedLimit\x12!\n" +
	"\fdevice_limit\x18\x04 \x01(\x05R\vdeviceLimit\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\x03R\texpiredAt\x12'\n" +
	"\x0ftransfer_enable\x18\x06 \x01(\x03R\x0etransferEnable\x12\x1f\n" +
	"\vused_upload\x18\a \x01(\x03R\n" +
	"usedUpload\x12#\n" +
	"\rused_download\x18\b \x01(\x03R\fusedDownload\x122\n" +
	"\x05extra\x18\t \x03(\v2\x1c.v2board.UserInfo.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x10UserListResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.v2board.UserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"\x8c\x02\n" +
	"\x16UserChangeNotification\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.v2board.UserChangeNotification.ChangeTypeR\x04type\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.v2board.UserInfoR\x04user\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"m\n" +
	"\n" +
	"ChangeType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\v\n" +
	"\aUPDATED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\x12\x11\n" +
	"\rTRAFFIC_RESET\x10\x04\x12\n" +
	"\n" +
	"\x06BANNED\x10\x05\x12\f\n" +
	"\bUNBANNED\x10\x06\"\xcb\x01\n" +
	"\x14TrafficReportRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12G\n" +
	"\btraffics\x18\x02 \x03(\v2+.v2board.TrafficReportRequest.TrafficsEntryR\btraffics\x1aQ\n" +
	"\rTrafficsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.v2board.TrafficDataR\x05value:\x028\x01\"A\n" +
	"\vTrafficData\x12\x16\n" +
	"\x06upload\x18\x01 \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\x02 \x01(\x03R\bdownload\"\xd2\x01\n" +
	"\x15TrafficReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\bbalances\x18\x03 \x03(\v2,.v2board.TrafficReportResponse.BalancesEntryR\bbalances\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xc0\x01\n" +
	"\x13OnlineReportRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12@\n" +
	"\x06online\x18\x02 \x03(\v2(.v2board.OnlineReportRequest.OnlineEntryR\x06online\x1aN\n" +
	"\vOnlineEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.v2board.OnlineDataR\x05value:\x028\x01\"<\n" +
	"\n" +
	"OnlineData\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"R\n" +
	"\x11ConfigSyncRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12$\n" +
	"\x0elast_sync_time\x18\x02 \x01(\x03R\flastSyncTime\"\xb0\x01\n" +
	"\x12ConfigSyncResponse\x12\x1f\n" +
	"\vhas_changes\x18\x01 \x01(\bR\n" +
	"hasChanges\x123\n" +
	"\x06config\x18\x02 \x01(\v2\x1b.v2board.NodeConfigResponseR\x06config\x12'\n" +
	"\x05users\x18\x03 \x03(\v2\x11.v2board.UserInfoR\x05users\x12\x1b\n" +
	"\tsync_time\x18\x04 \x01(\x03R\bsyncTime\"\xfd\x01\n" +
	"\x18ConfigChangeNotification\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.v2board.ConfigChangeNotification.ChangeTypeR\x04type\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"N\n" +
	"\n" +
	"ChangeType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vNODE_CONFIG\x10\x01\x12\r\n" +
	"\tUSER_LIST\x10\x02\x12\x13\n" +
	"\x0fPROTOCOL_CONFIG\x10\x03\"G\n" +
	"\x12HealthCheckRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xda\x01\n" +
	"\x13HealthCheckResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.v2board.HealthCheckResponse.ServingStatusR\x06status\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xae\x02\n" +
	"\vNodeService\x12G\n" +
	"\bRegister\x12\x1c.v2board.NodeRegisterRequest\x1a\x1d.v2board.NodeRegisterResponse\x12D\n" +
	"\tGetConfig\x12\x1a.v2board.NodeConfigRequest\x1a\x1b.v2board.NodeConfigResponse\x12C\n" +
	"\fReportStatus\x12\x1a.v2board.NodeStatusRequest\x1a\x17.v2board.StatusResponse\x12K\n" +
	"\fStatusStream\x12\x1a.v2board.NodeStatusRequest\x1a\x1b.v2board.NodeConfigResponse(\x010\x012\x9b\x01\n" +
	"\vUserService\x12?\n" +
	"\bGetUsers\x12\x18.v2board.UserListRequest\x1a\x19.v2board.UserListResponse\x12K\n" +
	"\vUserChanges\x12\x1f.v2board.UserChangeNotification\x1a\x17.v2board.StatusResponse(\x010\x012\xc6\x02\n" +
	"\x0eTrafficService\x12N\n" +
	"\rReportTraffic\x12\x1d.v2board.TrafficReportRequest\x1a\x1e.v2board.TrafficReportResponse\x12E\n" +
	"\fReportOnline\x12\x1c.v2board.OnlineReportRequest\x1a\x17.v2board.StatusResponse\x12R\n" +
	"\rTrafficStream\x12\x1d.v2board.TrafficReportRequest\x1a\x1e.v2board.TrafficReportResponse(\x010\x01\x12I\n" +
	"\fOnlineStream\x12\x1c.v2board.OnlineReportRequest\x1a\x17.v2board.StatusResponse(\x010\x012\xf0\x01\n" +
	"\x11ConfigSyncService\x12E\n" +
	"\n" +
	"SyncConfig\x12\x1a.v2board.ConfigSyncRequest\x1a\x1b.v2board.ConfigSyncResponse\x12O\n" +
	"\rConfigChanges\x12!.v2board.ConfigChangeNotification\x1a\x17.v2board.StatusResponse(\x010\x01\x12C\n" +
	"\bFullSync\x12\x1a.v2board.ConfigSyncRequest\x1a\x1b.v2board.ConfigSyncResponse2\x9b\x01\n" +
	"\rHealthService\x12B\n" +
	"\x05Check\x12\x1b.v2board.HealthCheckRequest\x1a\x1c.v2board.HealthCheckResponse\x12F\n" +
	"\x05Watch\x12\x1b.v2board.HealthCheckRequest\x1a\x1c.v2board.HealthCheckResponse(\x010\x01B/Z-github.com/anixops/v2board/api/grpc/v2boardpbb\x06proto3"

var (
	file_api_grpc_v2board_proto_rawDescOnce sync.Once
	file_api_grpc_v2board_proto_rawDescData []byte
)

func file_api_grpc_v2board_proto_rawDescGZIP() []byte {
	file_api_grpc_v2board_proto_rawDescOnce.Do(func() {
		file_api_grpc_v2board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v2board_proto_rawDesc), len(file_api_grpc_v2board_proto_rawDesc)))
	})
	return file_api_grpc_v2board_proto_rawDescData
}

var file_api_grpc_v2board_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_grpc_v2board_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_grpc_v2board_proto_goTypes = []any{
	(UserChangeNotification_ChangeType)(0),   // 0: v2board.UserChangeNotification.ChangeType
	(ConfigChangeNotification_ChangeType)(0), // 1: v2board.ConfigChangeNotification.ChangeType
	(HealthCheckResponse_ServingStatus)(0),   // 2: v2board.HealthCheckResponse.ServingStatus
	(*Empty)(nil),                            // 3: v2board.Empty
	(*StatusResponse)(nil),                   // 4: v2board.StatusResponse
	(*NodeRegisterRequest)(nil),              // 5: v2board.NodeRegisterRequest
	(*NodeRegisterResponse)(nil),             // 6: v2board.NodeRegisterResponse
	(*NodeConfigRequest)(nil),                // 7: v2board.NodeConfigRequest
	(*NodeConfigResponse)(nil),               // 8: v2board.NodeConfigResponse
	(*BaseConfig)(nil),                       // 9: v2board.BaseConfig
	(*Route)(nil),                            // 10: v2board.Route
	(*NodeStatusRequest)(nil),                // 11: v2board.NodeStatusRequest
	(*UserListRequest)(nil),                  // 12: v2board.UserListRequest
	(*UserInfo)(nil),                         // 13: v2board.UserInfo
	(*UserListResponse)(nil),                 // 14: v2board.UserListResponse
	(*UserChangeNotification)(nil),           // 15: v2board.UserChangeNotification
	(*TrafficReportRequest)(nil),             // 16: v2board.TrafficReportRequest
	(*TrafficData)(nil),                      // 17: v2board.TrafficData
	(*TrafficReportResponse)(nil),            // 18: v2board.TrafficReportResponse
	(*OnlineReportRequest)(nil),              // 19: v2board.OnlineReportRequest
	(*OnlineData)(nil),                       // 20: v2board.OnlineData
	(*ConfigSyncRequest)(nil),                // 21: v2board.ConfigSyncRequest
	(*ConfigSyncResponse)(nil),               // 22: v2board.ConfigSyncResponse
	(*ConfigChangeNotification)(nil),         // 23: v2board.ConfigChangeNotification
	(*HealthCheckRequest)(nil),               // 24: v2board.HealthCheckRequest
	(*HealthCheckResponse)(nil),              // 25: v2board.HealthCheckResponse
	nil,                                      // 26: v2board.NodeConfigResponse.TlsSettingsEntry
	nil,                                      // 27: v2board.NodeConfigResponse.NetworkSettingsEntry
	nil,                                      // 28: v2board.NodeConfigResponse.ExtraEntry
	nil,                                      // 29: v2board.UserInfo.ExtraEntry
	nil,                                      // 30: v2board.TrafficReportRequest.TrafficsEntry
	nil,                                      // 31: v2board.TrafficReportResponse.BalancesEntry
	nil,                                      // 32: v2board.OnlineReportRequest.OnlineEntry
}
var file_api_grpc_v2board_proto_depIdxs = []int32{
	26, // 0: v2board.NodeConfigResponse.tls_settings:type_name -> v2board.NodeConfigResponse.TlsSettingsEntry
	27, // 1: v2board.NodeConfigResponse.network_settings:type_name -> v2board.NodeConfigResponse.NetworkSettingsEntry
	9,  // 2: v2board.NodeConfigResponse.base_config:type_name -> v2board.BaseConfig
	10, // 3: v2board.NodeConfigResponse.routes:type_name -> v2board.Route
	28, // 4: v2board.NodeConfigResponse.extra:type_name -> v2board.NodeConfigResponse.ExtraEntry
	29, // 5: v2board.UserInfo.extra:type_name -> v2board.UserInfo.ExtraEntry
	13, // 6: v2board.UserListResponse.users:type_name -> v2board.UserInfo
	0,  // 7: v2board.UserChangeNotification.type:type_name -> v2board.UserChangeNotification.ChangeType
	13, // 8: v2board.UserChangeNotification.user:type_name -> v2board.UserInfo
	30, // 9: v2board.TrafficReportRequest.traffics:type_name -> v2board.TrafficReportRequest.TrafficsEntry
	31, // 10: v2board.TrafficReportResponse.balances:type_name -> v2board.TrafficReportResponse.BalancesEntry
	32, // 11: v2board.OnlineReportRequest.online:type_name -> v2board.OnlineReportRequest.OnlineEntry
	8,  // 12: v2board.ConfigSyncResponse.config:type_name -> v2board.NodeConfigResponse
	13, // 13: v2board.ConfigSyncResponse.users:type_name -> v2board.UserInfo
	1,  // 14: v2board.ConfigChangeNotification.type:type_name -> v2board.ConfigChangeNotification.ChangeType
	2,  // 15: v2board.HealthCheckResponse.status:type_name -> v2board.HealthCheckResponse.ServingStatus
	17, // 16: v2board.TrafficReportRequest.TrafficsEntry.value:type_name -> v2board.TrafficData
	20, // 17: v2board.OnlineReportRequest.OnlineEntry.value:type_name -> v2board.OnlineData
	5,  // 18: v2board.NodeService.Register:input_type -> v2board.NodeRegisterRequest
	7,  // 19: v2board.NodeService.GetConfig:input_type -> v2board.NodeConfigRequest
	11, // 20: v2board.NodeService.ReportStatus:input_type -> v2board.NodeStatusRequest
	11, // 21: v2board.NodeService.StatusStream:input_type -> v2board.NodeStatusRequest
	12, // 22: v2board.UserService.GetUsers:input_type -> v2board.UserListRequest
	15, // 23: v2board.UserService.UserChanges:input_type -> v2board.UserChangeNotification
	16, // 24: v2board.TrafficService.ReportTraffic:input_type -> v2board.TrafficReportRequest
	19, // 25: v2board.TrafficService.ReportOnline:input_type -> v2board.OnlineReportRequest
	16, // 26: v2board.TrafficService.TrafficStream:input_type -> v2board.TrafficReportRequest
	19, // 27: v2board.TrafficService.OnlineStream:input_type -> v2board.OnlineReportRequest
	21, // 28: v2board.ConfigSyncService.SyncConfig:input_type -> v2board.ConfigSyncRequest
	23, // 29: v2board.ConfigSyncService.ConfigChanges:input_type -> v2board.ConfigChangeNotification
	21, // 30: v2board.ConfigSyncService.FullSync:input_type -> v2board.ConfigSyncRequest
	24, // 31: v2board.HealthService.Check:input_type -> v2board.HealthCheckRequest
	24, // 32: v2board.HealthService.Watch:input_type -> v2board.HealthCheckRequest
	6,  // 33: v2board.NodeService.Register:output_type -> v2board.NodeRegisterResponse
	8,  // 34: v2board.NodeService.GetConfig:output_type -> v2board.NodeConfigResponse
	4,  // 35: v2board.NodeService.ReportStatus:output_type -> v2board.StatusResponse
	8,  // 36: v2board.NodeService.StatusStream:output_type -> v2board.NodeConfigResponse
	14, // 37: v2board.UserService.GetUsers:output_type -> v2board.UserListResponse
	4,  // 38: v2board.UserService.UserChanges:output_type -> v2board.StatusResponse
	18, // 39: v2board.TrafficService.ReportTraffic:output_type -> v2board.TrafficReportResponse
	4,  // 40: v2board.TrafficService.ReportOnline:output_type -> v2board.StatusResponse
	18, // 41: v2board.TrafficService.TrafficStream:output_type -> v2board.TrafficReportResponse
	4,  // 42: v2board.TrafficService.OnlineStream:output_type -> v2board.StatusResponse
	22, // 43: v2board.ConfigSyncService.SyncConfig:output_type -> v2board.ConfigSyncResponse
	4,  // 44: v2board.ConfigSyncService.ConfigChanges:output_type -> v2board.StatusResponse
	22, // 45: v2board.ConfigSyncService.FullSync:output_type -> v2board.ConfigSyncResponse
	25, // 46: v2board.HealthService.Check:output_type -> v2board.HealthCheckResponse
	25, // 47: v2board.HealthService.Watch:output_type -> v2board.HealthCheckResponse
	33, // [33:48] is the sub-list for method output_type
	18, // [18:33] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_grpc_v2board_proto_init() }
func file_api_grpc_v2board_proto_init() {
	if File_api_grpc_v2board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v2board_proto_rawDesc), len(file_api_grpc_v2board_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_api_grpc_v2board_proto_goTypes,
		DependencyIndexes: file_api_grpc_v2board_proto_depIdxs,
		EnumInfos:         file_api_grpc_v2board_proto_enumTypes,
		MessageInfos:      file_api_grpc_v2board_proto_msgTypes,
	}.Build()
	File_api_grpc_v2board_proto = out.File
	file_api_grpc_v2board_proto_goTypes = nil
	file_api_grpc_v2board_proto_depIdxs = nil
}
