// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: api/grpc/v2board.proto

package v2boardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Register_FullMethodName     = "/v2board.NodeService/Register"
	NodeService_GetConfig_FullMethodName    = "/v2board.NodeService/GetConfig"
	NodeService_ReportStatus_FullMethodName = "/v2board.NodeService/ReportStatus"
	NodeService_StatusStream_FullMethodName = "/v2board.NodeService/StatusStream"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 节点服务
type NodeServiceClient interface {
	// 节点注册
	Register(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error)
	// 获取节点配置
	GetConfig(ctx context.Context, in *NodeConfigRequest, opts ...grpc.CallOption) (*NodeConfigResponse, error)
	// 上报节点状态 (替代心跳)
	ReportStatus(ctx context.Context, in *NodeStatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// 双向流：节点状态实时通信
	StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeStatusRequest, NodeConfigResponse], error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Register(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRegisterResponse)
	err := c.cc.Invoke(ctx, NodeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetConfig(ctx context.Context, in *NodeConfigRequest, opts ...grpc.CallOption) (*NodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeConfigResponse)
	err := c.cc.Invoke(ctx, NodeService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReportStatus(ctx context.Context, in *NodeStatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NodeService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeStatusRequest, NodeConfigResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_StatusStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeStatusRequest, NodeConfigResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StatusStreamClient = grpc.BidiStreamingClient[NodeStatusRequest, NodeConfigResponse]

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// 节点服务
type NodeServiceServer interface {
	// 节点注册
	Register(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error)
	// 获取节点配置
	GetConfig(context.Context, *NodeConfigRequest) (*NodeConfigResponse, error)
	// 上报节点状态 (替代心跳)
	ReportStatus(context.Context, *NodeStatusRequest) (*StatusResponse, error)
	// 双向流：节点状态实时通信
	StatusStream(grpc.BidiStreamingServer[NodeStatusRequest, NodeConfigResponse]) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Register(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodeServiceServer) GetConfig(context.Context, *NodeConfigRequest) (*NodeConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedNodeServiceServer) ReportStatus(context.Context, *NodeStatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedNodeServiceServer) StatusStream(grpc.BidiStreamingServer[NodeStatusRequest, NodeConfigResponse]) error {
	return status.Error(codes.Unimplemented, "method StatusStream not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Register(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetConfig(ctx, req.(*NodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReportStatus(ctx, req.(*NodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).StatusStream(&grpc.GenericServerStream[NodeStatusRequest, NodeConfigResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StatusStreamServer = grpc.BidiStreamingServer[NodeStatusRequest, NodeConfigResponse]

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v2board.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NodeService_Register_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _NodeService_GetConfig_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _NodeService_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusStream",
			Handler:       _NodeService_StatusStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/v2board.proto",
}

const (
	UserService_GetUsers_FullMethodName    = "/v2board.UserService/GetUsers"
	UserService_UserChanges_FullMethodName = "/v2board.UserService/UserChanges"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户服务
type UserServiceClient interface {
	// 获取用户列表
	GetUsers(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	// 双向流：用户变更实时推送
	// 面板推送用户变更，节点确认接收
	UserChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UserChangeNotification, StatusResponse], error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, UserService_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UserChangeNotification, StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_UserChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserChangeNotification, StatusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_UserChangesClient = grpc.BidiStreamingClient[UserChangeNotification, StatusResponse]

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// 用户服务
type UserServiceServer interface {
	// 获取用户列表
	GetUsers(context.Context, *UserListRequest) (*UserListResponse, error)
	// 双向流：用户变更实时推送
	// 面板推送用户变更，节点确认接收
	UserChanges(grpc.BidiStreamingServer[UserChangeNotification, StatusResponse]) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUsers(context.Context, *UserListRequest) (*UserListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedUserServiceServer) UserChanges(grpc.BidiStreamingServer[UserChangeNotification, StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method UserChanges not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).UserChanges(&grpc.GenericServerStream[UserChangeNotification, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_UserChangesServer = grpc.BidiStreamingServer[UserChangeNotification, StatusResponse]

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v2board.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UserChanges",
			Handler:       _UserService_UserChanges_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/v2board.proto",
}

const (
	TrafficService_ReportTraffic_FullMethodName = "/v2board.TrafficService/ReportTraffic"
	TrafficService_ReportOnline_FullMethodName  = "/v2board.TrafficService/ReportOnline"
	TrafficService_TrafficStream_FullMethodName = "/v2board.TrafficService/TrafficStream"
	TrafficService_OnlineStream_FullMethodName  = "/v2board.TrafficService/OnlineStream"
)

// TrafficServiceClient is the client API for TrafficService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 流量服务
type TrafficServiceClient interface {
	// 批量上报流量
	ReportTraffic(ctx context.Context, in *TrafficReportRequest, opts ...grpc.CallOption) (*TrafficReportResponse, error)
	// 上报在线状态
	ReportOnline(ctx context.Context, in *OnlineReportRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// 双向流：实时流量上报
	// 节点持续上报，面板实时响应
	TrafficStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TrafficReportRequest, TrafficReportResponse], error)
	// 双向流：实时在线状态
	OnlineStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OnlineReportRequest, StatusResponse], error)
}

type trafficServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficServiceClient(cc grpc.ClientConnInterface) TrafficServiceClient {
	return &trafficServiceClient{cc}
}

func (c *trafficServiceClient) ReportTraffic(ctx context.Context, in *TrafficReportRequest, opts ...grpc.CallOption) (*TrafficReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficReportResponse)
	err := c.cc.Invoke(ctx, TrafficService_ReportTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficServiceClient) ReportOnline(ctx context.Context, in *OnlineReportRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TrafficService_ReportOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficServiceClient) TrafficStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TrafficReportRequest, TrafficReportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrafficService_ServiceDesc.Streams[0], TrafficService_TrafficStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrafficReportRequest, TrafficReportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficService_TrafficStreamClient = grpc.BidiStreamingClient[TrafficReportRequest, TrafficReportResponse]

func (c *trafficServiceClient) OnlineStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OnlineReportRequest, StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrafficService_ServiceDesc.Streams[1], TrafficService_OnlineStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OnlineReportRequest, StatusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficService_OnlineStreamClient = grpc.BidiStreamingClient[OnlineReportRequest, StatusResponse]

// TrafficServiceServer is the server API for TrafficService service.
// All implementations must embed UnimplementedTrafficServiceServer
// for forward compatibility.
//
// 流量服务
type TrafficServiceServer interface {
	// 批量上报流量
	ReportTraffic(context.Context, *TrafficReportRequest) (*TrafficReportResponse, error)
	// 上报在线状态
	ReportOnline(context.Context, *OnlineReportRequest) (*StatusResponse, error)
	// 双向流：实时流量上报
	// 节点持续上报，面板实时响应
	TrafficStream(grpc.BidiStreamingServer[TrafficReportRequest, TrafficReportResponse]) error
	// 双向流：实时在线状态
	OnlineStream(grpc.BidiStreamingServer[OnlineReportRequest, StatusResponse]) error
	mustEmbedUnimplementedTrafficServiceServer()
}

// UnimplementedTrafficServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficServiceServer struct{}

func (UnimplementedTrafficServiceServer) ReportTraffic(context.Context, *TrafficReportRequest) (*TrafficReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTraffic not implemented")
}
func (UnimplementedTrafficServiceServer) ReportOnline(context.Context, *OnlineReportRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportOnline not implemented")
}
func (UnimplementedTrafficServiceServer) TrafficStream(grpc.BidiStreamingServer[TrafficReportRequest, TrafficReportResponse]) error {
	return status.Error(codes.Unimplemented, "method TrafficStream not implemented")
}
func (UnimplementedTrafficServiceServer) OnlineStream(grpc.BidiStreamingServer[OnlineReportRequest, StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method OnlineStream not implemented")
}
func (UnimplementedTrafficServiceServer) mustEmbedUnimplementedTrafficServiceServer() {}
func (UnimplementedTrafficServiceServer) testEmbeddedByValue()                        {}

// UnsafeTrafficServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficServiceServer will
// result in compilation errors.
type UnsafeTrafficServiceServer interface {
	mustEmbedUnimplementedTrafficServiceServer()
}

func RegisterTrafficServiceServer(s grpc.ServiceRegistrar, srv TrafficServiceServer) {
	// If the following call panics, it indicates UnimplementedTrafficServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficService_ServiceDesc, srv)
}

func _TrafficService_ReportTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).ReportTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_ReportTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).ReportTraffic(ctx, req.(*TrafficReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficService_ReportOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).ReportOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_ReportOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).ReportOnline(ctx, req.(*OnlineReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficService_TrafficStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficServiceServer).TrafficStream(&grpc.GenericServerStream[TrafficReportRequest, TrafficReportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficService_TrafficStreamServer = grpc.BidiStreamingServer[TrafficReportRequest, TrafficReportResponse]

func _TrafficService_OnlineStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficServiceServer).OnlineStream(&grpc.GenericServerStream[OnlineReportRequest, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficService_OnlineStreamServer = grpc.BidiStreamingServer[OnlineReportRequest, StatusResponse]

// TrafficService_ServiceDesc is the grpc.ServiceDesc for TrafficService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v2board.TrafficService",
	HandlerType: (*TrafficServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportTraffic",
			Handler:    _TrafficService_ReportTraffic_Handler,
		},
		{
			MethodName: "ReportOnline",
			Handler:    _TrafficService_ReportOnline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrafficStream",
			Handler:       _TrafficService_TrafficStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OnlineStream",
			Handler:       _TrafficService_OnlineStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/v2board.proto",
}

const (
	ConfigSyncService_SyncConfig_FullMethodName    = "/v2board.ConfigSyncService/SyncConfig"
	ConfigSyncService_ConfigChanges_FullMethodName = "/v2board.ConfigSyncService/ConfigChanges"
	ConfigSyncService_FullSync_FullMethodName      = "/v2board.ConfigSyncService/FullSync"
)

// ConfigSyncServiceClient is the client API for ConfigSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 配置同步服务
type ConfigSyncServiceClient interface {
	// 请求配置同步
	SyncConfig(ctx context.Context, in *ConfigSyncRequest, opts ...grpc.CallOption) (*ConfigSyncResponse, error)
	// 双向流：配置变更实时推送
	// 面板推送变更，节点确认接收
	ConfigChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConfigChangeNotification, StatusResponse], error)
	// 全量同步 (节点启动时)
	FullSync(ctx context.Context, in *ConfigSyncRequest, opts ...grpc.CallOption) (*ConfigSyncResponse, error)
}

type configSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigSyncServiceClient(cc grpc.ClientConnInterface) ConfigSyncServiceClient {
	return &configSyncServiceClient{cc}
}

func (c *configSyncServiceClient) SyncConfig(ctx context.Context, in *ConfigSyncRequest, opts ...grpc.CallOption) (*ConfigSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSyncResponse)
	err := c.cc.Invoke(ctx, ConfigSyncService_SyncConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configSyncServiceClient) ConfigChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConfigChangeNotification, StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigSyncService_ServiceDesc.Streams[0], ConfigSyncService_ConfigChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfigChangeNotification, StatusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSyncService_ConfigChangesClient = grpc.BidiStreamingClient[ConfigChangeNotification, StatusResponse]

func (c *configSyncServiceClient) FullSync(ctx context.Context, in *ConfigSyncRequest, opts ...grpc.CallOption) (*ConfigSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSyncResponse)
	err := c.cc.Invoke(ctx, ConfigSyncService_FullSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigSyncServiceServer is the server API for ConfigSyncService service.
// All implementations must embed UnimplementedConfigSyncServiceServer
// for forward compatibility.
//
// 配置同步服务
type ConfigSyncServiceServer interface {
	// 请求配置同步
	SyncConfig(context.Context, *ConfigSyncRequest) (*ConfigSyncResponse, error)
	// 双向流：配置变更实时推送
	// 面板推送变更，节点确认接收
	ConfigChanges(grpc.BidiStreamingServer[ConfigChangeNotification, StatusResponse]) error
	// 全量同步 (节点启动时)
	FullSync(context.Context, *ConfigSyncRequest) (*ConfigSyncResponse, error)
	mustEmbedUnimplementedConfigSyncServiceServer()
}

// UnimplementedConfigSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigSyncServiceServer struct{}

func (UnimplementedConfigSyncServiceServer) SyncConfig(context.Context, *ConfigSyncRequest) (*ConfigSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncConfig not implemented")
}
func (UnimplementedConfigSyncServiceServer) ConfigChanges(grpc.BidiStreamingServer[ConfigChangeNotification, StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method ConfigChanges not implemented")
}
func (UnimplementedConfigSyncServiceServer) FullSync(context.Context, *ConfigSyncRequest) (*ConfigSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FullSync not implemented")
}
func (UnimplementedConfigSyncServiceServer) mustEmbedUnimplementedConfigSyncServiceServer() {}
func (UnimplementedConfigSyncServiceServer) testEmbeddedByValue()                           {}

// UnsafeConfigSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigSyncServiceServer will
// result in compilation errors.
type UnsafeConfigSyncServiceServer interface {
	mustEmbedUnimplementedConfigSyncServiceServer()
}

func RegisterConfigSyncServiceServer(s grpc.ServiceRegistrar, srv ConfigSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigSyncService_ServiceDesc, srv)
}

func _ConfigSyncService_SyncConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSyncServiceServer).SyncConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSyncService_SyncConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSyncServiceServer).SyncConfig(ctx, req.(*ConfigSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigSyncService_ConfigChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigSyncServiceServer).ConfigChanges(&grpc.GenericServerStream[ConfigChangeNotification, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSyncService_ConfigChangesServer = grpc.BidiStreamingServer[ConfigChangeNotification, StatusResponse]

func _ConfigSyncService_FullSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSyncServiceServer).FullSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSyncService_FullSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSyncServiceServer).FullSync(ctx, req.(*ConfigSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigSyncService_ServiceDesc is the grpc.ServiceDesc for ConfigSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v2board.ConfigSyncService",
	HandlerType: (*ConfigSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncConfig",
			Handler:    _ConfigSyncService_SyncConfig_Handler,
		},
		{
			MethodName: "FullSync",
			Handler:    _ConfigSyncService_FullSync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConfigChanges",
			Handler:       _ConfigSyncService_ConfigChanges_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/v2board.proto",
}

const (
	HealthService_Check_FullMethodName = "/v2board.HealthService/Check"
	HealthService_Watch_FullMethodName = "/v2board.HealthService/Watch"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 健康检查服务
type HealthServiceClient interface {
	// 简单健康检查
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 双向流：持续健康检查
	Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HealthCheckRequest, HealthCheckResponse], error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, HealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HealthCheckRequest, HealthCheckResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HealthService_ServiceDesc.Streams[0], HealthService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HealthCheckRequest, HealthCheckResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthService_WatchClient = grpc.BidiStreamingClient[HealthCheckRequest, HealthCheckResponse]

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
//
// 健康检查服务
type HealthServiceServer interface {
	// 简单健康检查
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 双向流：持续健康检查
	Watch(grpc.BidiStreamingServer[HealthCheckRequest, HealthCheckResponse]) error
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServiceServer) Watch(grpc.BidiStreamingServer[HealthCheckRequest, HealthCheckResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthServiceServer).Watch(&grpc.GenericServerStream[HealthCheckRequest, HealthCheckResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthService_WatchServer = grpc.BidiStreamingServer[HealthCheckRequest, HealthCheckResponse]

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v2board.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _HealthService_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _HealthService_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/v2board.proto",
}
