// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: api/kerneltelemetry/v1/kernel_telemetry.proto

package kerneltelemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// refresh rebuilds the snapshot from the database and replaces the cached
	// one, as the v2 route's refresh=true does.
	Refresh       bool `protobuf:"varint,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_api_kerneltelemetry_v1_kernel_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kerneltelemetry_v1_kernel_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *GetDashboardRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

// GetDashboardResponse is the snapshot, field for field the kernel's
// service.DashboardStats. Amounts are in cents, traffic in bytes.
type GetDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveUsers   int64                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	ExpiredUsers  int64                  `protobuf:"varint,3,opt,name=expired_users,json=expiredUsers,proto3" json:"expired_users,omitempty"`
	BannedUsers   int64                  `protobuf:"varint,4,opt,name=banned_users,json=bannedUsers,proto3" json:"banned_users,omitempty"`
	TodayNewUsers int64                  `protobuf:"varint,5,opt,name=today_new_users,json=todayNewUsers,proto3" json:"today_new_users,omitempty"`
	TotalOrders   int64                  `protobuf:"varint,6,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	PendingOrders int64                  `protobuf:"varint,7,opt,name=pending_orders,json=pendingOrders,proto3" json:"pending_orders,omitempty"`
	PaidOrders    int64                  `protobuf:"varint,8,opt,name=paid_orders,json=paidOrders,proto3" json:"paid_orders,omitempty"`
	TotalRevenue  int64                  `protobuf:"varint,9,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	MonthlyIncome int64                  `protobuf:"varint,10,opt,name=monthly_income,json=monthlyIncome,proto3" json:"monthly_income,omitempty"`
	TodayIncome   int64                  `protobuf:"varint,11,opt,name=today_income,json=todayIncome,proto3" json:"today_income,omitempty"`
	TotalNodes    int64                  `protobuf:"varint,12,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	ActiveNodes   int64                  `protobuf:"varint,13,opt,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	// online_users counts the users in the kernel's alive set.
	OnlineUsers      int64 `protobuf:"varint,14,opt,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty"`
	TotalTrafficUsed int64 `protobuf:"varint,15,opt,name=total_traffic_used,json=totalTrafficUsed,proto3" json:"total_traffic_used,omitempty"`
	TodayTraffic     int64 `protobuf:"varint,16,opt,name=today_traffic,json=todayTraffic,proto3" json:"today_traffic,omitempty"`
	// cached_at is when the kernel built the snapshot: RFC 3339 with its
	// fraction and offset, as encoding/json writes the kernel's time, so a
	// module answers it byte for byte.
	CachedAt      string `protobuf:"bytes,17,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_api_kerneltelemetry_v1_kernel_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kerneltelemetry_v1_kernel_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *GetDashboardResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetDashboardResponse) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *GetDashboardResponse) GetExpiredUsers() int64 {
	if x != nil {
		return x.ExpiredUsers
	}
	return 0
}

func (x *GetDashboardResponse) GetBannedUsers() int64 {
	if x != nil {
		return x.BannedUsers
	}
	return 0
}

func (x *GetDashboardResponse) GetTodayNewUsers() int64 {
	if x != nil {
		return x.TodayNewUsers
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalOrders() int64 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *GetDashboardResponse) GetPendingOrders() int64 {
	if x != nil {
		return x.PendingOrders
	}
	return 0
}

func (x *GetDashboardResponse) GetPaidOrders() int64 {
	if x != nil {
		return x.PaidOrders
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *GetDashboardResponse) GetMonthlyIncome() int64 {
	if x != nil {
		return x.MonthlyIncome
	}
	return 0
}

func (x *GetDashboardResponse) GetTodayIncome() int64 {
	if x != nil {
		return x.TodayIncome
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalNodes() int64 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *GetDashboardResponse) GetActiveNodes() int64 {
	if x != nil {
		return x.ActiveNodes
	}
	return 0
}

func (x *GetDashboardResponse) GetOnlineUsers() int64 {
	if x != nil {
		return x.OnlineUsers
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalTrafficUsed() int64 {
	if x != nil {
		return x.TotalTrafficUsed
	}
	return 0
}

func (x *GetDashboardResponse) GetTodayTraffic() int64 {
	if x != nil {
		return x.TodayTraffic
	}
	return 0
}

func (x *GetDashboardResponse) GetCachedAt() string {
	if x != nil {
		return x.CachedAt
	}
	return ""
}

var File_api_kerneltelemetry_v1_kernel_telemetry_proto protoreflect.FileDescriptor

const file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDesc = "" +
	"\n" +
	"-api/kerneltelemetry/v1/kernel_telemetry.proto\x12\x1aanixops.kerneltelemetry.v1\"/\n" +
	"\x13GetDashboardRequest\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\bR\arefresh\"\xfb\x04\n" +
	"\x14GetDashboardResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x02 \x01(\x03R\vactiveUsers\x12#\n" +
	"\rexpired_users\x18\x03 \x01(\x03R\fexpiredUsers\x12!\n" +
	"\fbanned_users\x18\x04 \x01(\x03R\vbannedUsers\x12&\n" +
	"\x0ftoday_new_users\x18\x05 \x01(\x03R\rtodayNewUsers\x12!\n" +
	"\ftotal_orders\x18\x06 \x01(\x03R\vtotalOrders\x12%\n" +
	"\x0epending_orders\x18\a \x01(\x03R\rpendingOrders\x12\x1f\n" +
	"\vpaid_orders\x18\b \x01(\x03R\n" +
	"paidOrders\x12#\n" +
	"\rtotal_revenue\x18\t \x01(\x03R\ftotalRevenue\x12%\n" +
	"\x0emonthly_income\x18\n" +
	" \x01(\x03R\rmonthlyIncome\x12!\n" +
	"\ftoday_income\x18\v \x01(\x03R\vtodayIncome\x12\x1f\n" +
	"\vtotal_nodes\x18\f \x01(\x03R\n" +
	"totalNodes\x12!\n" +
	"\factive_nodes\x18\r \x01(\x03R\vactiveNodes\x12!\n" +
	"\fonline_users\x18\x0e \x01(\x03R\vonlineUsers\x12,\n" +
	"\x12total_traffic_used\x18\x0f \x01(\x03R\x10totalTrafficUsed\x12#\n" +
	"\rtoday_traffic\x18\x10 \x01(\x03R\ftodayTraffic\x12\x1b\n" +
	"\tcached_at\x18\x11 \x01(\tR\bcachedAt2\x84\x01\n" +
	"\x0fKernelTelemetry\x12q\n" +
	"\fGetDashboard\x12/.anixops.kerneltelemetry.v1.GetDashboardRequest\x1a0.anixops.kerneltelemetry.v1.GetDashboardResponseBNZLgithub.com/AnixOps/anix-control/sdk/api/kerneltelemetry/v1;kerneltelemetryv1b\x06proto3"

var (
	file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDescOnce sync.Once
	file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDescData []byte
)

func file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDescGZIP() []byte {
	file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDescOnce.Do(func() {
		file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDesc), len(file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDesc)))
	})
	return file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDescData
}

var file_api_kerneltelemetry_v1_kernel_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_kerneltelemetry_v1_kernel_telemetry_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),  // 0: anixops.kerneltelemetry.v1.GetDashboardRequest
	(*GetDashboardResponse)(nil), // 1: anixops.kerneltelemetry.v1.GetDashboardResponse
}
var file_api_kerneltelemetry_v1_kernel_telemetry_proto_depIdxs = []int32{
	0, // 0: anixops.kerneltelemetry.v1.KernelTelemetry.GetDashboard:input_type -> anixops.kerneltelemetry.v1.GetDashboardRequest
	1, // 1: anixops.kerneltelemetry.v1.KernelTelemetry.GetDashboard:output_type -> anixops.kerneltelemetry.v1.GetDashboardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_kerneltelemetry_v1_kernel_telemetry_proto_init() }
func file_api_kerneltelemetry_v1_kernel_telemetry_proto_init() {
	if File_api_kerneltelemetry_v1_kernel_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDesc), len(file_api_kerneltelemetry_v1_kernel_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kerneltelemetry_v1_kernel_telemetry_proto_goTypes,
		DependencyIndexes: file_api_kerneltelemetry_v1_kernel_telemetry_proto_depIdxs,
		MessageInfos:      file_api_kerneltelemetry_v1_kernel_telemetry_proto_msgTypes,
	}.Build()
	File_api_kerneltelemetry_v1_kernel_telemetry_proto = out.File
	file_api_kerneltelemetry_v1_kernel_telemetry_proto_goTypes = nil
	file_api_kerneltelemetry_v1_kernel_telemetry_proto_depIdxs = nil
}
