// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: api/grpc/agent/v1/agent.proto

package agentv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObservedPhase int32

const (
	ObservedPhase_OBSERVED_PHASE_UNSPECIFIED ObservedPhase = 0
	ObservedPhase_OBSERVED_PHASE_ACCEPTED    ObservedPhase = 1
	ObservedPhase_OBSERVED_PHASE_APPLYING    ObservedPhase = 2
	ObservedPhase_OBSERVED_PHASE_SUCCEEDED   ObservedPhase = 3
	ObservedPhase_OBSERVED_PHASE_FAILED      ObservedPhase = 4
	ObservedPhase_OBSERVED_PHASE_SUPERSEDED  ObservedPhase = 5
)

// Enum value maps for ObservedPhase.
var (
	ObservedPhase_name = map[int32]string{
		0: "OBSERVED_PHASE_UNSPECIFIED",
		1: "OBSERVED_PHASE_ACCEPTED",
		2: "OBSERVED_PHASE_APPLYING",
		3: "OBSERVED_PHASE_SUCCEEDED",
		4: "OBSERVED_PHASE_FAILED",
		5: "OBSERVED_PHASE_SUPERSEDED",
	}
	ObservedPhase_value = map[string]int32{
		"OBSERVED_PHASE_UNSPECIFIED": 0,
		"OBSERVED_PHASE_ACCEPTED":    1,
		"OBSERVED_PHASE_APPLYING":    2,
		"OBSERVED_PHASE_SUCCEEDED":   3,
		"OBSERVED_PHASE_FAILED":      4,
		"OBSERVED_PHASE_SUPERSEDED":  5,
	}
)

func (x ObservedPhase) Enum() *ObservedPhase {
	p := new(ObservedPhase)
	*p = x
	return p
}

func (x ObservedPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObservedPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ObservedPhase) Type() protoreflect.EnumType {
	return &file_api_grpc_agent_v1_agent_proto_enumTypes[0]
}

func (x ObservedPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObservedPhase.Descriptor instead.
func (ObservedPhase) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Capability) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Hello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Protocol     string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	AgentVersion string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	InstanceId   string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Capabilities []*Capability          `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels       map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// config_revision is the revision of the last ConfigSnapshot the Agent
	// applied, 0 for none. Control reads it only when config.v1 is negotiated.
	ConfigRevision uint64 `protobuf:"varint,6,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	// users_cursor is the cursor of the last UserDelta the Agent applied, 0 for
	// none. Control reads it only when users.v1 is negotiated.
	UsersCursor   uint64 `protobuf:"varint,7,opt,name=users_cursor,json=usersCursor,proto3" json:"users_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Hello) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Hello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Hello) GetConfigRevision() uint64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *Hello) GetUsersCursor() uint64 {
	if x != nil {
		return x.UsersCursor
	}
	return 0
}

type HelloAck struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SessionId                string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerTimeUnixMs         int64                  `protobuf:"varint,2,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	DesiredRevision          uint64                 `protobuf:"varint,4,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	// server_capabilities lists the data-plane features this Control serves on
	// the session: config.v1, users.v1, reports.v1, package-reports.v1,
	// forward.v1, maintenance.v1, alive.v1 and artifacts.v1 (Capability name
	// "config", "users", "reports", "package-reports", "forward",
	// "maintenance", "alive" or "artifacts", version "v1"). artifacts.v1
	// offers the AgentArtifacts service (artifacts.proto) and adds no
	// payload.
	// Control lists only features that Hello.capabilities lists too, so the
	// list is the negotiated set. Empty from a Control that serves none;
	// Agents built before this field ignore it.
	ServerCapabilities []*Capability `protobuf:"bytes,5,rep,name=server_capabilities,json=serverCapabilities,proto3" json:"server_capabilities,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HelloAck) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

func (x *HelloAck) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *HelloAck) GetDesiredRevision() uint64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *HelloAck) GetServerCapabilities() []*Capability {
	if x != nil {
		return x.ServerCapabilities
	}
	return nil
}

type Heartbeat struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ObservedRevision   uint64                 `protobuf:"varint,3,opt,name=observed_revision,json=observedRevision,proto3" json:"observed_revision,omitempty"`
	Metrics            map[string]float64     `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	PluginObservations []*PluginObservedState `protobuf:"bytes,5,rep,name=plugin_observations,json=pluginObservations,proto3" json:"plugin_observations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Heartbeat) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetObservedRevision() uint64 {
	if x != nil {
		return x.ObservedRevision
	}
	return 0
}

func (x *Heartbeat) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Heartbeat) GetPluginObservations() []*PluginObservedState {
	if x != nil {
		return x.PluginObservations
	}
	return nil
}

// PluginObservedState is a bounded, non-secret runtime observation emitted by
// an enabled Agent plugin. The kernel binds this to the operation version,
// revision, and config hash before a topology can be promoted.
type PluginObservedState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PluginId         string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DesiredRevision  uint64                 `protobuf:"varint,3,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	ObservedRevision uint64                 `protobuf:"varint,4,opt,name=observed_revision,json=observedRevision,proto3" json:"observed_revision,omitempty"`
	ConfigHash       string                 `protobuf:"bytes,5,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Health           string                 `protobuf:"bytes,6,opt,name=health,proto3" json:"health,omitempty"`
	RulesetSha256    string                 `protobuf:"bytes,7,opt,name=ruleset_sha256,json=rulesetSha256,proto3" json:"ruleset_sha256,omitempty"`
	ObservedAtUnixMs int64                  `protobuf:"varint,8,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	RuleCounters     []*PluginRuleCounter   `protobuf:"bytes,9,rep,name=rule_counters,json=ruleCounters,proto3" json:"rule_counters,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginObservedState) Reset() {
	*x = PluginObservedState{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginObservedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginObservedState) ProtoMessage() {}

func (x *PluginObservedState) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginObservedState.ProtoReflect.Descriptor instead.
func (*PluginObservedState) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PluginObservedState) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginObservedState) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginObservedState) GetDesiredRevision() uint64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *PluginObservedState) GetObservedRevision() uint64 {
	if x != nil {
		return x.ObservedRevision
	}
	return 0
}

func (x *PluginObservedState) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *PluginObservedState) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *PluginObservedState) GetRulesetSha256() string {
	if x != nil {
		return x.RulesetSha256
	}
	return ""
}

func (x *PluginObservedState) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

func (x *PluginObservedState) GetRuleCounters() []*PluginRuleCounter {
	if x != nil {
		return x.RuleCounters
	}
	return nil
}

type PluginRuleCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Packets       uint64                 `protobuf:"varint,2,opt,name=packets,proto3" json:"packets,omitempty"`
	Bytes         uint64                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRuleCounter) Reset() {
	*x = PluginRuleCounter{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRuleCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRuleCounter) ProtoMessage() {}

func (x *PluginRuleCounter) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRuleCounter.ProtoReflect.Descriptor instead.
func (*PluginRuleCounter) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PluginRuleCounter) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *PluginRuleCounter) GetPackets() uint64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *PluginRuleCounter) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type HeartbeatAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerTimeUnixMs int64                  `protobuf:"varint,2,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	DesiredRevision  uint64                 `protobuf:"varint,3,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatAck) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

func (x *HeartbeatAck) GetDesiredRevision() uint64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

type DesiredOperation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Kind           string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Revision       uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	PayloadJson    []byte                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DesiredOperation) Reset() {
	*x = DesiredOperation{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredOperation) ProtoMessage() {}

func (x *DesiredOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredOperation.ProtoReflect.Descriptor instead.
func (*DesiredOperation) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DesiredOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *DesiredOperation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DesiredOperation) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DesiredOperation) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *DesiredOperation) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type OperationAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Accepted         bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error            string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	AcceptedAtUnixMs int64                  `protobuf:"varint,4,opt,name=accepted_at_unix_ms,json=acceptedAtUnixMs,proto3" json:"accepted_at_unix_ms,omitempty"`
	SessionId        string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Revision         uint64                 `protobuf:"varint,6,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OperationAck) Reset() {
	*x = OperationAck{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationAck) ProtoMessage() {}

func (x *OperationAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationAck.ProtoReflect.Descriptor instead.
func (*OperationAck) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *OperationAck) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *OperationAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OperationAck) GetAcceptedAtUnixMs() int64 {
	if x != nil {
		return x.AcceptedAtUnixMs
	}
	return 0
}

func (x *OperationAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OperationAck) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ObservedState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Revision         uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Phase            ObservedPhase          `protobuf:"varint,3,opt,name=phase,proto3,enum=anix.agent.v1.ObservedPhase" json:"phase,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	StateJson        []byte                 `protobuf:"bytes,5,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	ObservedAtUnixMs int64                  `protobuf:"varint,6,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	SessionId        string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ObservedState) Reset() {
	*x = ObservedState{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedState) ProtoMessage() {}

func (x *ObservedState) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedState.ProtoReflect.Descriptor instead.
func (*ObservedState) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ObservedState) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ObservedState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ObservedState) GetPhase() ObservedPhase {
	if x != nil {
		return x.Phase
	}
	return ObservedPhase_OBSERVED_PHASE_UNSPECIFIED
}

func (x *ObservedState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ObservedState) GetStateJson() []byte {
	if x != nil {
		return x.StateJson
	}
	return nil
}

func (x *ObservedState) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

func (x *ObservedState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AgentToControl struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RequestId    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NodeId       uint32                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Revision     uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	SentAtUnixMs int64                  `protobuf:"varint,4,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentToControl_Hello
	//	*AgentToControl_Heartbeat
	//	*AgentToControl_OperationAck
	//	*AgentToControl_ObservedState
	//	*AgentToControl_ConfigStatus
	//	*AgentToControl_Traffic
	//	*AgentToControl_Logs
	//	*AgentToControl_Status
	//	*AgentToControl_PackageReport
	//	*AgentToControl_MaintenanceEvents
	Payload       isAgentToControl_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToControl) Reset() {
	*x = AgentToControl{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToControl) ProtoMessage() {}

func (x *AgentToControl) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToControl.ProtoReflect.Descriptor instead.
func (*AgentToControl) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentToControl) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentToControl) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AgentToControl) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *AgentToControl) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *AgentToControl) GetPayload() isAgentToControl_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentToControl) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentToControl) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToControl) GetOperationAck() *OperationAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_OperationAck); ok {
			return x.OperationAck
		}
	}
	return nil
}

func (x *AgentToControl) GetObservedState() *ObservedState {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_ObservedState); ok {
			return x.ObservedState
		}
	}
	return nil
}

func (x *AgentToControl) GetConfigStatus() *ConfigStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_ConfigStatus); ok {
			return x.ConfigStatus
		}
	}
	return nil
}

func (x *AgentToControl) GetTraffic() *TrafficReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_Traffic); ok {
			return x.Traffic
		}
	}
	return nil
}

func (x *AgentToControl) GetLogs() *LogBatch {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *AgentToControl) GetStatus() *NodeStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentToControl) GetPackageReport() *PackageReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_PackageReport); ok {
			return x.PackageReport
		}
	}
	return nil
}

func (x *AgentToControl) GetMaintenanceEvents() *MaintenanceEvents {
	if x != nil {
		if x, ok := x.Payload.(*AgentToControl_MaintenanceEvents); ok {
			return x.MaintenanceEvents
		}
	}
	return nil
}

type isAgentToControl_Payload interface {
	isAgentToControl_Payload()
}

type AgentToControl_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type AgentToControl_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type AgentToControl_OperationAck struct {
	OperationAck *OperationAck `protobuf:"bytes,12,opt,name=operation_ack,json=operationAck,proto3,oneof"`
}

type AgentToControl_ObservedState struct {
	ObservedState *ObservedState `protobuf:"bytes,13,opt,name=observed_state,json=observedState,proto3,oneof"`
}

type AgentToControl_ConfigStatus struct {
	// Data plane. Sent only when the capability is negotiated (see
	// HelloAck.server_capabilities): config_status with config.v1, the others
	// with reports.v1.
	ConfigStatus *ConfigStatus `protobuf:"bytes,14,opt,name=config_status,json=configStatus,proto3,oneof"`
}

type AgentToControl_Traffic struct {
	Traffic *TrafficReport `protobuf:"bytes,15,opt,name=traffic,proto3,oneof"`
}

type AgentToControl_Logs struct {
	Logs *LogBatch `protobuf:"bytes,16,opt,name=logs,proto3,oneof"`
}

type AgentToControl_Status struct {
	Status *NodeStatus `protobuf:"bytes,17,opt,name=status,proto3,oneof"`
}

type AgentToControl_PackageReport struct {
	// Sent only with package-reports.v1 negotiated. Never acknowledged.
	PackageReport *PackageReport `protobuf:"bytes,18,opt,name=package_report,json=packageReport,proto3,oneof"`
}

type AgentToControl_MaintenanceEvents struct {
	// Sent only with maintenance.v1 negotiated: a batch of the Agent's
	// maintenance outbox. Control answers it with maintenance_ack.
	MaintenanceEvents *MaintenanceEvents `protobuf:"bytes,19,opt,name=maintenance_events,json=maintenanceEvents,proto3,oneof"`
}

func (*AgentToControl_Hello) isAgentToControl_Payload() {}

func (*AgentToControl_Heartbeat) isAgentToControl_Payload() {}

func (*AgentToControl_OperationAck) isAgentToControl_Payload() {}

func (*AgentToControl_ObservedState) isAgentToControl_Payload() {}

func (*AgentToControl_ConfigStatus) isAgentToControl_Payload() {}

func (*AgentToControl_Traffic) isAgentToControl_Payload() {}

func (*AgentToControl_Logs) isAgentToControl_Payload() {}

func (*AgentToControl_Status) isAgentToControl_Payload() {}

func (*AgentToControl_PackageReport) isAgentToControl_Payload() {}

func (*AgentToControl_MaintenanceEvents) isAgentToControl_Payload() {}

type ControlToAgent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RequestId    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NodeId       uint32                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Revision     uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	SentAtUnixMs int64                  `protobuf:"varint,4,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlToAgent_HelloAck
	//	*ControlToAgent_HeartbeatAck
	//	*ControlToAgent_DesiredOperation
	//	*ControlToAgent_Config
	//	*ControlToAgent_Users
	//	*ControlToAgent_ReportAck
	//	*ControlToAgent_MaintenanceAck
	//	*ControlToAgent_AliveList
	Payload       isControlToAgent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlToAgent) Reset() {
	*x = ControlToAgent{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlToAgent) ProtoMessage() {}

func (x *ControlToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlToAgent.ProtoReflect.Descriptor instead.
func (*ControlToAgent) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ControlToAgent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ControlToAgent) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ControlToAgent) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ControlToAgent) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *ControlToAgent) GetPayload() isControlToAgent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlToAgent) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*ControlToAgent_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ControlToAgent) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ControlToAgent_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ControlToAgent) GetDesiredOperation() *DesiredOperation {
	if x != nil {
		if x, ok := x.Payload.(*ControlToAgent_DesiredOperation); ok {
			return x.DesiredOperation
		}
	}
	return nil
}

func (x *ControlToAgent) GetConfig() *ConfigSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*ControlToAgent_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ControlToAgent) GetUsers() *UserDelta {
	if x != nil {
		if x, ok := x.Payload.(*ControlToAgent_Users); ok {
			return x.Users
		}
	}
	return nil
}

func (x *ControlToAgent) GetReportAck() *ReportAck {
	if x != nil {
		if x, ok := x.Payload.(*ControlToAgent_ReportAck); ok {
			return x.ReportAck
		}
	}
	return nil
}

func (x *ControlToAgent) GetMaintenanceAck() *MaintenanceAck {
	if x != nil {
		if x, ok := x.Payload.(*ControlToAgent_MaintenanceAck); ok {
			return x.MaintenanceAck
		}
	}
	return nil
}

func (x *ControlToAgent) GetAliveList() *AliveList {
	if x != nil {
		if x, ok := x.Payload.(*ControlToAgent_AliveList); ok {
			return x.AliveList
		}
	}
	return nil
}

type isControlToAgent_Payload interface {
	isControlToAgent_Payload()
}

type ControlToAgent_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,10,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ControlToAgent_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,11,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ControlToAgent_DesiredOperation struct {
	DesiredOperation *DesiredOperation `protobuf:"bytes,12,opt,name=desired_operation,json=desiredOperation,proto3,oneof"`
}

type ControlToAgent_Config struct {
	// Data plane. Sent only when the capability is negotiated (see
	// HelloAck.server_capabilities): config with config.v1, users with
	// users.v1, report_ack in answer to a report sent with reports.v1.
	Config *ConfigSnapshot `protobuf:"bytes,13,opt,name=config,proto3,oneof"`
}

type ControlToAgent_Users struct {
	Users *UserDelta `protobuf:"bytes,14,opt,name=users,proto3,oneof"`
}

type ControlToAgent_ReportAck struct {
	ReportAck *ReportAck `protobuf:"bytes,15,opt,name=report_ack,json=reportAck,proto3,oneof"`
}

type ControlToAgent_MaintenanceAck struct {
	// Answers maintenance_events (maintenance.v1), with the request_id of
	// the message it answers.
	MaintenanceAck *MaintenanceAck `protobuf:"bytes,16,opt,name=maintenance_ack,json=maintenanceAck,proto3,oneof"`
}

type ControlToAgent_AliveList struct {
	// Sent only with alive.v1 negotiated: one page of the online device
	// counts of every user, across all nodes (UniProxy alivelist).
	AliveList *AliveList `protobuf:"bytes,17,opt,name=alive_list,json=aliveList,proto3,oneof"`
}

func (*ControlToAgent_HelloAck) isControlToAgent_Payload() {}

func (*ControlToAgent_HeartbeatAck) isControlToAgent_Payload() {}

func (*ControlToAgent_DesiredOperation) isControlToAgent_Payload() {}

func (*ControlToAgent_Config) isControlToAgent_Payload() {}

func (*ControlToAgent_Users) isControlToAgent_Payload() {}

func (*ControlToAgent_ReportAck) isControlToAgent_Payload() {}

func (*ControlToAgent_MaintenanceAck) isControlToAgent_Payload() {}

func (*ControlToAgent_AliveList) isControlToAgent_Payload() {}

// ConfigSnapshot is a node's whole configuration at one revision (config.v1).
// Control sends it after HelloAck when Hello.config_revision is older, and
// whenever the node's desired configuration changes. It replaces what the
// Agent runs, so a lost or repeated snapshot is harmless.
type ConfigSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config_revision increases with every change of the node's desired
	// configuration.
	ConfigRevision uint64 `protobuf:"varint,1,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	// config_hash is the lowercase hex SHA-256 of the exact config_json bytes.
	ConfigHash string `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// format names the schema of config_json. An Agent that does not know it
	// answers ConfigStatus with applied false.
	Format        string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	ConfigJson    []byte `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigSnapshot) GetConfigRevision() uint64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *ConfigSnapshot) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ConfigSnapshot) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ConfigSnapshot) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

// ConfigStatus answers a ConfigSnapshot (config.v1): applied, or failed with
// an error. A failure becomes the node's runtime health.
type ConfigStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigRevision uint64                 `protobuf:"varint,1,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	ConfigHash     string                 `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Applied        bool                   `protobuf:"varint,3,opt,name=applied,proto3" json:"applied,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// error_code names why the configuration was not applied, one of the
	// agentcontrol.ConfigErrorCode* codes (config_format_unsupported,
	// config_hash_mismatch, config_invalid, config_apply_failed); empty when
	// applied, and from Agents built before it. error stays the text.
	ErrorCode     string `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigStatus) Reset() {
	*x = ConfigStatus{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigStatus) ProtoMessage() {}

func (x *ConfigStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigStatus.ProtoReflect.Descriptor instead.
func (*ConfigStatus) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigStatus) GetConfigRevision() uint64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *ConfigStatus) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ConfigStatus) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ConfigStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConfigStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// NodeUser is one user the node serves.
type NodeUser struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uuid   string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// speed_limit_mbps is 0 for no limit.
	SpeedLimitMbps int64 `protobuf:"varint,3,opt,name=speed_limit_mbps,json=speedLimitMbps,proto3" json:"speed_limit_mbps,omitempty"`
	// device_limit is 0 for no limit.
	DeviceLimit int32 `protobuf:"varint,4,opt,name=device_limit,json=deviceLimit,proto3" json:"device_limit,omitempty"`
	// extra_json holds protocol-specific fields, such as WireGuard peer keys.
	ExtraJson     []byte `protobuf:"bytes,5,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeUser) Reset() {
	*x = NodeUser{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUser) ProtoMessage() {}

func (x *NodeUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUser.ProtoReflect.Descriptor instead.
func (*NodeUser) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *NodeUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NodeUser) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NodeUser) GetSpeedLimitMbps() int64 {
	if x != nil {
		return x.SpeedLimitMbps
	}
	return 0
}

func (x *NodeUser) GetDeviceLimit() int32 {
	if x != nil {
		return x.DeviceLimit
	}
	return 0
}

func (x *NodeUser) GetExtraJson() []byte {
	if x != nil {
		return x.ExtraJson
	}
	return nil
}

// UserDelta carries the node's user changes after the Agent's cursor
// (users.v1). One delta may span several messages: the Agent applies them
// together when the one with last_page arrives, then stores cursor and
// resumes from it in Hello.users_cursor. With full, the pages together are
// the node's whole user set and replace the Agent's; otherwise they are
// changes, applied in order.
type UserDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cursor         uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Full           bool                   `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	LastPage       bool                   `protobuf:"varint,3,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
	Upserts        []*NodeUser            `protobuf:"bytes,4,rep,name=upserts,proto3" json:"upserts,omitempty"`
	RemovedUserIds []uint64               `protobuf:"varint,5,rep,packed,name=removed_user_ids,json=removedUserIds,proto3" json:"removed_user_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserDelta) Reset() {
	*x = UserDelta{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelta) ProtoMessage() {}

func (x *UserDelta) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelta.ProtoReflect.Descriptor instead.
func (*UserDelta) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *UserDelta) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *UserDelta) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *UserDelta) GetLastPage() bool {
	if x != nil {
		return x.LastPage
	}
	return false
}

func (x *UserDelta) GetUpserts() []*NodeUser {
	if x != nil {
		return x.Upserts
	}
	return nil
}

func (x *UserDelta) GetRemovedUserIds() []uint64 {
	if x != nil {
		return x.RemovedUserIds
	}
	return nil
}

// TrafficReport carries per-user traffic and online IPs for one window
// (reports.v1). Control records a batch_id once and answers ReportAck.
type TrafficReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// batch_id is unique per node and kept when the batch is resent:
	// node:<kind>-<id>:<boot id>:<sequence>.
	BatchId         string         `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Users           []*UserTraffic `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Online          []*OnlineUser  `protobuf:"bytes,3,rep,name=online,proto3" json:"online,omitempty"`
	WindowEndUnixMs int64          `protobuf:"varint,4,opt,name=window_end_unix_ms,json=windowEndUnixMs,proto3" json:"window_end_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *TrafficReport) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *TrafficReport) GetUsers() []*UserTraffic {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *TrafficReport) GetOnline() []*OnlineUser {
	if x != nil {
		return x.Online
	}
	return nil
}

func (x *TrafficReport) GetWindowEndUnixMs() int64 {
	if x != nil {
		return x.WindowEndUnixMs
	}
	return 0
}

// UserTraffic is one user's traffic in a TrafficReport window.
type UserTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UploadBytes   uint64                 `protobuf:"varint,2,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes uint64                 `protobuf:"varint,3,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *UserTraffic) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserTraffic) GetUploadBytes() uint64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *UserTraffic) GetDownloadBytes() uint64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

// OnlineUser is one user's online IPs at the end of a TrafficReport window.
type OnlineUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ips           []string               `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUser) Reset() {
	*x = OnlineUser{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUser) ProtoMessage() {}

func (x *OnlineUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUser.ProtoReflect.Descriptor instead.
func (*OnlineUser) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *OnlineUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OnlineUser) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// LogBatch carries node runtime logs (reports.v1). Control records a
// batch_id once and answers ReportAck.
type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *LogBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// LogEntry is one node runtime log line.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// level is debug, info, warning or error.
	Level          string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Source         string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Message        string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LoggedAtUnixMs int64  `protobuf:"varint,4,opt,name=logged_at_unix_ms,json=loggedAtUnixMs,proto3" json:"logged_at_unix_ms,omitempty"`
	// fields_json is a JSON object of structured fields, without secrets.
	FieldsJson    []byte `protobuf:"bytes,5,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`
	TraceId       string `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetLoggedAtUnixMs() int64 {
	if x != nil {
		return x.LoggedAtUnixMs
	}
	return 0
}

func (x *LogEntry) GetFieldsJson() []byte {
	if x != nil {
		return x.FieldsJson
	}
	return nil
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// ReportAck answers a TrafficReport or LogBatch by batch_id. applied is true
// when this delivery recorded the batch, and false when Control had recorded
// it before (error empty) or refuses it for good (error set). In each case the
// Agent drops the batch from its spool. Control sends no ReportAck for a batch
// it cannot record for now, and the Agent resends it later.
type ReportAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BatchId string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Applied bool                   `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// error_code names the refusal, one of the agentcontrol.ReportErrorCode*
	// codes, whenever error is set. With report_unavailable (error empty),
	// Control could not record the batch now: the Agent keeps it and sends
	// it again, not before retry_after_ms. Control sends that transient
	// answer only to an Agent whose Hello listed reports.v1 with the
	// attribute transient_ack "v1", and echoes the attribute in
	// HelloAck.server_capabilities; other Agents get no ReportAck for such a
	// batch, as before. PROTOCOL.md, "Error codes".
	ErrorCode string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// retry_after_ms is the least wait before the batch is sent again; set
	// only with report_unavailable.
	RetryAfterMs  uint32 `protobuf:"varint,5,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ReportAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *ReportAck) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ReportAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportAck) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ReportAck) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// NodeStatus is the node's system and runtime health (reports.v1). Each one
// replaces the previous; Control does not acknowledge it.
type NodeStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent    float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent float64                `protobuf:"fixed64,2,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	DiskUsagePercent   float64                `protobuf:"fixed64,3,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	// uptime_seconds counts from the Agent's start.
	UptimeSeconds    int64  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	RuntimeHealthy   bool   `protobuf:"varint,5,opt,name=runtime_healthy,json=runtimeHealthy,proto3" json:"runtime_healthy,omitempty"`
	RuntimeError     string `protobuf:"bytes,6,opt,name=runtime_error,json=runtimeError,proto3" json:"runtime_error,omitempty"`
	ObservedAtUnixMs int64  `protobuf:"varint,7,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *NodeStatus) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeStatus) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *NodeStatus) GetDiskUsagePercent() float64 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *NodeStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeStatus) GetRuntimeHealthy() bool {
	if x != nil {
		return x.RuntimeHealthy
	}
	return false
}

func (x *NodeStatus) GetRuntimeError() string {
	if x != nil {
		return x.RuntimeError
	}
	return ""
}

func (x *NodeStatus) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

// PackageReport is the latest observation of one kind that an Agent plugin
// package reports for the node (package-reports.v1). Each one replaces the
// previous report of the same node, plugin_id and kind; Control keeps no
// history and does not acknowledge it, and the Agent neither spools nor
// resends it. Control accepts it only when the node's assigned release of
// plugin_id at version is a signed official Agent release whose manifest
// declares the capability Control requires for kind; otherwise it drops the
// report and the stream stays open. PROTOCOL.md, "Package reports".
type PackageReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// plugin_id is the package that produced the report.
	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// kind names the payload schema, lowercase dot-separated words such as
	// systemd.services; a new schema version is a new kind.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// version is the release of plugin_id the Agent runs; it must be the
	// version assigned to the node.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// payload_json is a JSON object in the schema of kind, at most 256 KiB.
	PayloadJson []byte `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	// observed_at_unix_ms is when the plugin took the observation; 0 means
	// when Control received it.
	ObservedAtUnixMs int64 `protobuf:"varint,5,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PackageReport) Reset() {
	*x = PackageReport{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageReport) ProtoMessage() {}

func (x *PackageReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageReport.ProtoReflect.Descriptor instead.
func (*PackageReport) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *PackageReport) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PackageReport) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PackageReport) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageReport) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *PackageReport) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

// MaintenanceEvents is a batch of the Agent's durable maintenance outbox
// (maintenance.v1): the plugin health incidents and recoveries the Agent
// keeps until Control has stored them. It carries what the legacy agent
// WebSocket's maintenance_events message carries. PROTOCOL.md,
// "Maintenance events".
type MaintenanceEvents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the event schema, anixops.maintenance/v1.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// events_json are the events, oldest first: each one JSON object of the
	// version's event schema, at most 16 KiB, and at most 50 per batch.
	EventsJson    [][]byte `protobuf:"bytes,2,rep,name=events_json,json=eventsJson,proto3" json:"events_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceEvents) Reset() {
	*x = MaintenanceEvents{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceEvents) ProtoMessage() {}

func (x *MaintenanceEvents) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceEvents.ProtoReflect.Descriptor instead.
func (*MaintenanceEvents) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *MaintenanceEvents) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MaintenanceEvents) GetEventsJson() [][]byte {
	if x != nil {
		return x.EventsJson
	}
	return nil
}

// MaintenanceAck answers MaintenanceEvents with one result per event, in
// the batch's order.
type MaintenanceAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the version of the batch it answers.
	Version       string                    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Events        []*MaintenanceEventResult `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceAck) Reset() {
	*x = MaintenanceAck{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceAck) ProtoMessage() {}

func (x *MaintenanceAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceAck.ProtoReflect.Descriptor instead.
func (*MaintenanceAck) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *MaintenanceAck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MaintenanceAck) GetEvents() []*MaintenanceEventResult {
	if x != nil {
		return x.Events
	}
	return nil
}

// MaintenanceEventResult is Control's answer for one maintenance event.
type MaintenanceEventResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is the event's event_id, empty when the event could not be
	// read.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// persisted is true when Control has stored the event, by this delivery
	// or an earlier one: the Agent removes it from its outbox.
	Persisted bool `protobuf:"varint,2,opt,name=persisted,proto3" json:"persisted,omitempty"`
	// error is set when Control refuses the event for good; it refuses it
	// again on every delivery. persisted false without an error means Control
	// could not store the event now, and the Agent sends it again later.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// error_code names the refusal, one of the
	// agentcontrol.MaintenanceErrorCode* codes, whenever error is set. With
	// maintenance_unavailable (error empty, persisted false) Control could
	// not store the event now: the Agent keeps it and sends it again, not
	// before retry_after_ms.
	ErrorCode string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// retry_after_ms is the least wait before the event is sent again; set
	// only with maintenance_unavailable.
	RetryAfterMs  uint32 `protobuf:"varint,5,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceEventResult) Reset() {
	*x = MaintenanceEventResult{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceEventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceEventResult) ProtoMessage() {}

func (x *MaintenanceEventResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceEventResult.ProtoReflect.Descriptor instead.
func (*MaintenanceEventResult) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *MaintenanceEventResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MaintenanceEventResult) GetPersisted() bool {
	if x != nil {
		return x.Persisted
	}
	return false
}

func (x *MaintenanceEventResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MaintenanceEventResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MaintenanceEventResult) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// AliveList is the number of online devices (distinct IPs) of every user
// with at least one, across all nodes (alive.v1): what UniProxy alivelist
// answers, from the same source. The Agent enforces NodeUser.device_limit
// against it. One list may span several messages, the users in id order,
// each page with the same revision: the Agent replaces its whole list when
// the page with last_page arrives. Control sends a list after HelloAck and
// then whenever the counts change, at most once a minute. A user missing
// from the list has no device online. PROTOCOL.md, "Alive list".
type AliveList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// revision increases with every list Control sends on the session.
	Revision uint64       `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	LastPage bool         `protobuf:"varint,2,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
	Entries  []*UserAlive `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	// computed_at_unix_ms is when Control counted the devices.
	ComputedAtUnixMs int64 `protobuf:"varint,4,opt,name=computed_at_unix_ms,json=computedAtUnixMs,proto3" json:"computed_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AliveList) Reset() {
	*x = AliveList{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveList) ProtoMessage() {}

func (x *AliveList) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveList.ProtoReflect.Descriptor instead.
func (*AliveList) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{27}
}

func (x *AliveList) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *AliveList) GetLastPage() bool {
	if x != nil {
		return x.LastPage
	}
	return false
}

func (x *AliveList) GetEntries() []*UserAlive {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AliveList) GetComputedAtUnixMs() int64 {
	if x != nil {
		return x.ComputedAtUnixMs
	}
	return 0
}

// UserAlive is one user's online device count in an AliveList.
type UserAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AliveCount    uint32                 `protobuf:"varint,2,opt,name=alive_count,json=aliveCount,proto3" json:"alive_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAlive) Reset() {
	*x = UserAlive{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAlive) ProtoMessage() {}

func (x *UserAlive) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAlive.ProtoReflect.Descriptor instead.
func (*UserAlive) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{28}
}

func (x *UserAlive) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserAlive) GetAliveCount() uint32 {
	if x != nil {
		return x.AliveCount
	}
	return 0
}

var File_api_grpc_agent_v1_agent_proto protoreflect.FileDescriptor

const file_api_grpc_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/grpc/agent/v1/agent.proto\x12\ranix.agent.v1\"\xc4\x01\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12I\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2).anix.agent.v1.Capability.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x02\n" +
	"\x05Hello\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12=\n" +
	"\fcapabilities\x18\x04 \x03(\v2\x19.anix.agent.v1.CapabilityR\fcapabilities\x128\n" +
	"\x06labels\x18\x05 \x03(\v2 .anix.agent.v1.Hello.LabelsEntryR\x06labels\x12'\n" +
	"\x0fconfig_revision\x18\x06 \x01(\x04R\x0econfigRevision\x12!\n" +
	"\fusers_cursor\x18\a \x01(\x04R\vusersCursor\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\bHelloAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x13server_time_unix_ms\x18\x02 \x01(\x03R\x10serverTimeUnixMs\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\rR\x18heartbeatIntervalSeconds\x12)\n" +
	"\x10desired_revision\x18\x04 \x01(\x04R\x0fdesiredRevision\x12J\n" +
	"\x13server_capabilities\x18\x05 \x03(\v2\x19.anix.agent.v1.CapabilityR\x12serverCapabilities\"\xd0\x02\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12+\n" +
	"\x11observed_revision\x18\x03 \x01(\x04R\x10observedRevision\x12?\n" +
	"\ametrics\x18\x04 \x03(\v2%.anix.agent.v1.Heartbeat.MetricsEntryR\ametrics\x12S\n" +
	"\x13plugin_observations\x18\x05 \x03(\v2\".anix.agent.v1.PluginObservedStateR\x12pluginObservations\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xfa\x02\n" +
	"\x13PluginObservedState\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10desired_revision\x18\x03 \x01(\x04R\x0fdesiredRevision\x12+\n" +
	"\x11observed_revision\x18\x04 \x01(\x04R\x10observedRevision\x12\x1f\n" +
	"\vconfig_hash\x18\x05 \x01(\tR\n" +
	"configHash\x12\x16\n" +
	"\x06health\x18\x06 \x01(\tR\x06health\x12%\n" +
	"\x0eruleset_sha256\x18\a \x01(\tR\rrulesetSha256\x12-\n" +
	"\x13observed_at_unix_ms\x18\b \x01(\x03R\x10observedAtUnixMs\x12E\n" +
	"\rrule_counters\x18\t \x03(\v2 .anix.agent.v1.PluginRuleCounterR\fruleCounters\"\\\n" +
	"\x11PluginRuleCounter\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x18\n" +
	"\apackets\x18\x02 \x01(\x04R\apackets\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x04R\x05bytes\"\x87\x01\n" +
	"\fHeartbeatAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x13server_time_unix_ms\x18\x02 \x01(\x03R\x10serverTimeUnixMs\x12)\n" +
	"\x10desired_revision\x18\x03 \x01(\x04R\x0fdesiredRevision\"\xb2\x01\n" +
	"\x10DesiredOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\fR\vpayloadJson\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"\xcd\x01\n" +
	"\fOperationAck\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12-\n" +
	"\x13accepted_at_unix_ms\x18\x04 \x01(\x03R\x10acceptedAtUnixMs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1a\n" +
	"\brevision\x18\x06 \x01(\x04R\brevision\"\x89\x02\n" +
	"\rObservedState\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x122\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x1c.anix.agent.v1.ObservedPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"state_json\x18\x05 \x01(\fR\tstateJson\x12-\n" +
	"\x13observed_at_unix_ms\x18\x06 \x01(\x03R\x10observedAtUnixMs\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"\x85\x06\n" +
	"\x0eAgentToControl\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x04 \x01(\x03R\fsentAtUnixMs\x12,\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x14.anix.agent.v1.HelloH\x00R\x05hello\x128\n" +
	"\theartbeat\x18\v \x01(\v2\x18.anix.agent.v1.HeartbeatH\x00R\theartbeat\x12B\n" +
	"\roperation_ack\x18\f \x01(\v2\x1b.anix.agent.v1.OperationAckH\x00R\foperationAck\x12E\n" +
	"\x0eobserved_state\x18\r \x01(\v2\x1c.anix.agent.v1.ObservedStateH\x00R\robservedState\x12B\n" +
	"\rconfig_status\x18\x0e \x01(\v2\x1b.anix.agent.v1.ConfigStatusH\x00R\fconfigStatus\x128\n" +
	"\atraffic\x18\x0f \x01(\v2\x1c.anix.agent.v1.TrafficReportH\x00R\atraffic\x12-\n" +
	"\x04logs\x18\x10 \x01(\v2\x17.anix.agent.v1.LogBatchH\x00R\x04logs\x123\n" +
	"\x06status\x18\x11 \x01(\v2\x19.anix.agent.v1.NodeStatusH\x00R\x06status\x12E\n" +
	"\x0epackage_report\x18\x12 \x01(\v2\x1c.anix.agent.v1.PackageReportH\x00R\rpackageReport\x12Q\n" +
	"\x12maintenance_events\x18\x13 \x01(\v2 .anix.agent.v1.MaintenanceEventsH\x00R\x11maintenanceEventsB\t\n" +
	"\apayload\"\x8d\x05\n" +
	"\x0eControlToAgent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x04 \x01(\x03R\fsentAtUnixMs\x126\n" +
	"\thello_ack\x18\n" +
	" \x01(\v2\x17.anix.agent.v1.HelloAckH\x00R\bhelloAck\x12B\n" +
	"\rheartbeat_ack\x18\v \x01(\v2\x1b.anix.agent.v1.HeartbeatAckH\x00R\fheartbeatAck\x12N\n" +
	"\x11desired_operation\x18\f \x01(\v2\x1f.anix.agent.v1.DesiredOperationH\x00R\x10desiredOperation\x127\n" +
	"\x06config\x18\r \x01(\v2\x1d.anix.agent.v1.ConfigSnapshotH\x00R\x06config\x120\n" +
	"\x05users\x18\x0e \x01(\v2\x18.anix.agent.v1.UserDeltaH\x00R\x05users\x129\n" +
	"\n" +
	"report_ack\x18\x0f \x01(\v2\x18.anix.agent.v1.ReportAckH\x00R\treportAck\x12H\n" +
	"\x0fmaintenance_ack\x18\x10 \x01(\v2\x1d.anix.agent.v1.MaintenanceAckH\x00R\x0emaintenanceAck\x129\n" +
	"\n" +
	"alive_list\x18\x11 \x01(\v2\x18.anix.agent.v1.AliveListH\x00R\taliveListB\t\n" +
	"\apayload\"\x93\x01\n" +
	"\x0eConfigSnapshot\x12'\n" +
	"\x0fconfig_revision\x18\x01 \x01(\x04R\x0econfigRevision\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\fR\n" +
	"configJson\"\xa7\x01\n" +
	"\fConfigStatus\x12'\n" +
	"\x0fconfig_revision\x18\x01 \x01(\x04R\x0econfigRevision\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\x12\x18\n" +
	"\aapplied\x18\x03 \x01(\bR\aapplied\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\"\xa3\x01\n" +
	"\bNodeUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12(\n" +
	"\x10speed_limit_mbps\x18\x03 \x01(\x03R\x0espeedLimitMbps\x12!\n" +
	"\fdevice_limit\x18\x04 \x01(\x05R\vdeviceLimit\x12\x1d\n" +
	"\n" +
	"extra_json\x18\x05 \x01(\fR\textraJson\"\xb1\x01\n" +
	"\tUserDelta\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\x12\x12\n" +
	"\x04full\x18\x02 \x01(\bR\x04full\x12\x1b\n" +
	"\tlast_page\x18\x03 \x01(\bR\blastPage\x121\n" +
	"\aupserts\x18\x04 \x03(\v2\x17.anix.agent.v1.NodeUserR\aupserts\x12(\n" +
	"\x10removed_user_ids\x18\x05 \x03(\x04R\x0eremovedUserIds\"\xbc\x01\n" +
	"\rTrafficReport\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x120\n" +
	"\x05users\x18\x02 \x03(\v2\x1a.anix.agent.v1.UserTrafficR\x05users\x121\n" +
	"\x06online\x18\x03 \x03(\v2\x19.anix.agent.v1.OnlineUserR\x06online\x12+\n" +
	"\x12window_end_unix_ms\x18\x04 \x01(\x03R\x0fwindowEndUnixMs\"p\n" +
	"\vUserTraffic\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fupload_bytes\x18\x02 \x01(\x04R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\x03 \x01(\x04R\rdownloadBytes\"7\n" +
	"\n" +
	"OnlineUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\"X\n" +
	"\bLogBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x121\n" +
	"\aentries\x18\x02 \x03(\v2\x17.anix.agent.v1.LogEntryR\aentries\"\xb9\x01\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x11logged_at_unix_ms\x18\x04 \x01(\x03R\x0eloggedAtUnixMs\x12\x1f\n" +
	"\vfields_json\x18\x05 \x01(\fR\n" +
	"fieldsJson\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\"\x9b\x01\n" +
	"\tReportAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x18\n" +
	"\aapplied\x18\x02 \x01(\bR\aapplied\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12$\n" +
	"\x0eretry_after_ms\x18\x05 \x01(\rR\fretryAfterMs\"\xbc\x02\n" +
	"\n" +
	"NodeStatus\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x02 \x01(\x01R\x12memoryUsagePercent\x12,\n" +
	"\x12disk_usage_percent\x18\x03 \x01(\x01R\x10diskUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0fruntime_healthy\x18\x05 \x01(\bR\x0eruntimeHealthy\x12#\n" +
	"\rruntime_error\x18\x06 \x01(\tR\fruntimeError\x12-\n" +
	"\x13observed_at_unix_ms\x18\a \x01(\x03R\x10observedAtUnixMs\"\xac\x01\n" +
	"\rPackageReport\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\fR\vpayloadJson\x12-\n" +
	"\x13observed_at_unix_ms\x18\x05 \x01(\x03R\x10observedAtUnixMs\"N\n" +
	"\x11MaintenanceEvents\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vevents_json\x18\x02 \x03(\fR\n" +
	"eventsJson\"i\n" +
	"\x0eMaintenanceAck\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12=\n" +
	"\x06events\x18\x02 \x03(\v2%.anix.agent.v1.MaintenanceEventResultR\x06events\"\xac\x01\n" +
	"\x16MaintenanceEventResult\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\tpersisted\x18\x02 \x01(\bR\tpersisted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12$\n" +
	"\x0eretry_after_ms\x18\x05 \x01(\rR\fretryAfterMs\"\xa7\x01\n" +
	"\tAliveList\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x1b\n" +
	"\tlast_page\x18\x02 \x01(\bR\blastPage\x122\n" +
	"\aentries\x18\x03 \x03(\v2\x18.anix.agent.v1.UserAliveR\aentries\x12-\n" +
	"\x13computed_at_unix_ms\x18\x04 \x01(\x03R\x10computedAtUnixMs\"E\n" +
	"\tUserAlive\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\valive_count\x18\x02 \x01(\rR\n" +
	"aliveCount*\xc1\x01\n" +
	"\rObservedPhase\x12\x1e\n" +
	"\x1aOBSERVED_PHASE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OBSERVED_PHASE_ACCEPTED\x10\x01\x12\x1b\n" +
	"\x17OBSERVED_PHASE_APPLYING\x10\x02\x12\x1c\n" +
	"\x18OBSERVED_PHASE_SUCCEEDED\x10\x03\x12\x19\n" +
	"\x15OBSERVED_PHASE_FAILED\x10\x04\x12\x1d\n" +
	"\x19OBSERVED_PHASE_SUPERSEDED\x10\x052h\n" +
	"\x13AgentControlService\x12Q\n" +
	"\rControlStream\x12\x1d.anix.agent.v1.AgentToControl\x1a\x1d.anix.agent.v1.ControlToAgent(\x010\x01B<Z:github.com/AnixOps/anix-control/sdk/api/agent/v1;agentv1pbb\x06proto3"

var (
	file_api_grpc_agent_v1_agent_proto_rawDescOnce sync.Once
	file_api_grpc_agent_v1_agent_proto_rawDescData []byte
)

func file_api_grpc_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_api_grpc_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_grpc_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_agent_v1_agent_proto_rawDesc), len(file_api_grpc_agent_v1_agent_proto_rawDesc)))
	})
	return file_api_grpc_agent_v1_agent_proto_rawDescData
}

var file_api_grpc_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_grpc_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_grpc_agent_v1_agent_proto_goTypes = []any{
	(ObservedPhase)(0),             // 0: anix.agent.v1.ObservedPhase
	(*Capability)(nil),             // 1: anix.agent.v1.Capability
	(*Hello)(nil),                  // 2: anix.agent.v1.Hello
	(*HelloAck)(nil),               // 3: anix.agent.v1.HelloAck
	(*Heartbeat)(nil),              // 4: anix.agent.v1.Heartbeat
	(*PluginObservedState)(nil),    // 5: anix.agent.v1.PluginObservedState
	(*PluginRuleCounter)(nil),      // 6: anix.agent.v1.PluginRuleCounter
	(*HeartbeatAck)(nil),           // 7: anix.agent.v1.HeartbeatAck
	(*DesiredOperation)(nil),       // 8: anix.agent.v1.DesiredOperation
	(*OperationAck)(nil),           // 9: anix.agent.v1.OperationAck
	(*ObservedState)(nil),          // 10: anix.agent.v1.ObservedState
	(*AgentToControl)(nil),         // 11: anix.agent.v1.AgentToControl
	(*ControlToAgent)(nil),         // 12: anix.agent.v1.ControlToAgent
	(*ConfigSnapshot)(nil),         // 13: anix.agent.v1.ConfigSnapshot
	(*ConfigStatus)(nil),           // 14: anix.agent.v1.ConfigStatus
	(*NodeUser)(nil),               // 15: anix.agent.v1.NodeUser
	(*UserDelta)(nil),              // 16: anix.agent.v1.UserDelta
	(*TrafficReport)(nil),          // 17: anix.agent.v1.TrafficReport
	(*UserTraffic)(nil),            // 18: anix.agent.v1.UserTraffic
	(*OnlineUser)(nil),             // 19: anix.agent.v1.OnlineUser
	(*LogBatch)(nil),               // 20: anix.agent.v1.LogBatch
	(*LogEntry)(nil),               // 21: anix.agent.v1.LogEntry
	(*ReportAck)(nil),              // 22: anix.agent.v1.ReportAck
	(*NodeStatus)(nil),             // 23: anix.agent.v1.NodeStatus
	(*PackageReport)(nil),          // 24: anix.agent.v1.PackageReport
	(*MaintenanceEvents)(nil),      // 25: anix.agent.v1.MaintenanceEvents
	(*MaintenanceAck)(nil),         // 26: anix.agent.v1.MaintenanceAck
	(*MaintenanceEventResult)(nil), // 27: anix.agent.v1.MaintenanceEventResult
	(*AliveList)(nil),              // 28: anix.agent.v1.AliveList
	(*UserAlive)(nil),              // 29: anix.agent.v1.UserAlive
	nil,                            // 30: anix.agent.v1.Capability.AttributesEntry
	nil,                            // 31: anix.agent.v1.Hello.LabelsEntry
	nil,                            // 32: anix.agent.v1.Heartbeat.MetricsEntry
}
var file_api_grpc_agent_v1_agent_proto_depIdxs = []int32{
	30, // 0: anix.agent.v1.Capability.attributes:type_name -> anix.agent.v1.Capability.AttributesEntry
	1,  // 1: anix.agent.v1.Hello.capabilities:type_name -> anix.agent.v1.Capability
	31, // 2: anix.agent.v1.Hello.labels:type_name -> anix.agent.v1.Hello.LabelsEntry
	1,  // 3: anix.agent.v1.HelloAck.server_capabilities:type_name -> anix.agent.v1.Capability
	32, // 4: anix.agent.v1.Heartbeat.metrics:type_name -> anix.agent.v1.Heartbeat.MetricsEntry
	5,  // 5: anix.agent.v1.Heartbeat.plugin_observations:type_name -> anix.agent.v1.PluginObservedState
	6,  // 6: anix.agent.v1.PluginObservedState.rule_counters:type_name -> anix.agent.v1.PluginRuleCounter
	0,  // 7: anix.agent.v1.ObservedState.phase:type_name -> anix.agent.v1.ObservedPhase
	2,  // 8: anix.agent.v1.AgentToControl.hello:type_name -> anix.agent.v1.Hello
	4,  // 9: anix.agent.v1.AgentToControl.heartbeat:type_name -> anix.agent.v1.Heartbeat
	9,  // 10: anix.agent.v1.AgentToControl.operation_ack:type_name -> anix.agent.v1.OperationAck
	10, // 11: anix.agent.v1.AgentToControl.observed_state:type_name -> anix.agent.v1.ObservedState
	14, // 12: anix.agent.v1.AgentToControl.config_status:type_name -> anix.agent.v1.ConfigStatus
	17, // 13: anix.agent.v1.AgentToControl.traffic:type_name -> anix.agent.v1.TrafficReport
	20, // 14: anix.agent.v1.AgentToControl.logs:type_name -> anix.agent.v1.LogBatch
	23, // 15: anix.agent.v1.AgentToControl.status:type_name -> anix.agent.v1.NodeStatus
	24, // 16: anix.agent.v1.AgentToControl.package_report:type_name -> anix.agent.v1.PackageReport
	25, // 17: anix.agent.v1.AgentToControl.maintenance_events:type_name -> anix.agent.v1.MaintenanceEvents
	3,  // 18: anix.agent.v1.ControlToAgent.hello_ack:type_name -> anix.agent.v1.HelloAck
	7,  // 19: anix.agent.v1.ControlToAgent.heartbeat_ack:type_name -> anix.agent.v1.HeartbeatAck
	8,  // 20: anix.agent.v1.ControlToAgent.desired_operation:type_name -> anix.agent.v1.DesiredOperation
	13, // 21: anix.agent.v1.ControlToAgent.config:type_name -> anix.agent.v1.ConfigSnapshot
	16, // 22: anix.agent.v1.ControlToAgent.users:type_name -> anix.agent.v1.UserDelta
	22, // 23: anix.agent.v1.ControlToAgent.report_ack:type_name -> anix.agent.v1.ReportAck
	26, // 24: anix.agent.v1.ControlToAgent.maintenance_ack:type_name -> anix.agent.v1.MaintenanceAck
	28, // 25: anix.agent.v1.ControlToAgent.alive_list:type_name -> anix.agent.v1.AliveList
	15, // 26: anix.agent.v1.UserDelta.upserts:type_name -> anix.agent.v1.NodeUser
	18, // 27: anix.agent.v1.TrafficReport.users:type_name -> anix.agent.v1.UserTraffic
	19, // 28: anix.agent.v1.TrafficReport.online:type_name -> anix.agent.v1.OnlineUser
	21, // 29: anix.agent.v1.LogBatch.entries:type_name -> anix.agent.v1.LogEntry
	27, // 30: anix.agent.v1.MaintenanceAck.events:type_name -> anix.agent.v1.MaintenanceEventResult
	29, // 31: anix.agent.v1.AliveList.entries:type_name -> anix.agent.v1.UserAlive
	11, // 32: anix.agent.v1.AgentControlService.ControlStream:input_type -> anix.agent.v1.AgentToControl
	12, // 33: anix.agent.v1.AgentControlService.ControlStream:output_type -> anix.agent.v1.ControlToAgent
	33, // [33:34] is the sub-list for method output_type
	32, // [32:33] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_api_grpc_agent_v1_agent_proto_init() }
func file_api_grpc_agent_v1_agent_proto_init() {
	if File_api_grpc_agent_v1_agent_proto != nil {
		return
	}
	file_api_grpc_agent_v1_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*AgentToControl_Hello)(nil),
		(*AgentToControl_Heartbeat)(nil),
		(*AgentToControl_OperationAck)(nil),
		(*AgentToControl_ObservedState)(nil),
		(*AgentToControl_ConfigStatus)(nil),
		(*AgentToControl_Traffic)(nil),
		(*AgentToControl_Logs)(nil),
		(*AgentToControl_Status)(nil),
		(*AgentToControl_PackageReport)(nil),
		(*AgentToControl_MaintenanceEvents)(nil),
	}
	file_api_grpc_agent_v1_agent_proto_msgTypes[11].OneofWrappers = []any{
		(*ControlToAgent_HelloAck)(nil),
		(*ControlToAgent_HeartbeatAck)(nil),
		(*ControlToAgent_DesiredOperation)(nil),
		(*ControlToAgent_Config)(nil),
		(*ControlToAgent_Users)(nil),
		(*ControlToAgent_ReportAck)(nil),
		(*ControlToAgent_MaintenanceAck)(nil),
		(*ControlToAgent_AliveList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_agent_v1_agent_proto_rawDesc), len(file_api_grpc_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_grpc_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_api_grpc_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_api_grpc_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_api_grpc_agent_v1_agent_proto = out.File
	file_api_grpc_agent_v1_agent_proto_goTypes = nil
	file_api_grpc_agent_v1_agent_proto_depIdxs = nil
}
