// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: api/grpc/agent/v1/agent_enrollment.proto

package agentv1pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentEnrollment_Enroll_FullMethodName               = "/anix.agent.v1.AgentEnrollment/Enroll"
	AgentEnrollment_Renew_FullMethodName                = "/anix.agent.v1.AgentEnrollment/Renew"
	AgentEnrollment_GetTrustBundle_FullMethodName       = "/anix.agent.v1.AgentEnrollment/GetTrustBundle"
	AgentEnrollment_IssueLinkCertificate_FullMethodName = "/anix.agent.v1.AgentEnrollment/IssueLinkCertificate"
	AgentEnrollment_GetLinkTrustBundle_FullMethodName   = "/anix.agent.v1.AgentEnrollment/GetLinkTrustBundle"
)

// AgentEnrollmentClient is the client API for AgentEnrollment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentEnrollment issues the mTLS client certificates of AnixOps Agents. It is
// served on Control's node-facing agent listener, next to
// AgentControlService. It lives in its own file so the descriptor of
// agent.proto, which Agents in the field run, stays unchanged.
//
// A certificate carries exactly one URI SAN naming the node:
//
//	spiffe://anixops/<cluster>/agent/proxy-<id>     a proxy node (v2_node)
//	spiffe://anixops/<cluster>/agent/forward-<id>   a forward node (v2_forward_node)
//
// Control ignores the subject and SANs of the CSR and issues the identity of
// the node the bootstrap credential authenticated.
type AgentEnrollmentClient interface {
	// Enroll exchanges a bootstrap credential and a CSR for the node's first
	// certificate. The credential is one of:
	//   - the node credential an agent already has, as metadata: x-node-id and
	//     x-api-key (a proxy node's API key), with x-node-kind "forward" for a
	//     forward node's token;
	//   - enrollment_credential, a one-time anixagt_ credential bound to a node.
	Enroll(ctx context.Context, in *EnrollAgentRequest, opts ...grpc.CallOption) (*EnrollAgentResponse, error)
	// Renew issues a new certificate to the holder of a valid one, presented as
	// the TLS client certificate.
	Renew(ctx context.Context, in *RenewAgentCertificateRequest, opts ...grpc.CallOption) (*RenewAgentCertificateResponse, error)
	// GetTrustBundle returns the CA certificates that sign agent certificates.
	// It requires a valid agent client certificate.
	GetTrustBundle(ctx context.Context, in *GetAgentTrustBundleRequest, opts ...grpc.CallOption) (*GetAgentTrustBundleResponse, error)
	// IssueLinkCertificate issues the node of the presented agent client
	// certificate a forward link certificate (owner decision H28): the
	// certificate a forward engine such as gost presents to the node's peers
	// on encrypted links, signed by the forward link CA, a root separate from
	// the CA of agent certificates. It requires a valid agent client
	// certificate (never the node credential) of a node whose Agent negotiated
	// forward.v1 in its last Hello. The CSR's key must be a key of its own,
	// never the agent certificate's; the CSR may name only the node's DNS
	// name ("forward-7") and SPIFFE ID. Renewal is the same call with a new
	// key, at renew_after_unix. See PROTOCOL.md "Forward link certificates".
	IssueLinkCertificate(ctx context.Context, in *IssueLinkCertificateRequest, opts ...grpc.CallOption) (*IssueLinkCertificateResponse, error)
	// GetLinkTrustBundle returns the forward link CAs a node trusts to verify
	// its peers' link certificates. It requires a valid agent client
	// certificate.
	GetLinkTrustBundle(ctx context.Context, in *GetLinkTrustBundleRequest, opts ...grpc.CallOption) (*GetLinkTrustBundleResponse, error)
}

type agentEnrollmentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentEnrollmentClient(cc grpc.ClientConnInterface) AgentEnrollmentClient {
	return &agentEnrollmentClient{cc}
}

func (c *agentEnrollmentClient) Enroll(ctx context.Context, in *EnrollAgentRequest, opts ...grpc.CallOption) (*EnrollAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollAgentResponse)
	err := c.cc.Invoke(ctx, AgentEnrollment_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentEnrollmentClient) Renew(ctx context.Context, in *RenewAgentCertificateRequest, opts ...grpc.CallOption) (*RenewAgentCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewAgentCertificateResponse)
	err := c.cc.Invoke(ctx, AgentEnrollment_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentEnrollmentClient) GetTrustBundle(ctx context.Context, in *GetAgentTrustBundleRequest, opts ...grpc.CallOption) (*GetAgentTrustBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentTrustBundleResponse)
	err := c.cc.Invoke(ctx, AgentEnrollment_GetTrustBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentEnrollmentClient) IssueLinkCertificate(ctx context.Context, in *IssueLinkCertificateRequest, opts ...grpc.CallOption) (*IssueLinkCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueLinkCertificateResponse)
	err := c.cc.Invoke(ctx, AgentEnrollment_IssueLinkCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentEnrollmentClient) GetLinkTrustBundle(ctx context.Context, in *GetLinkTrustBundleRequest, opts ...grpc.CallOption) (*GetLinkTrustBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLinkTrustBundleResponse)
	err := c.cc.Invoke(ctx, AgentEnrollment_GetLinkTrustBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentEnrollmentServer is the server API for AgentEnrollment service.
// All implementations must embed UnimplementedAgentEnrollmentServer
// for forward compatibility.
//
// AgentEnrollment issues the mTLS client certificates of AnixOps Agents. It is
// served on Control's node-facing agent listener, next to
// AgentControlService. It lives in its own file so the descriptor of
// agent.proto, which Agents in the field run, stays unchanged.
//
// A certificate carries exactly one URI SAN naming the node:
//
//	spiffe://anixops/<cluster>/agent/proxy-<id>     a proxy node (v2_node)
//	spiffe://anixops/<cluster>/agent/forward-<id>   a forward node (v2_forward_node)
//
// Control ignores the subject and SANs of the CSR and issues the identity of
// the node the bootstrap credential authenticated.
type AgentEnrollmentServer interface {
	// Enroll exchanges a bootstrap credential and a CSR for the node's first
	// certificate. The credential is one of:
	//   - the node credential an agent already has, as metadata: x-node-id and
	//     x-api-key (a proxy node's API key), with x-node-kind "forward" for a
	//     forward node's token;
	//   - enrollment_credential, a one-time anixagt_ credential bound to a node.
	Enroll(context.Context, *EnrollAgentRequest) (*EnrollAgentResponse, error)
	// Renew issues a new certificate to the holder of a valid one, presented as
	// the TLS client certificate.
	Renew(context.Context, *RenewAgentCertificateRequest) (*RenewAgentCertificateResponse, error)
	// GetTrustBundle returns the CA certificates that sign agent certificates.
	// It requires a valid agent client certificate.
	GetTrustBundle(context.Context, *GetAgentTrustBundleRequest) (*GetAgentTrustBundleResponse, error)
	// IssueLinkCertificate issues the node of the presented agent client
	// certificate a forward link certificate (owner decision H28): the
	// certificate a forward engine such as gost presents to the node's peers
	// on encrypted links, signed by the forward link CA, a root separate from
	// the CA of agent certificates. It requires a valid agent client
	// certificate (never the node credential) of a node whose Agent negotiated
	// forward.v1 in its last Hello. The CSR's key must be a key of its own,
	// never the agent certificate's; the CSR may name only the node's DNS
	// name ("forward-7") and SPIFFE ID. Renewal is the same call with a new
	// key, at renew_after_unix. See PROTOCOL.md "Forward link certificates".
	IssueLinkCertificate(context.Context, *IssueLinkCertificateRequest) (*IssueLinkCertificateResponse, error)
	// GetLinkTrustBundle returns the forward link CAs a node trusts to verify
	// its peers' link certificates. It requires a valid agent client
	// certificate.
	GetLinkTrustBundle(context.Context, *GetLinkTrustBundleRequest) (*GetLinkTrustBundleResponse, error)
	mustEmbedUnimplementedAgentEnrollmentServer()
}

// UnimplementedAgentEnrollmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentEnrollmentServer struct{}

func (UnimplementedAgentEnrollmentServer) Enroll(context.Context, *EnrollAgentRequest) (*EnrollAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedAgentEnrollmentServer) Renew(context.Context, *RenewAgentCertificateRequest) (*RenewAgentCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedAgentEnrollmentServer) GetTrustBundle(context.Context, *GetAgentTrustBundleRequest) (*GetAgentTrustBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrustBundle not implemented")
}
func (UnimplementedAgentEnrollmentServer) IssueLinkCertificate(context.Context, *IssueLinkCertificateRequest) (*IssueLinkCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueLinkCertificate not implemented")
}
func (UnimplementedAgentEnrollmentServer) GetLinkTrustBundle(context.Context, *GetLinkTrustBundleRequest) (*GetLinkTrustBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinkTrustBundle not implemented")
}
func (UnimplementedAgentEnrollmentServer) mustEmbedUnimplementedAgentEnrollmentServer() {}
func (UnimplementedAgentEnrollmentServer) testEmbeddedByValue()                         {}

// UnsafeAgentEnrollmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentEnrollmentServer will
// result in compilation errors.
type UnsafeAgentEnrollmentServer interface {
	mustEmbedUnimplementedAgentEnrollmentServer()
}

func RegisterAgentEnrollmentServer(s grpc.ServiceRegistrar, srv AgentEnrollmentServer) {
	// If the following call panics, it indicates UnimplementedAgentEnrollmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentEnrollment_ServiceDesc, srv)
}

func _AgentEnrollment_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEnrollmentServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEnrollment_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEnrollmentServer).Enroll(ctx, req.(*EnrollAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentEnrollment_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewAgentCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEnrollmentServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEnrollment_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEnrollmentServer).Renew(ctx, req.(*RenewAgentCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentEnrollment_GetTrustBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentTrustBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEnrollmentServer).GetTrustBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEnrollment_GetTrustBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEnrollmentServer).GetTrustBundle(ctx, req.(*GetAgentTrustBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentEnrollment_IssueLinkCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueLinkCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEnrollmentServer).IssueLinkCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEnrollment_IssueLinkCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEnrollmentServer).IssueLinkCertificate(ctx, req.(*IssueLinkCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentEnrollment_GetLinkTrustBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkTrustBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEnrollmentServer).GetLinkTrustBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEnrollment_GetLinkTrustBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEnrollmentServer).GetLinkTrustBundle(ctx, req.(*GetLinkTrustBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentEnrollment_ServiceDesc is the grpc.ServiceDesc for AgentEnrollment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentEnrollment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anix.agent.v1.AgentEnrollment",
	HandlerType: (*AgentEnrollmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _AgentEnrollment_Enroll_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _AgentEnrollment_Renew_Handler,
		},
		{
			MethodName: "GetTrustBundle",
			Handler:    _AgentEnrollment_GetTrustBundle_Handler,
		},
		{
			MethodName: "IssueLinkCertificate",
			Handler:    _AgentEnrollment_IssueLinkCertificate_Handler,
		},
		{
			MethodName: "GetLinkTrustBundle",
			Handler:    _AgentEnrollment_GetLinkTrustBundle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/agent/v1/agent_enrollment.proto",
}
