// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: api/grpc/agent/v1/agent.proto

package agentv1pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControlService_ControlStream_FullMethodName = "/anix.agent.v1.AgentControlService/ControlStream"
)

// AgentControlServiceClient is the client API for AgentControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlServiceClient interface {
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToControl, ControlToAgent], error)
}

type agentControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlServiceClient(cc grpc.ClientConnInterface) AgentControlServiceClient {
	return &agentControlServiceClient{cc}
}

func (c *agentControlServiceClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToControl, ControlToAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlService_ServiceDesc.Streams[0], AgentControlService_ControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentToControl, ControlToAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_ControlStreamClient = grpc.BidiStreamingClient[AgentToControl, ControlToAgent]

// AgentControlServiceServer is the server API for AgentControlService service.
// All implementations must embed UnimplementedAgentControlServiceServer
// for forward compatibility.
type AgentControlServiceServer interface {
	ControlStream(grpc.BidiStreamingServer[AgentToControl, ControlToAgent]) error
	mustEmbedUnimplementedAgentControlServiceServer()
}

// UnimplementedAgentControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServiceServer struct{}

func (UnimplementedAgentControlServiceServer) ControlStream(grpc.BidiStreamingServer[AgentToControl, ControlToAgent]) error {
	return status.Error(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedAgentControlServiceServer) mustEmbedUnimplementedAgentControlServiceServer() {}
func (UnimplementedAgentControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServiceServer will
// result in compilation errors.
type UnsafeAgentControlServiceServer interface {
	mustEmbedUnimplementedAgentControlServiceServer()
}

func RegisterAgentControlServiceServer(s grpc.ServiceRegistrar, srv AgentControlServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControlService_ServiceDesc, srv)
}

func _AgentControlService_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServiceServer).ControlStream(&grpc.GenericServerStream[AgentToControl, ControlToAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_ControlStreamServer = grpc.BidiStreamingServer[AgentToControl, ControlToAgent]

// AgentControlService_ServiceDesc is the grpc.ServiceDesc for AgentControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anix.agent.v1.AgentControlService",
	HandlerType: (*AgentControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlStream",
			Handler:       _AgentControlService_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/agent/v1/agent.proto",
}
