// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: api/identity/v1/identity.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_GetTokenKeys_FullMethodName     = "/anixops.identity.v1.IdentityService/GetTokenKeys"
	IdentityService_BatchGetAccounts_FullMethodName = "/anixops.identity.v1.IdentityService/BatchGetAccounts"
	IdentityService_ImportAccounts_FullMethodName   = "/anixops.identity.v1.IdentityService/ImportAccounts"
	IdentityService_ExportAccounts_FullMethodName   = "/anixops.identity.v1.IdentityService/ExportAccounts"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService is served by the identity module. The kernel is its only
// caller: it authenticates with the kernel's mTLS identity.
type IdentityServiceClient interface {
	// GetTokenKeys publishes the public keys that verify access tokens.
	GetTokenKeys(ctx context.Context, in *GetTokenKeysRequest, opts ...grpc.CallOption) (*GetTokenKeysResponse, error)
	BatchGetAccounts(ctx context.Context, in *BatchGetAccountsRequest, opts ...grpc.CallOption) (*BatchGetAccountsResponse, error)
	// ImportAccounts receives accounts from the kernel's legacy tables. The
	// first message is the header; the stream is resumable by checkpoint.
	ImportAccounts(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportAccountsRequest, ImportAccountsResponse], error)
	// ExportAccounts streams accounts changed after a version, for kernel
	// reconciliation of its read projection.
	ExportAccounts(ctx context.Context, in *ExportAccountsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Account], error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) GetTokenKeys(ctx context.Context, in *GetTokenKeysRequest, opts ...grpc.CallOption) (*GetTokenKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenKeysResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetTokenKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) BatchGetAccounts(ctx context.Context, in *BatchGetAccountsRequest, opts ...grpc.CallOption) (*BatchGetAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetAccountsResponse)
	err := c.cc.Invoke(ctx, IdentityService_BatchGetAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ImportAccounts(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportAccountsRequest, ImportAccountsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IdentityService_ServiceDesc.Streams[0], IdentityService_ImportAccounts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportAccountsRequest, ImportAccountsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IdentityService_ImportAccountsClient = grpc.ClientStreamingClient[ImportAccountsRequest, ImportAccountsResponse]

func (c *identityServiceClient) ExportAccounts(ctx context.Context, in *ExportAccountsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Account], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IdentityService_ServiceDesc.Streams[1], IdentityService_ExportAccounts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportAccountsRequest, Account]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IdentityService_ExportAccountsClient = grpc.ServerStreamingClient[Account]

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService is served by the identity module. The kernel is its only
// caller: it authenticates with the kernel's mTLS identity.
type IdentityServiceServer interface {
	// GetTokenKeys publishes the public keys that verify access tokens.
	GetTokenKeys(context.Context, *GetTokenKeysRequest) (*GetTokenKeysResponse, error)
	BatchGetAccounts(context.Context, *BatchGetAccountsRequest) (*BatchGetAccountsResponse, error)
	// ImportAccounts receives accounts from the kernel's legacy tables. The
	// first message is the header; the stream is resumable by checkpoint.
	ImportAccounts(grpc.ClientStreamingServer[ImportAccountsRequest, ImportAccountsResponse]) error
	// ExportAccounts streams accounts changed after a version, for kernel
	// reconciliation of its read projection.
	ExportAccounts(*ExportAccountsRequest, grpc.ServerStreamingServer[Account]) error
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) GetTokenKeys(context.Context, *GetTokenKeysRequest) (*GetTokenKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenKeys not implemented")
}
func (UnimplementedIdentityServiceServer) BatchGetAccounts(context.Context, *BatchGetAccountsRequest) (*BatchGetAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetAccounts not implemented")
}
func (UnimplementedIdentityServiceServer) ImportAccounts(grpc.ClientStreamingServer[ImportAccountsRequest, ImportAccountsResponse]) error {
	return status.Error(codes.Unimplemented, "method ImportAccounts not implemented")
}
func (UnimplementedIdentityServiceServer) ExportAccounts(*ExportAccountsRequest, grpc.ServerStreamingServer[Account]) error {
	return status.Error(codes.Unimplemented, "method ExportAccounts not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_GetTokenKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetTokenKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetTokenKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetTokenKeys(ctx, req.(*GetTokenKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_BatchGetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).BatchGetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_BatchGetAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).BatchGetAccounts(ctx, req.(*BatchGetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ImportAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentityServiceServer).ImportAccounts(&grpc.GenericServerStream[ImportAccountsRequest, ImportAccountsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IdentityService_ImportAccountsServer = grpc.ClientStreamingServer[ImportAccountsRequest, ImportAccountsResponse]

func _IdentityService_ExportAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportAccountsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IdentityServiceServer).ExportAccounts(m, &grpc.GenericServerStream[ExportAccountsRequest, Account]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IdentityService_ExportAccountsServer = grpc.ServerStreamingServer[Account]

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anixops.identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTokenKeys",
			Handler:    _IdentityService_GetTokenKeys_Handler,
		},
		{
			MethodName: "BatchGetAccounts",
			Handler:    _IdentityService_BatchGetAccounts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImportAccounts",
			Handler:       _IdentityService_ImportAccounts_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ExportAccounts",
			Handler:       _IdentityService_ExportAccounts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/identity/v1/identity.proto",
}
