// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: api/identity/v1/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenKeyState int32

const (
	TokenKeyState_TOKEN_KEY_STATE_UNSPECIFIED TokenKeyState = 0
	// NEXT keys are published before they sign.
	TokenKeyState_TOKEN_KEY_STATE_NEXT   TokenKeyState = 1
	TokenKeyState_TOKEN_KEY_STATE_ACTIVE TokenKeyState = 2
	// RETIRED keys no longer sign but still verify until not_after.
	TokenKeyState_TOKEN_KEY_STATE_RETIRED TokenKeyState = 3
	// REVOKED keys must not verify anything.
	TokenKeyState_TOKEN_KEY_STATE_REVOKED TokenKeyState = 4
)

// Enum value maps for TokenKeyState.
var (
	TokenKeyState_name = map[int32]string{
		0: "TOKEN_KEY_STATE_UNSPECIFIED",
		1: "TOKEN_KEY_STATE_NEXT",
		2: "TOKEN_KEY_STATE_ACTIVE",
		3: "TOKEN_KEY_STATE_RETIRED",
		4: "TOKEN_KEY_STATE_REVOKED",
	}
	TokenKeyState_value = map[string]int32{
		"TOKEN_KEY_STATE_UNSPECIFIED": 0,
		"TOKEN_KEY_STATE_NEXT":        1,
		"TOKEN_KEY_STATE_ACTIVE":      2,
		"TOKEN_KEY_STATE_RETIRED":     3,
		"TOKEN_KEY_STATE_REVOKED":     4,
	}
)

func (x TokenKeyState) Enum() *TokenKeyState {
	p := new(TokenKeyState)
	*p = x
	return p
}

func (x TokenKeyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenKeyState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_identity_v1_identity_proto_enumTypes[0].Descriptor()
}

func (TokenKeyState) Type() protoreflect.EnumType {
	return &file_api_identity_v1_identity_proto_enumTypes[0]
}

func (x TokenKeyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenKeyState.Descriptor instead.
func (TokenKeyState) EnumDescriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

type TokenKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kid   string                 `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// alg is always "EdDSA" (Ed25519).
	Alg           string        `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"`
	PublicKey     []byte        `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	State         TokenKeyState `protobuf:"varint,4,opt,name=state,proto3,enum=anixops.identity.v1.TokenKeyState" json:"state,omitempty"`
	NotBeforeUnix int64         `protobuf:"varint,5,opt,name=not_before_unix,json=notBeforeUnix,proto3" json:"not_before_unix,omitempty"`
	NotAfterUnix  int64         `protobuf:"varint,6,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenKey) Reset() {
	*x = TokenKey{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenKey) ProtoMessage() {}

func (x *TokenKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenKey.ProtoReflect.Descriptor instead.
func (*TokenKey) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *TokenKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *TokenKey) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *TokenKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *TokenKey) GetState() TokenKeyState {
	if x != nil {
		return x.State
	}
	return TokenKeyState_TOKEN_KEY_STATE_UNSPECIFIED
}

func (x *TokenKey) GetNotBeforeUnix() int64 {
	if x != nil {
		return x.NotBeforeUnix
	}
	return 0
}

func (x *TokenKey) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

type GetTokenKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenKeysRequest) Reset() {
	*x = GetTokenKeysRequest{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenKeysRequest) ProtoMessage() {}

func (x *GetTokenKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenKeysRequest.ProtoReflect.Descriptor instead.
func (*GetTokenKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

type GetTokenKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Keys  []*TokenKey            `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// issuer and audience are the iss and aud claims every token carries.
	Issuer        string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience      string `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenKeysResponse) Reset() {
	*x = GetTokenKeysResponse{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenKeysResponse) ProtoMessage() {}

func (x *GetTokenKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenKeysResponse.ProtoReflect.Descriptor instead.
func (*GetTokenKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenKeysResponse) GetKeys() []*TokenKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetTokenKeysResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *GetTokenKeysResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

type Account struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountUuid string                 `protobuf:"bytes,2,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Email       string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsAdmin     bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsStaff     bool                   `protobuf:"varint,5,opt,name=is_staff,json=isStaff,proto3" json:"is_staff,omitempty"`
	Banned      bool                   `protobuf:"varint,6,opt,name=banned,proto3" json:"banned,omitempty"`
	// token_version increases whenever existing tokens must stop working.
	TokenVersion uint64 `protobuf:"varint,7,opt,name=token_version,json=tokenVersion,proto3" json:"token_version,omitempty"`
	// version increases on every change; the kernel projection is monotonic
	// in it.
	Version       uint64 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAtUnix int64  `protobuf:"varint,9,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64  `protobuf:"varint,10,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	MfaEnabled    bool   `protobuf:"varint,11,opt,name=mfa_enabled,json=mfaEnabled,proto3" json:"mfa_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Account) GetAccountUuid() string {
	if x != nil {
		return x.AccountUuid
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *Account) GetIsStaff() bool {
	if x != nil {
		return x.IsStaff
	}
	return false
}

func (x *Account) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *Account) GetTokenVersion() uint64 {
	if x != nil {
		return x.TokenVersion
	}
	return 0
}

func (x *Account) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Account) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Account) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *Account) GetMfaEnabled() bool {
	if x != nil {
		return x.MfaEnabled
	}
	return false
}

type BatchGetAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetAccountsRequest) Reset() {
	*x = BatchGetAccountsRequest{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetAccountsRequest) ProtoMessage() {}

func (x *BatchGetAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetAccountsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetAccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetAccountsRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type BatchGetAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetAccountsResponse) Reset() {
	*x = BatchGetAccountsResponse{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetAccountsResponse) ProtoMessage() {}

func (x *BatchGetAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetAccountsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetAccountsResponse) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type ImportAccountsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ImportAccountsRequest_Header
	//	*ImportAccountsRequest_Account
	//	*ImportAccountsRequest_InviteCode
	//	*ImportAccountsRequest_DeletedUserId
	Value         isImportAccountsRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportAccountsRequest) Reset() {
	*x = ImportAccountsRequest{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportAccountsRequest) ProtoMessage() {}

func (x *ImportAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportAccountsRequest.ProtoReflect.Descriptor instead.
func (*ImportAccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *ImportAccountsRequest) GetValue() isImportAccountsRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ImportAccountsRequest) GetHeader() *ImportHeader {
	if x != nil {
		if x, ok := x.Value.(*ImportAccountsRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ImportAccountsRequest) GetAccount() *ImportedAccount {
	if x != nil {
		if x, ok := x.Value.(*ImportAccountsRequest_Account); ok {
			return x.Account
		}
	}
	return nil
}

func (x *ImportAccountsRequest) GetInviteCode() *ImportedInviteCode {
	if x != nil {
		if x, ok := x.Value.(*ImportAccountsRequest_InviteCode); ok {
			return x.InviteCode
		}
	}
	return nil
}

func (x *ImportAccountsRequest) GetDeletedUserId() uint64 {
	if x != nil {
		if x, ok := x.Value.(*ImportAccountsRequest_DeletedUserId); ok {
			return x.DeletedUserId
		}
	}
	return 0
}

type isImportAccountsRequest_Value interface {
	isImportAccountsRequest_Value()
}

type ImportAccountsRequest_Header struct {
	Header *ImportHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ImportAccountsRequest_Account struct {
	Account *ImportedAccount `protobuf:"bytes,2,opt,name=account,proto3,oneof"`
}

type ImportAccountsRequest_InviteCode struct {
	InviteCode *ImportedInviteCode `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3,oneof"`
}

type ImportAccountsRequest_DeletedUserId struct {
	// deleted_user_id names an account whose subscriber the product deleted
	// since the previous import; identity deletes it too.
	DeletedUserId uint64 `protobuf:"varint,4,opt,name=deleted_user_id,json=deletedUserId,proto3,oneof"`
}

func (*ImportAccountsRequest_Header) isImportAccountsRequest_Value() {}

func (*ImportAccountsRequest_Account) isImportAccountsRequest_Value() {}

func (*ImportAccountsRequest_InviteCode) isImportAccountsRequest_Value() {}

func (*ImportAccountsRequest_DeletedUserId) isImportAccountsRequest_Value() {}

type ImportHeader struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ImportId string                 `protobuf:"bytes,1,opt,name=import_id,json=importId,proto3" json:"import_id,omitempty"`
	// delta imports only carry accounts updated after the previous import.
	Delta         bool   `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Checkpoint    string `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportHeader) Reset() {
	*x = ImportHeader{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHeader) ProtoMessage() {}

func (x *ImportHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHeader.ProtoReflect.Descriptor instead.
func (*ImportHeader) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *ImportHeader) GetImportId() string {
	if x != nil {
		return x.ImportId
	}
	return ""
}

func (x *ImportHeader) GetDelta() bool {
	if x != nil {
		return x.Delta
	}
	return false
}

func (x *ImportHeader) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

type ImportedAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	PasswordAlgo  string                 `protobuf:"bytes,3,opt,name=password_algo,json=passwordAlgo,proto3" json:"password_algo,omitempty"`
	PasswordSalt  string                 `protobuf:"bytes,4,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	Mfa           *ImportedMFA           `protobuf:"bytes,5,opt,name=mfa,proto3" json:"mfa,omitempty"`
	InviteUserId  uint64                 `protobuf:"varint,6,opt,name=invite_user_id,json=inviteUserId,proto3" json:"invite_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedAccount) Reset() {
	*x = ImportedAccount{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedAccount) ProtoMessage() {}

func (x *ImportedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedAccount.ProtoReflect.Descriptor instead.
func (*ImportedAccount) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *ImportedAccount) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ImportedAccount) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *ImportedAccount) GetPasswordAlgo() string {
	if x != nil {
		return x.PasswordAlgo
	}
	return ""
}

func (x *ImportedAccount) GetPasswordSalt() string {
	if x != nil {
		return x.PasswordSalt
	}
	return ""
}

func (x *ImportedAccount) GetMfa() *ImportedMFA {
	if x != nil {
		return x.Mfa
	}
	return nil
}

func (x *ImportedAccount) GetInviteUserId() uint64 {
	if x != nil {
		return x.InviteUserId
	}
	return 0
}

type ImportedMFA struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TotpSecret       string                 `protobuf:"bytes,2,opt,name=totp_secret,json=totpSecret,proto3" json:"totp_secret,omitempty"`
	BackupCodeHashes []string               `protobuf:"bytes,3,rep,name=backup_code_hashes,json=backupCodeHashes,proto3" json:"backup_code_hashes,omitempty"`
	EnabledAtUnix    int64                  `protobuf:"varint,4,opt,name=enabled_at_unix,json=enabledAtUnix,proto3" json:"enabled_at_unix,omitempty"`
	// last_used_unix and last_method describe the last successful check.
	LastUsedUnix  int64  `protobuf:"varint,5,opt,name=last_used_unix,json=lastUsedUnix,proto3" json:"last_used_unix,omitempty"`
	LastMethod    string `protobuf:"bytes,6,opt,name=last_method,json=lastMethod,proto3" json:"last_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedMFA) Reset() {
	*x = ImportedMFA{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedMFA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedMFA) ProtoMessage() {}

func (x *ImportedMFA) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedMFA.ProtoReflect.Descriptor instead.
func (*ImportedMFA) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *ImportedMFA) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ImportedMFA) GetTotpSecret() string {
	if x != nil {
		return x.TotpSecret
	}
	return ""
}

func (x *ImportedMFA) GetBackupCodeHashes() []string {
	if x != nil {
		return x.BackupCodeHashes
	}
	return nil
}

func (x *ImportedMFA) GetEnabledAtUnix() int64 {
	if x != nil {
		return x.EnabledAtUnix
	}
	return 0
}

func (x *ImportedMFA) GetLastUsedUnix() int64 {
	if x != nil {
		return x.LastUsedUnix
	}
	return 0
}

func (x *ImportedMFA) GetLastMethod() string {
	if x != nil {
		return x.LastMethod
	}
	return ""
}

type ImportedInviteCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Used          bool                   `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,4,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedInviteCode) Reset() {
	*x = ImportedInviteCode{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedInviteCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedInviteCode) ProtoMessage() {}

func (x *ImportedInviteCode) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedInviteCode.ProtoReflect.Descriptor instead.
func (*ImportedInviteCode) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *ImportedInviteCode) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ImportedInviteCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ImportedInviteCode) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *ImportedInviteCode) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type ImportAccountsResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Accounts    uint64                 `protobuf:"varint,1,opt,name=accounts,proto3" json:"accounts,omitempty"`
	InviteCodes uint64                 `protobuf:"varint,2,opt,name=invite_codes,json=inviteCodes,proto3" json:"invite_codes,omitempty"`
	Checkpoint  string                 `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	// deleted counts the deleted_user_id messages applied.
	Deleted       uint64 `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportAccountsResponse) Reset() {
	*x = ImportAccountsResponse{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportAccountsResponse) ProtoMessage() {}

func (x *ImportAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportAccountsResponse.ProtoReflect.Descriptor instead.
func (*ImportAccountsResponse) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *ImportAccountsResponse) GetAccounts() uint64 {
	if x != nil {
		return x.Accounts
	}
	return 0
}

func (x *ImportAccountsResponse) GetInviteCodes() uint64 {
	if x != nil {
		return x.InviteCodes
	}
	return 0
}

func (x *ImportAccountsResponse) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

func (x *ImportAccountsResponse) GetDeleted() uint64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type ExportAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterVersion  uint64                 `protobuf:"varint,1,opt,name=after_version,json=afterVersion,proto3" json:"after_version,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAccountsRequest) Reset() {
	*x = ExportAccountsRequest{}
	mi := &file_api_identity_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAccountsRequest) ProtoMessage() {}

func (x *ExportAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_identity_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAccountsRequest.ProtoReflect.Descriptor instead.
func (*ExportAccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_identity_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *ExportAccountsRequest) GetAfterVersion() uint64 {
	if x != nil {
		return x.AfterVersion
	}
	return 0
}

func (x *ExportAccountsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_api_identity_v1_identity_proto protoreflect.FileDescriptor

const file_api_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/identity/v1/identity.proto\x12\x13anixops.identity.v1\"\xd5\x01\n" +
	"\bTokenKey\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\x12\x10\n" +
	"\x03alg\x18\x02 \x01(\tR\x03alg\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x128\n" +
	"\x05state\x18\x04 \x01(\x0e2\".anixops.identity.v1.TokenKeyStateR\x05state\x12&\n" +
	"\x0fnot_before_unix\x18\x05 \x01(\x03R\rnotBeforeUnix\x12$\n" +
	"\x0enot_after_unix\x18\x06 \x01(\x03R\fnotAfterUnix\"\x15\n" +
	"\x13GetTokenKeysRequest\"}\n" +
	"\x14GetTokenKeysResponse\x121\n" +
	"\x04keys\x18\x01 \x03(\v2\x1d.anixops.identity.v1.TokenKeyR\x04keys\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience\"\xd9\x02\n" +
	"\aAccount\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\faccount_uuid\x18\x02 \x01(\tR\vaccountUuid\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x12\x19\n" +
	"\bis_staff\x18\x05 \x01(\bR\aisStaff\x12\x16\n" +
	"\x06banned\x18\x06 \x01(\bR\x06banned\x12#\n" +
	"\rtoken_version\x18\a \x01(\x04R\ftokenVersion\x12\x18\n" +
	"\aversion\x18\b \x01(\x04R\aversion\x12&\n" +
	"\x0fcreated_at_unix\x18\t \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\n" +
	" \x01(\x03R\rupdatedAtUnix\x12\x1f\n" +
	"\vmfa_enabled\x18\v \x01(\bR\n" +
	"mfaEnabled\"4\n" +
	"\x17BatchGetAccountsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x04R\auserIds\"T\n" +
	"\x18BatchGetAccountsResponse\x128\n" +
	"\baccounts\x18\x01 \x03(\v2\x1c.anixops.identity.v1.AccountR\baccounts\"\x95\x02\n" +
	"\x15ImportAccountsRequest\x12;\n" +
	"\x06header\x18\x01 \x01(\v2!.anixops.identity.v1.ImportHeaderH\x00R\x06header\x12@\n" +
	"\aaccount\x18\x02 \x01(\v2$.anixops.identity.v1.ImportedAccountH\x00R\aaccount\x12J\n" +
	"\vinvite_code\x18\x03 \x01(\v2'.anixops.identity.v1.ImportedInviteCodeH\x00R\n" +
	"inviteCode\x12(\n" +
	"\x0fdeleted_user_id\x18\x04 \x01(\x04H\x00R\rdeletedUserIdB\a\n" +
	"\x05value\"a\n" +
	"\fImportHeader\x12\x1b\n" +
	"\timport_id\x18\x01 \x01(\tR\bimportId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\bR\x05delta\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x03 \x01(\tR\n" +
	"checkpoint\"\x92\x02\n" +
	"\x0fImportedAccount\x126\n" +
	"\aaccount\x18\x01 \x01(\v2\x1c.anixops.identity.v1.AccountR\aaccount\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12#\n" +
	"\rpassword_algo\x18\x03 \x01(\tR\fpasswordAlgo\x12#\n" +
	"\rpassword_salt\x18\x04 \x01(\tR\fpasswordSalt\x122\n" +
	"\x03mfa\x18\x05 \x01(\v2 .anixops.identity.v1.ImportedMFAR\x03mfa\x12$\n" +
	"\x0einvite_user_id\x18\x06 \x01(\x04R\finviteUserId\"\xe5\x01\n" +
	"\vImportedMFA\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vtotp_secret\x18\x02 \x01(\tR\n" +
	"totpSecret\x12,\n" +
	"\x12backup_code_hashes\x18\x03 \x03(\tR\x10backupCodeHashes\x12&\n" +
	"\x0fenabled_at_unix\x18\x04 \x01(\x03R\renabledAtUnix\x12$\n" +
	"\x0elast_used_unix\x18\x05 \x01(\x03R\flastUsedUnix\x12\x1f\n" +
	"\vlast_method\x18\x06 \x01(\tR\n" +
	"lastMethod\"}\n" +
	"\x12ImportedInviteCode\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04used\x18\x03 \x01(\bR\x04used\x12&\n" +
	"\x0fcreated_at_unix\x18\x04 \x01(\x03R\rcreatedAtUnix\"\x91\x01\n" +
	"\x16ImportAccountsResponse\x12\x1a\n" +
	"\baccounts\x18\x01 \x01(\x04R\baccounts\x12!\n" +
	"\finvite_codes\x18\x02 \x01(\x04R\vinviteCodes\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x03 \x01(\tR\n" +
	"checkpoint\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\x04R\adeleted\"R\n" +
	"\x15ExportAccountsRequest\x12#\n" +
	"\rafter_version\x18\x01 \x01(\x04R\fafterVersion\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit*\xa0\x01\n" +
	"\rTokenKeyState\x12\x1f\n" +
	"\x1bTOKEN_KEY_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TOKEN_KEY_STATE_NEXT\x10\x01\x12\x1a\n" +
	"\x16TOKEN_KEY_STATE_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17TOKEN_KEY_STATE_RETIRED\x10\x03\x12\x1b\n" +
	"\x17TOKEN_KEY_STATE_REVOKED\x10\x042\xb2\x03\n" +
	"\x0fIdentityService\x12c\n" +
	"\fGetTokenKeys\x12(.anixops.identity.v1.GetTokenKeysRequest\x1a).anixops.identity.v1.GetTokenKeysResponse\x12o\n" +
	"\x10BatchGetAccounts\x12,.anixops.identity.v1.BatchGetAccountsRequest\x1a-.anixops.identity.v1.BatchGetAccountsResponse\x12k\n" +
	"\x0eImportAccounts\x12*.anixops.identity.v1.ImportAccountsRequest\x1a+.anixops.identity.v1.ImportAccountsResponse(\x01\x12\\\n" +
	"\x0eExportAccounts\x12*.anixops.identity.v1.ExportAccountsRequest\x1a\x1c.anixops.identity.v1.Account0\x01B@Z>github.com/AnixOps/anix-control/sdk/api/identity/v1;identityv1b\x06proto3"

var (
	file_api_identity_v1_identity_proto_rawDescOnce sync.Once
	file_api_identity_v1_identity_proto_rawDescData []byte
)

func file_api_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_api_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_api_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_identity_v1_identity_proto_rawDesc), len(file_api_identity_v1_identity_proto_rawDesc)))
	})
	return file_api_identity_v1_identity_proto_rawDescData
}

var file_api_identity_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_identity_v1_identity_proto_goTypes = []any{
	(TokenKeyState)(0),               // 0: anixops.identity.v1.TokenKeyState
	(*TokenKey)(nil),                 // 1: anixops.identity.v1.TokenKey
	(*GetTokenKeysRequest)(nil),      // 2: anixops.identity.v1.GetTokenKeysRequest
	(*GetTokenKeysResponse)(nil),     // 3: anixops.identity.v1.GetTokenKeysResponse
	(*Account)(nil),                  // 4: anixops.identity.v1.Account
	(*BatchGetAccountsRequest)(nil),  // 5: anixops.identity.v1.BatchGetAccountsRequest
	(*BatchGetAccountsResponse)(nil), // 6: anixops.identity.v1.BatchGetAccountsResponse
	(*ImportAccountsRequest)(nil),    // 7: anixops.identity.v1.ImportAccountsRequest
	(*ImportHeader)(nil),             // 8: anixops.identity.v1.ImportHeader
	(*ImportedAccount)(nil),          // 9: anixops.identity.v1.ImportedAccount
	(*ImportedMFA)(nil),              // 10: anixops.identity.v1.ImportedMFA
	(*ImportedInviteCode)(nil),       // 11: anixops.identity.v1.ImportedInviteCode
	(*ImportAccountsResponse)(nil),   // 12: anixops.identity.v1.ImportAccountsResponse
	(*ExportAccountsRequest)(nil),    // 13: anixops.identity.v1.ExportAccountsRequest
}
var file_api_identity_v1_identity_proto_depIdxs = []int32{
	0,  // 0: anixops.identity.v1.TokenKey.state:type_name -> anixops.identity.v1.TokenKeyState
	1,  // 1: anixops.identity.v1.GetTokenKeysResponse.keys:type_name -> anixops.identity.v1.TokenKey
	4,  // 2: anixops.identity.v1.BatchGetAccountsResponse.accounts:type_name -> anixops.identity.v1.Account
	8,  // 3: anixops.identity.v1.ImportAccountsRequest.header:type_name -> anixops.identity.v1.ImportHeader
	9,  // 4: anixops.identity.v1.ImportAccountsRequest.account:type_name -> anixops.identity.v1.ImportedAccount
	11, // 5: anixops.identity.v1.ImportAccountsRequest.invite_code:type_name -> anixops.identity.v1.ImportedInviteCode
	4,  // 6: anixops.identity.v1.ImportedAccount.account:type_name -> anixops.identity.v1.Account
	10, // 7: anixops.identity.v1.ImportedAccount.mfa:type_name -> anixops.identity.v1.ImportedMFA
	2,  // 8: anixops.identity.v1.IdentityService.GetTokenKeys:input_type -> anixops.identity.v1.GetTokenKeysRequest
	5,  // 9: anixops.identity.v1.IdentityService.BatchGetAccounts:input_type -> anixops.identity.v1.BatchGetAccountsRequest
	7,  // 10: anixops.identity.v1.IdentityService.ImportAccounts:input_type -> anixops.identity.v1.ImportAccountsRequest
	13, // 11: anixops.identity.v1.IdentityService.ExportAccounts:input_type -> anixops.identity.v1.ExportAccountsRequest
	3,  // 12: anixops.identity.v1.IdentityService.GetTokenKeys:output_type -> anixops.identity.v1.GetTokenKeysResponse
	6,  // 13: anixops.identity.v1.IdentityService.BatchGetAccounts:output_type -> anixops.identity.v1.BatchGetAccountsResponse
	12, // 14: anixops.identity.v1.IdentityService.ImportAccounts:output_type -> anixops.identity.v1.ImportAccountsResponse
	4,  // 15: anixops.identity.v1.IdentityService.ExportAccounts:output_type -> anixops.identity.v1.Account
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_identity_v1_identity_proto_init() }
func file_api_identity_v1_identity_proto_init() {
	if File_api_identity_v1_identity_proto != nil {
		return
	}
	file_api_identity_v1_identity_proto_msgTypes[6].OneofWrappers = []any{
		(*ImportAccountsRequest_Header)(nil),
		(*ImportAccountsRequest_Account)(nil),
		(*ImportAccountsRequest_InviteCode)(nil),
		(*ImportAccountsRequest_DeletedUserId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_identity_v1_identity_proto_rawDesc), len(file_api_identity_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_api_identity_v1_identity_proto_depIdxs,
		EnumInfos:         file_api_identity_v1_identity_proto_enumTypes,
		MessageInfos:      file_api_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_api_identity_v1_identity_proto = out.File
	file_api_identity_v1_identity_proto_goTypes = nil
	file_api_identity_v1_identity_proto_depIdxs = nil
}
