server {
    listen 80;
    listen [::]:80;

    server_name __SERVER_NAMES__;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }

    access_log /var/log/nginx/x.kalijerry.uk-http.access.log;
    error_log /var/log/nginx/x.kalijerry.uk-http.error.log;
}
