package service

import (
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"log"
	"testing"
	"time"

	"github.com/AnixOps/anix-control/v4/internal/model"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

// The official signing root changed (v4.2): the identity-platform
// installation of a Control that ran with the old root points at a release
// bound to a retired root, so nobody can log in. These tests drive
// BootstrapIdentityPlatformPackage the way cmd/server's bootstrapDatabase does
// on the first start with the new root, on SQLite and on PostgreSQL. Every key
// here is generated by the test; no release key appears anywhere.

type rotationKey struct {
	public  ed25519.PublicKey
	private ed25519.PrivateKey
}

func newRotationKey(t *testing.T) rotationKey {
	t.Helper()
	public, private, err := ed25519.GenerateKey(rand.Reader)
	require.NoError(t, err)
	return rotationKey{public: public, private: private}
}

func (k rotationKey) encoded() string     { return base64.StdEncoding.EncodeToString(k.public) }
func (k rotationKey) fingerprint() string { return PluginTrustRootFingerprint(k.public) }
func (k rotationKey) keyID() string       { return PluginTrustRootKeyID(k.public) }

// startControlWithRoot is the start of a Control configured with key's root:
// bootstrapDatabase makes the configured root the active one, then runs the
// identity bootstrap with the same key and the package directory.
func startControlWithRoot(db *gorm.DB, key rotationKey, bootstrapDir string) error {
	if _, err := EnsurePluginTrustRoot(db, key.public); err != nil {
		return err
	}
	return BootstrapIdentityPlatformPackage(db, key.encoded(), bootstrapDir)
}

// prepareRotationDB creates the kernel schema; withOperationLog adds the
// operation log table that cmd/server's schema migration creates before the
// bootstrap runs.
func prepareRotationDB(t *testing.T, db *gorm.DB, withOperationLog bool) {
	t.Helper()
	require.NoError(t, EnsureKernelSchema(db))
	if withOperationLog {
		require.NoError(t, db.AutoMigrate(&model.OperationLog{}))
	}
}

// seedIdentityUnderRoot is a Control that ran with key's root and the
// bootstrap package at version: the release is registered, the artifact
// stored and the installation healthy at generation.
func seedIdentityUnderRoot(t *testing.T, db *gorm.DB, key rotationKey, version string, generation int64) model.PluginInstallation {
	t.Helper()
	directory := writeBootstrapIdentityPlatformPackageVersion(t, key.private, version)
	require.NoError(t, startControlWithRoot(db, key, directory))
	require.NoError(t, db.Model(&model.PluginInstallation{}).
		Where("plugin_id = ? AND target = ?", "identity-platform", "control").
		Updates(map[string]any{"observed_version": version, "state": "healthy", "lifecycle_generation": generation}).Error)
	return loadIdentityInstallation(t, db)
}

// seedPluginUnderRoot registers another package under key and installs it
// healthy at generation 5.
func seedPluginUnderRoot(t *testing.T, db *gorm.DB, key rotationKey, pluginID, version string, mutate func(*PluginManifest)) model.PluginInstallation {
	t.Helper()
	pkg := signedTestPackage(t, key.private, pluginID, version, mutate)
	release, err := RegisterPluginRelease(db, pkg.ManifestJSON, pkg.Signature, key.public)
	require.NoError(t, err)
	_, err = StorePluginArtifact(db, release.ID, pkg.Artifact)
	require.NoError(t, err)
	installation := model.PluginInstallation{
		PluginID: pluginID, Target: "control", DesiredVersion: version, ObservedVersion: version,
		State: "healthy", Enabled: true, LifecycleGeneration: 5,
	}
	require.NoError(t, db.Create(&installation).Error)
	return installation
}

func loadIdentityInstallation(t *testing.T, db *gorm.DB) model.PluginInstallation {
	t.Helper()
	return loadInstallation(t, db, "identity-platform")
}

func loadInstallation(t *testing.T, db *gorm.DB, pluginID string) model.PluginInstallation {
	t.Helper()
	var installation model.PluginInstallation
	require.NoError(t, db.First(&installation, "plugin_id = ? AND target = ?", pluginID, "control").Error)
	return installation
}

func loadRelease(t *testing.T, db *gorm.DB, pluginID, version string) model.PluginRelease {
	t.Helper()
	var release model.PluginRelease
	require.NoError(t, db.First(&release, "plugin_id = ? AND version = ?", pluginID, version).Error)
	return release
}

func rotationAuditEntries(t *testing.T, db *gorm.DB) []model.OperationLog {
	t.Helper()
	var entries []model.OperationLog
	require.NoError(t, db.Where("module = ?", "kernel").Order("id").Find(&entries).Error)
	return entries
}

func countReleases(t *testing.T, db *gorm.DB, pluginID string) int64 {
	t.Helper()
	var count int64
	require.NoError(t, db.Model(&model.PluginRelease{}).Where("plugin_id = ?", pluginID).Count(&count).Error)
	return count
}

// captureStandardLog returns what the standard logger prints from now on.
func captureStandardLog(t *testing.T) *bytes.Buffer {
	t.Helper()
	var buffer bytes.Buffer
	previous := log.Writer()
	log.SetOutput(&buffer)
	t.Cleanup(func() { log.SetOutput(previous) })
	return &buffer
}

func TestBootstrapIdentityRootRotationSQLite(t *testing.T) {
	runIdentityRootRotationSuite(t, openRouteModeSQLite)
}

// TestPostgresBootstrapIdentityRootRotation runs the suite on PostgreSQL; CI's
// PostgreSQL regression job selects it by its name.
func TestPostgresBootstrapIdentityRootRotation(t *testing.T) {
	runIdentityRootRotationSuite(t, openRouteModePostgres)
}

func runIdentityRootRotationSuite(t *testing.T, open func(*testing.T) *gorm.DB) {
	t.Run("a retired-root installation moves to the verified bootstrap release", func(t *testing.T) {
		testRotationMovesInstallation(t, open(t))
	})
	t.Run("the same root never upgrades a healthy installation", func(t *testing.T) {
		testRotationSameRootUntouched(t, open(t))
	})
	t.Run("a bootstrap package signed by a third key changes nothing", func(t *testing.T) {
		testRotationThirdKeyRefused(t, open(t))
	})
	t.Run("other packages are not touched", func(t *testing.T) {
		testRotationOtherPluginsUntouched(t, open(t))
	})
	t.Run("a second start is idempotent", func(t *testing.T) {
		testRotationIdempotent(t, open(t))
	})
	t.Run("a bootstrap release that is not newer is refused", func(t *testing.T) {
		testRotationNotNewerRefused(t, open)
	})
	t.Run("the same version signed by another root keeps its error", func(t *testing.T) {
		testRotationSameVersionOtherRoot(t, open(t))
	})
	t.Run("a disabled installation is not re-enabled", func(t *testing.T) {
		testRotationDisabledUntouched(t, open(t))
	})
	t.Run("an installation without a release row is left alone", func(t *testing.T) {
		testRotationMissingReleaseUntouched(t, open(t))
	})
	t.Run("the move is validated like an administrator update", func(t *testing.T) {
		testRotationValidatedLikeAdminUpdate(t, open(t))
	})
	t.Run("the audit write is part of the transaction", func(t *testing.T) {
		testRotationAuditFailureRollsBack(t, open(t))
	})
	t.Run("the new lifecycle generation is accepted by the migration ledger", func(t *testing.T) {
		testRotationMigrationLedger(t, open(t))
	})
}

func testRotationMovesInstallation(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	before := seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)
	lastError := "plugin host unavailable: verified artifact reference is unavailable"
	require.NoError(t, db.Model(&before).Updates(map[string]any{"state": "failed", "last_error": lastError}).Error)
	logs := captureStandardLog(t)

	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.2.0-rc.1")
	require.NoError(t, startControlWithRoot(db, rootB, directory))

	// The installation intent moved the way an administrator's update moves
	// it: new desired version, pending, a new lifecycle generation. The host
	// start, the migration run and the observed version are the lifecycle
	// worker's, which the restart reconciliation queues for the new generation.
	after := loadIdentityInstallation(t, db)
	require.Equal(t, before.ID, after.ID)
	require.Equal(t, "4.2.0-rc.1", after.DesiredVersion)
	require.Equal(t, "4.1.0", after.ObservedVersion)
	require.Equal(t, "4.1.0", after.PreviousVersion)
	require.Equal(t, "pending", after.State)
	require.True(t, after.Enabled)
	require.Nil(t, after.DisabledAt)
	require.EqualValues(t, 4, after.LifecycleGeneration)
	require.Equal(t, lastError, after.LastError, "the worker clears the error when the host starts")
	require.Equal(t, before.ConfigRevision, after.ConfigRevision)

	// Releases are immutable: the old one stays bound to the retired root and
	// the new one is bound to the active root and verifies under it.
	oldRelease := loadRelease(t, db, "identity-platform", "4.1.0")
	newRelease := loadRelease(t, db, "identity-platform", "4.2.0-rc.1")
	require.Equal(t, rootA.fingerprint(), oldRelease.TrustRootFingerprint)
	require.Equal(t, rootB.fingerprint(), newRelease.TrustRootFingerprint)
	_, err := VerifyStoredPluginRelease(db, oldRelease, rootB.public)
	require.ErrorIs(t, err, ErrPluginTrustRootRequired)
	_, err = VerifyStoredPluginRelease(db, newRelease, rootB.public)
	require.NoError(t, err)
	require.NoError(t, ValidatePluginInstallationPlan(db, newRelease, "control", true, after.ID))
	artifact, err := GetPluginArtifact(db, newRelease.ID)
	require.NoError(t, err)
	require.NotEmpty(t, artifact.Data)

	// Audited, naming both versions and both roots.
	entries := rotationAuditEntries(t, db)
	require.Len(t, entries, 1)
	require.Equal(t, "bootstrap_installation_update", entries[0].Action)
	require.Equal(t, "plugin_installation", entries[0].TargetType)
	require.NotNil(t, entries[0].TargetID)
	require.Equal(t, after.ID, *entries[0].TargetID)
	require.Equal(t, "system/bootstrap", entries[0].Username)
	require.Equal(t, 1, entries[0].Status)
	var content map[string]any
	require.NoError(t, json.Unmarshal([]byte(entries[0].Content), &content))
	require.Equal(t, "identity-platform", content["plugin_id"])
	require.Equal(t, "4.1.0", content["from_version"])
	require.Equal(t, "4.2.0-rc.1", content["to_version"])
	require.Equal(t, rootA.fingerprint(), content["from_trust_root_fingerprint"])
	require.Equal(t, rootB.fingerprint(), content["to_trust_root_fingerprint"])
	require.EqualValues(t, 3, content["from_lifecycle_generation"])
	require.EqualValues(t, 4, content["to_lifecycle_generation"])

	// Loud: one warning that names old and new versions and roots.
	printed := logs.String()
	require.Contains(t, printed, "WARNING")
	for _, fact := range []string{"identity-platform", "4.1.0", "4.2.0-rc.1", rootA.keyID(), rootB.keyID()} {
		require.Contains(t, printed, fact)
	}
}

func testRotationSameRootUntouched(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA := newRotationKey(t)
	before := seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)
	logs := captureStandardLog(t)

	// The bootstrap package is newer and verifies, but the installed release
	// is bound to the active root: a bootstrap never silently upgrades.
	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootA.private, "4.2.0")
	require.NoError(t, startControlWithRoot(db, rootA, directory))

	require.Equal(t, before, loadIdentityInstallation(t, db))
	require.EqualValues(t, 2, countReleases(t, db, "identity-platform"), "the bootstrap release is still registered")
	require.Empty(t, rotationAuditEntries(t, db))
	require.NotContains(t, logs.String(), "WARNING")
}

func testRotationThirdKeyRefused(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB, rootC := newRotationKey(t), newRotationKey(t), newRotationKey(t)
	before := seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)
	_, err := EnsurePluginTrustRoot(db, rootB.public)
	require.NoError(t, err)

	// The configuration names root B; the package in the directory is signed
	// by a key nobody configured.
	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootC.private, "4.2.0")
	err = BootstrapIdentityPlatformPackage(db, rootB.encoded(), directory)
	require.Error(t, err)
	require.ErrorContains(t, err, "verify identity bootstrap package")
	require.ErrorContains(t, err, "plugin signature verification failed")

	require.Equal(t, before, loadIdentityInstallation(t, db))
	require.EqualValues(t, 1, countReleases(t, db, "identity-platform"))
	require.Empty(t, rotationAuditEntries(t, db))
}

func testRotationOtherPluginsUntouched(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)
	seedPluginUnderRoot(t, db, rootA, "knowledge", "4.1.0", nil)
	knowledgeBefore := loadInstallation(t, db, "knowledge")

	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.2.0")
	require.NoError(t, startControlWithRoot(db, rootB, directory))

	require.Equal(t, "4.2.0", loadIdentityInstallation(t, db).DesiredVersion)
	// knowledge still points at its old-root release: the operator imports
	// the other packages (docs/UPGRADE.md), the bootstrap never does.
	require.Equal(t, knowledgeBefore, loadInstallation(t, db, "knowledge"))
	knowledgeRelease := loadRelease(t, db, "knowledge", "4.1.0")
	require.Equal(t, rootA.fingerprint(), knowledgeRelease.TrustRootFingerprint)
	_, err := VerifyStoredPluginRelease(db, knowledgeRelease, rootB.public)
	require.ErrorIs(t, err, ErrPluginTrustRootRequired)
	require.EqualValues(t, 1, countReleases(t, db, "knowledge"))
	entries := rotationAuditEntries(t, db)
	require.Len(t, entries, 1)
	require.Contains(t, entries[0].Content, `"plugin_id":"identity-platform"`)
}

func testRotationIdempotent(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)
	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.2.0")
	require.NoError(t, startControlWithRoot(db, rootB, directory))
	moved := loadIdentityInstallation(t, db)
	require.EqualValues(t, 4, moved.LifecycleGeneration)
	logs := captureStandardLog(t)

	// A restart before the worker ran, and one after it did (desired is
	// observed and healthy): neither moves anything or writes another entry.
	require.NoError(t, startControlWithRoot(db, rootB, directory))
	require.Equal(t, moved, loadIdentityInstallation(t, db))
	require.NoError(t, db.Model(&model.PluginInstallation{}).Where("id = ?", moved.ID).
		Updates(map[string]any{"observed_version": "4.2.0", "state": "healthy", "last_error": ""}).Error)
	healthy := loadIdentityInstallation(t, db)
	require.NoError(t, startControlWithRoot(db, rootB, directory))
	require.Equal(t, healthy, loadIdentityInstallation(t, db))

	require.Len(t, rotationAuditEntries(t, db), 1)
	require.EqualValues(t, 2, countReleases(t, db, "identity-platform"))
	require.NotContains(t, logs.String(), "WARNING")
}

func testRotationNotNewerRefused(t *testing.T, open func(*testing.T) *gorm.DB) {
	for _, test := range []struct {
		name      string
		installed string
		bootstrap string
	}{
		{name: "older", installed: "4.2.0", bootstrap: "4.1.0"},
		{name: "older prerelease", installed: "4.2.0", bootstrap: "4.2.0-rc.1"},
		{name: "same precedence", installed: "4.2.0", bootstrap: "4.2.0+rebuild"},
		{name: "not full semantic versions", installed: "20260101", bootstrap: "20260202"},
		{name: "shorthand versions", installed: "4.2", bootstrap: "4.3"},
	} {
		t.Run(test.name, func(t *testing.T) {
			db := open(t)
			prepareRotationDB(t, db, true)
			rootA, rootB := newRotationKey(t), newRotationKey(t)
			before := seedIdentityUnderRoot(t, db, rootA, test.installed, 3)
			logs := captureStandardLog(t)

			// A bootstrap package never moves an installation to a release that
			// is not provably newer; the start goes on (a rolled-back image
			// must still start) and says so.
			directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, test.bootstrap)
			require.NoError(t, startControlWithRoot(db, rootB, directory))

			require.Equal(t, before, loadIdentityInstallation(t, db))
			require.Empty(t, rotationAuditEntries(t, db))
			printed := logs.String()
			require.Contains(t, printed, "WARNING")
			require.Contains(t, printed, "not moved")
			require.Contains(t, printed, test.installed)
			require.Contains(t, printed, test.bootstrap)
			require.Contains(t, printed, rootA.keyID())
			require.Contains(t, printed, rootB.keyID())
		})
	}
}

func testRotationSameVersionOtherRoot(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	before := seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)

	// Releases are immutable per version: re-signing 4.1.0 with the new root
	// is not a new release, and the existing error stands.
	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.1.0")
	err := startControlWithRoot(db, rootB, directory)
	require.EqualError(t, err, "existing identity release uses a different trust root")
	require.Equal(t, before, loadIdentityInstallation(t, db))
	require.Empty(t, rotationAuditEntries(t, db))
}

func testRotationDisabledUntouched(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)
	disabledAt := time.Now().UTC().Truncate(time.Second)
	require.NoError(t, db.Model(&model.PluginInstallation{}).Where("plugin_id = ?", "identity-platform").
		Updates(map[string]any{"enabled": false, "state": "disabled", "disabled_at": &disabledAt}).Error)
	before := loadIdentityInstallation(t, db)
	logs := captureStandardLog(t)

	// An administrator disabled identity-platform: the bootstrap does not
	// override that decision, even with a newer package under the active root.
	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.2.0")
	require.NoError(t, startControlWithRoot(db, rootB, directory))

	require.Equal(t, before, loadIdentityInstallation(t, db))
	require.Empty(t, rotationAuditEntries(t, db))
	require.NotContains(t, logs.String(), "WARNING")
}

func testRotationMissingReleaseUntouched(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)
	require.NoError(t, db.Model(&model.PluginInstallation{}).Where("plugin_id = ?", "identity-platform").
		Updates(map[string]any{"desired_version": "operator-selected"}).Error)
	before := loadIdentityInstallation(t, db)

	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.2.0")
	require.NoError(t, startControlWithRoot(db, rootB, directory))

	require.Equal(t, before, loadIdentityInstallation(t, db))
	require.Empty(t, rotationAuditEntries(t, db))
}

func testRotationValidatedLikeAdminUpdate(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	before := seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)
	// An enabled package that declares a conflict with identity-platform: an
	// administrator's update of identity-platform is refused with
	// plugin_conflict, so the bootstrap must not move it either.
	seedPluginUnderRoot(t, db, rootA, "conflicting", "4.1.0", func(manifest *PluginManifest) {
		manifest.Conflicts = []string{"identity-platform"}
	})
	logs := captureStandardLog(t)

	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.2.0")
	require.NoError(t, startControlWithRoot(db, rootB, directory))

	require.Equal(t, before, loadIdentityInstallation(t, db))
	require.Empty(t, rotationAuditEntries(t, db))
	printed := logs.String()
	require.Contains(t, printed, "WARNING")
	require.Contains(t, printed, "not moved")
	require.Contains(t, printed, "conflicts with")
}

func testRotationAuditFailureRollsBack(t *testing.T, db *gorm.DB) {
	// Without the operation log table the audit write fails: the move must
	// not survive as an unaudited change, and the start must say so.
	prepareRotationDB(t, db, false)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	before := seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)

	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.2.0")
	err := startControlWithRoot(db, rootB, directory)
	require.Error(t, err)
	require.ErrorContains(t, err, "audit")
	require.Equal(t, before, loadIdentityInstallation(t, db))
}

func testRotationMigrationLedger(t *testing.T, db *gorm.DB) {
	prepareRotationDB(t, db, true)
	rootA, rootB := newRotationKey(t), newRotationKey(t)
	seedIdentityUnderRoot(t, db, rootA, "4.1.0", 3)

	// The ledger holds a verified run of the old version at generation 3.
	run, err := BeginPackageMigration(db, model.PackageMigrationRun{
		PackageID: "identity-platform", PackageVersion: "4.1.0", Generation: 3,
		MigrationID: "identity-index", MigrationChecksum: "checksum-4.1.0",
		BeforeSchemaVersion: noPreviousSchemaVersion, AfterSchemaVersion: "4.1.0",
	})
	require.NoError(t, err)
	_, err = RecordMigrationCheckpoint(db, run.ID, PackageMigrationCheckpoint{
		OpaqueCheckpoint: "complete", ValidationDigest: "digest-4.1.0", Complete: true,
	})
	require.NoError(t, err)
	verifiedAt := time.Now().UTC()
	require.NoError(t, db.Model(&model.PackageMigrationRun{}).Where("id = ?", run.ID).Updates(map[string]any{
		"health_lease_id": "lease-3", "health_generation": uint64(3), "health_verified_at": &verifiedAt,
	}).Error)
	_, err = RecordPackageValidation(db, model.PackageValidationResult{MigrationRunID: run.ID})
	require.NoError(t, err)

	directory := writeBootstrapIdentityPlatformPackageVersion(t, rootB.private, "4.2.0")
	require.NoError(t, startControlWithRoot(db, rootB, directory))
	moved := loadIdentityInstallation(t, db)

	// The host start of the new release runs under the new generation, which
	// the ledger accepts after the verified run of generation 3. The old
	// generation cannot be reused for another version: a column write that
	// kept it would fail the migration of the host it moved to.
	next := model.PackageMigrationRun{
		PackageID: "identity-platform", PackageVersion: "4.2.0", Generation: uint64(moved.LifecycleGeneration), // #nosec G115 -- the move leaves a positive generation.
		MigrationID: "identity-index-next", MigrationChecksum: "checksum-4.2.0",
		BeforeSchemaVersion: "4.1.0", AfterSchemaVersion: "4.2.0", BackupReference: "operator-managed:identity-platform",
	}
	started, err := BeginPackageMigration(db, next)
	require.NoError(t, err)
	require.NotNil(t, started.PreviousGenerationID)
	reused := next
	reused.Generation = 3
	_, err = BeginPackageMigration(db, reused)
	require.ErrorIs(t, err, ErrPackageMigrationImmutable)
}
