// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: api/kernelorder/v1/kernel_order.proto

package kernelorderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderPaymentOutcome is what a paid record did to its order.
type OrderPaymentOutcome int32

const (
	OrderPaymentOutcome_ORDER_PAYMENT_OUTCOME_UNSPECIFIED OrderPaymentOutcome = 0
	// The order was marked paid and completed: its plan is granted.
	OrderPaymentOutcome_ORDER_PAYMENT_OUTCOME_COMPLETED OrderPaymentOutcome = 1
	// The order was marked paid, but granting its plan failed; it stays paid
	// for an administrator to complete.
	OrderPaymentOutcome_ORDER_PAYMENT_OUTCOME_PAID OrderPaymentOutcome = 2
	// The record does not pay its order (see reason); the order is unchanged
	// and the payment stays recorded.
	OrderPaymentOutcome_ORDER_PAYMENT_OUTCOME_REFUSED OrderPaymentOutcome = 3
)

// Enum value maps for OrderPaymentOutcome.
var (
	OrderPaymentOutcome_name = map[int32]string{
		0: "ORDER_PAYMENT_OUTCOME_UNSPECIFIED",
		1: "ORDER_PAYMENT_OUTCOME_COMPLETED",
		2: "ORDER_PAYMENT_OUTCOME_PAID",
		3: "ORDER_PAYMENT_OUTCOME_REFUSED",
	}
	OrderPaymentOutcome_value = map[string]int32{
		"ORDER_PAYMENT_OUTCOME_UNSPECIFIED": 0,
		"ORDER_PAYMENT_OUTCOME_COMPLETED":   1,
		"ORDER_PAYMENT_OUTCOME_PAID":        2,
		"ORDER_PAYMENT_OUTCOME_REFUSED":     3,
	}
)

func (x OrderPaymentOutcome) Enum() *OrderPaymentOutcome {
	p := new(OrderPaymentOutcome)
	*p = x
	return p
}

func (x OrderPaymentOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderPaymentOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kernelorder_v1_kernel_order_proto_enumTypes[0].Descriptor()
}

func (OrderPaymentOutcome) Type() protoreflect.EnumType {
	return &file_api_kernelorder_v1_kernel_order_proto_enumTypes[0]
}

func (x OrderPaymentOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderPaymentOutcome.Descriptor instead.
func (OrderPaymentOutcome) EnumDescriptor() ([]byte, []int) {
	return file_api_kernelorder_v1_kernel_order_proto_rawDescGZIP(), []int{0}
}

type CompleteOrderPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trade_no is the payment record's trade number
	// (v2_payment_record.trade_no), at most 120 bytes.
	TradeNo string `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	// order_id is the order the record names (v2_payment_record.order_id).
	OrderId       uint64 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderPaymentRequest) Reset() {
	*x = CompleteOrderPaymentRequest{}
	mi := &file_api_kernelorder_v1_kernel_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderPaymentRequest) ProtoMessage() {}

func (x *CompleteOrderPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kernelorder_v1_kernel_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderPaymentRequest.ProtoReflect.Descriptor instead.
func (*CompleteOrderPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_kernelorder_v1_kernel_order_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteOrderPaymentRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *CompleteOrderPaymentRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CompleteOrderPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// applied is false when the trade number was applied before; the other
	// fields then describe that first application.
	Applied bool                `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	OrderId uint64              `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Outcome OrderPaymentOutcome `protobuf:"varint,3,opt,name=outcome,proto3,enum=anixops.kernelorder.v1.OrderPaymentOutcome" json:"outcome,omitempty"`
	// reason says why a REFUSED record does not pay its order.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderPaymentResponse) Reset() {
	*x = CompleteOrderPaymentResponse{}
	mi := &file_api_kernelorder_v1_kernel_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderPaymentResponse) ProtoMessage() {}

func (x *CompleteOrderPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kernelorder_v1_kernel_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderPaymentResponse.ProtoReflect.Descriptor instead.
func (*CompleteOrderPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_kernelorder_v1_kernel_order_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteOrderPaymentResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *CompleteOrderPaymentResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CompleteOrderPaymentResponse) GetOutcome() OrderPaymentOutcome {
	if x != nil {
		return x.Outcome
	}
	return OrderPaymentOutcome_ORDER_PAYMENT_OUTCOME_UNSPECIFIED
}

func (x *CompleteOrderPaymentResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_kernelorder_v1_kernel_order_proto protoreflect.FileDescriptor

const file_api_kernelorder_v1_kernel_order_proto_rawDesc = "" +
	"\n" +
	"%api/kernelorder/v1/kernel_order.proto\x12\x16anixops.kernelorder.v1\"S\n" +
	"\x1bCompleteOrderPaymentRequest\x12\x19\n" +
	"\btrade_no\x18\x01 \x01(\tR\atradeNo\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"\xb2\x01\n" +
	"\x1cCompleteOrderPaymentResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x12E\n" +
	"\aoutcome\x18\x03 \x01(\x0e2+.anixops.kernelorder.v1.OrderPaymentOutcomeR\aoutcome\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason*\xa4\x01\n" +
	"\x13OrderPaymentOutcome\x12%\n" +
	"!ORDER_PAYMENT_OUTCOME_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fORDER_PAYMENT_OUTCOME_COMPLETED\x10\x01\x12\x1e\n" +
	"\x1aORDER_PAYMENT_OUTCOME_PAID\x10\x02\x12!\n" +
	"\x1dORDER_PAYMENT_OUTCOME_REFUSED\x10\x032\x91\x01\n" +
	"\vKernelOrder\x12\x81\x01\n" +
	"\x14CompleteOrderPayment\x123.anixops.kernelorder.v1.CompleteOrderPaymentRequest\x1a4.anixops.kernelorder.v1.CompleteOrderPaymentResponseBFZDgithub.com/AnixOps/anix-control/sdk/api/kernelorder/v1;kernelorderv1b\x06proto3"

var (
	file_api_kernelorder_v1_kernel_order_proto_rawDescOnce sync.Once
	file_api_kernelorder_v1_kernel_order_proto_rawDescData []byte
)

func file_api_kernelorder_v1_kernel_order_proto_rawDescGZIP() []byte {
	file_api_kernelorder_v1_kernel_order_proto_rawDescOnce.Do(func() {
		file_api_kernelorder_v1_kernel_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kernelorder_v1_kernel_order_proto_rawDesc), len(file_api_kernelorder_v1_kernel_order_proto_rawDesc)))
	})
	return file_api_kernelorder_v1_kernel_order_proto_rawDescData
}

var file_api_kernelorder_v1_kernel_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_kernelorder_v1_kernel_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_kernelorder_v1_kernel_order_proto_goTypes = []any{
	(OrderPaymentOutcome)(0),             // 0: anixops.kernelorder.v1.OrderPaymentOutcome
	(*CompleteOrderPaymentRequest)(nil),  // 1: anixops.kernelorder.v1.CompleteOrderPaymentRequest
	(*CompleteOrderPaymentResponse)(nil), // 2: anixops.kernelorder.v1.CompleteOrderPaymentResponse
}
var file_api_kernelorder_v1_kernel_order_proto_depIdxs = []int32{
	0, // 0: anixops.kernelorder.v1.CompleteOrderPaymentResponse.outcome:type_name -> anixops.kernelorder.v1.OrderPaymentOutcome
	1, // 1: anixops.kernelorder.v1.KernelOrder.CompleteOrderPayment:input_type -> anixops.kernelorder.v1.CompleteOrderPaymentRequest
	2, // 2: anixops.kernelorder.v1.KernelOrder.CompleteOrderPayment:output_type -> anixops.kernelorder.v1.CompleteOrderPaymentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_kernelorder_v1_kernel_order_proto_init() }
func file_api_kernelorder_v1_kernel_order_proto_init() {
	if File_api_kernelorder_v1_kernel_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kernelorder_v1_kernel_order_proto_rawDesc), len(file_api_kernelorder_v1_kernel_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kernelorder_v1_kernel_order_proto_goTypes,
		DependencyIndexes: file_api_kernelorder_v1_kernel_order_proto_depIdxs,
		EnumInfos:         file_api_kernelorder_v1_kernel_order_proto_enumTypes,
		MessageInfos:      file_api_kernelorder_v1_kernel_order_proto_msgTypes,
	}.Build()
	File_api_kernelorder_v1_kernel_order_proto = out.File
	file_api_kernelorder_v1_kernel_order_proto_goTypes = nil
	file_api_kernelorder_v1_kernel_order_proto_depIdxs = nil
}
