package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestApplyEnvOverridesEverySupportedType(t *testing.T) {
	loaded := &Config{}
	unknown, err := ApplyEnv(loaded, []string{
		"ANIX_CONTROL_DATABASE_PASSWORD=p@ss word",
		"ANIX_CONTROL_DATABASE_PORT=6543",
		"ANIX_CONTROL_PLUGINS_CONTROL_EXECUTION_ENABLED=true",
		"ANIX_CONTROL_PLUGINS_CONTROL_HOST_MAX_RESPONSE_BYTES=2097152",
		"ANIX_CONTROL_AUTH_LOGIN_RATE_LIMIT_ENABLED=false",
		"ANIX_CONTROL_SERVER_TRUSTED_PROXIES=10.0.0.0/8, 192.168.0.0/16 ,",
		"ANIX_CONTROL_FORWARD_RUNTIME_NODEX_TOKEN=nodex-token",
		"UNRELATED=1",
	})
	require.NoError(t, err)
	assert.Empty(t, unknown)
	assert.Equal(t, "p@ss word", loaded.Database.Password)
	assert.Equal(t, 6543, loaded.Database.Port)
	assert.True(t, loaded.Plugins.ControlExecutionEnabled)
	assert.EqualValues(t, 2097152, loaded.Plugins.ControlHostMaxResponseBytes)
	require.NotNil(t, loaded.Auth.LoginRateLimit.Enabled)
	assert.False(t, *loaded.Auth.LoginRateLimit.Enabled)
	assert.Equal(t, []string{"10.0.0.0/8", "192.168.0.0/16"}, loaded.Server.TrustedProxies)
	assert.Equal(t, "nodex-token", loaded.ForwardRuntime.NodeX.Token)
}

func TestApplyEnvReadsSecretsFromFiles(t *testing.T) {
	secretFile := filepath.Join(t.TempDir(), "jwt")
	require.NoError(t, os.WriteFile(secretFile, []byte("file-secret\n"), 0o600))

	loaded := &Config{}
	_, err := ApplyEnv(loaded, []string{"ANIX_CONTROL_JWT_SECRET_FILE=" + secretFile})
	require.NoError(t, err)
	assert.Equal(t, "file-secret", loaded.JWT.Secret)

	_, err = ApplyEnv(loaded, []string{"ANIX_CONTROL_JWT_SECRET=x", "ANIX_CONTROL_JWT_SECRET_FILE=" + secretFile})
	require.ErrorContains(t, err, "use one")

	_, err = ApplyEnv(loaded, []string{"ANIX_CONTROL_JWT_SECRET_FILE=" + filepath.Join(t.TempDir(), "missing")})
	require.ErrorContains(t, err, "ANIX_CONTROL_JWT_SECRET_FILE")
}

func TestApplyEnvRejectsInvalidValuesAndReportsUnknownNames(t *testing.T) {
	_, err := ApplyEnv(&Config{}, []string{"ANIX_CONTROL_DATABASE_PORT=abc"})
	require.ErrorContains(t, err, "ANIX_CONTROL_DATABASE_PORT")

	_, err = ApplyEnv(&Config{}, []string{"ANIX_CONTROL_GRPC_ENABLED=maybe"})
	require.ErrorContains(t, err, "ANIX_CONTROL_GRPC_ENABLED")

	unknown, err := ApplyEnv(&Config{}, []string{
		"ANIX_CONTROL_DATABSE_PASSWORD=typo",
		"ANIX_CONTROL_CONFIG=/app/config/config.yaml",
		"ANIX_CONTROL_HOST_SOCKET=/proc/self/fd/3/host.sock",
	})
	require.NoError(t, err)
	assert.Equal(t, []string{"ANIX_CONTROL_DATABSE_PASSWORD"}, unknown)
}

func TestEnvVarNamesAreUniqueAndNeverReserved(t *testing.T) {
	seen := map[string]string{}
	for _, variable := range EnvVars(Defaults()) {
		require.True(t, strings.HasPrefix(variable.Name, EnvPrefix), variable.Name)
		require.False(t, reservedEnvNames[variable.Name], "%s collides with a reserved variable", variable.Name)
		require.False(t, reservedEnvNames[variable.Name+EnvFileSuffix], "%s_FILE collides with a reserved variable", variable.Name)
		if previous, ok := seen[variable.Name]; ok {
			t.Fatalf("%s is generated by both %s and %s", variable.Name, previous, variable.Path)
		}
		seen[variable.Name] = variable.Path
	}
	for _, required := range []string{"ANIX_CONTROL_DATABASE_PASSWORD", "ANIX_CONTROL_JWT_SECRET", "ANIX_CONTROL_DATABASE_SSLMODE", "ANIX_CONTROL_PLUGINS_IDENTITY_BOOTSTRAP_PACKAGE_DIR"} {
		assert.Contains(t, seen, required)
	}
}

func TestEnvVarsNeverExposeSecretValues(t *testing.T) {
	loaded := Defaults()
	loaded.JWT.Secret = "do-not-print"
	loaded.Database.Password = "do-not-print"
	loaded.GRPC.APIToken = "do-not-print"
	for _, variable := range EnvVars(loaded) {
		assert.NotEqual(t, "do-not-print", variable.Default, variable.Name)
	}
}

func TestLoadWithoutConfigFileUsesBuiltInDefaultsAndEnvironment(t *testing.T) {
	loaded, err := load("", []string{
		"ANIX_CONTROL_JWT_SECRET=container-secret",
		"ANIX_CONTROL_DATABASE_HOST=db.internal",
	})
	require.NoError(t, err)
	assert.Equal(t, "production", loaded.Env)
	assert.Equal(t, "release", loaded.Server.Mode)
	assert.Equal(t, 8080, loaded.Server.Port)
	assert.Equal(t, "postgres", loaded.Database.Driver)
	assert.Equal(t, "db.internal", loaded.Database.Host)
	assert.Equal(t, "container-secret", loaded.JWT.Secret)
	assert.True(t, loaded.Plugins.ControlExecutionEnabled)
	assert.Empty(t, loaded.Plugins.ControlHostRuntimeDir, "container defaults use private temporary host directories")
	assert.Equal(t, "lvbhRmhzVbSAbrw3vm0k7vYqpEu4/dF/ZqVbp2gS7uM=", loaded.Plugins.OfficialPublicKey)
	require.NoError(t, loaded.ValidateForServer())
}

func TestLoadAppliesEnvironmentOverAConfigFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "config.yaml")
	require.NoError(t, os.WriteFile(path, []byte("env: development\ndatabase:\n  driver: sqlite\n  password: from-file\n"), 0o600))
	loaded, err := load(path, []string{"ANIX_CONTROL_DATABASE_PASSWORD=from-env"})
	require.NoError(t, err)
	assert.Equal(t, "from-env", loaded.Database.Password)
	assert.Equal(t, "sqlite", loaded.Database.Driver)
	assert.Empty(t, loaded.Server.Mode, "a development config keeps gin's own mode default")
}

func TestValidateForServerRequiresARealJWTSecretInProduction(t *testing.T) {
	for _, secret := range []string{"", "  ", "your-jwt-secret-key-change-in-production", "CHANGE-THIS-TO-A-VERY-LONG-RANDOM-STRING-IN-PRODUCTION"} {
		loaded := Defaults()
		loaded.JWT.Secret = secret
		require.Error(t, loaded.ValidateForServer(), "secret %q", secret)
	}
	development := &Config{Env: "development"}
	require.NoError(t, development.ValidateForServer())
}

func TestLoadValidatesDatabaseConnectionSettings(t *testing.T) {
	_, err := load("", []string{"ANIX_CONTROL_DATABASE_SSLMODE=sometimes"})
	require.ErrorContains(t, err, "database.sslmode")

	_, err = load("", []string{"ANIX_CONTROL_DATABASE_TIMEZONE=Mars/Base"})
	require.ErrorContains(t, err, "database.timezone")

	loaded, err := load("", []string{"ANIX_CONTROL_DATABASE_SSLMODE=verify-full", "ANIX_CONTROL_DATABASE_TIMEZONE=UTC"})
	require.NoError(t, err)
	assert.Equal(t, "verify-full", loaded.Database.SSLMode)
	assert.Equal(t, "UTC", loaded.Database.TimeZone)
}

func TestPathFromEnvTrimsTheConfiguredPath(t *testing.T) {
	t.Setenv(ConfigPathEnv, "  /app/config/config.yaml \n")
	assert.Equal(t, "/app/config/config.yaml", PathFromEnv())
	t.Setenv(ConfigPathEnv, "")
	assert.Empty(t, PathFromEnv())
}
