// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: api/packagebridge/v1/package_bridge.proto

package packagebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPackageConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageConfigRequest) Reset() {
	*x = GetPackageConfigRequest{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageConfigRequest) ProtoMessage() {}

func (x *GetPackageConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageConfigRequest.ProtoReflect.Descriptor instead.
func (*GetPackageConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{0}
}

// GetPackageConfigResponse is the host's view of its installation
// configuration. route_modes maps v2 route ids to legacy, shadow or native;
// routes that are absent run in legacy mode.
type GetPackageConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	RouteModes    map[string]string      `protobuf:"bytes,3,rep,name=route_modes,json=routeModes,proto3" json:"route_modes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageConfigResponse) Reset() {
	*x = GetPackageConfigResponse{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageConfigResponse) ProtoMessage() {}

func (x *GetPackageConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageConfigResponse.ProtoReflect.Descriptor instead.
func (*GetPackageConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *GetPackageConfigResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GetPackageConfigResponse) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *GetPackageConfigResponse) GetRouteModes() map[string]string {
	if x != nil {
		return x.RouteModes
	}
	return nil
}

type LeaseStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseStorageRequest) Reset() {
	*x = LeaseStorageRequest{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseStorageRequest) ProtoMessage() {}

func (x *LeaseStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseStorageRequest.ProtoReflect.Descriptor instead.
func (*LeaseStorageRequest) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{2}
}

type LeaseStorageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// driver is "postgres" or "sqlite".
	Driver string `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	// dsn connects as the package role (postgres) or names the shared database
	// file (sqlite). It never carries kernel credentials.
	Dsn string `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn,omitempty"`
	// schema holds the package's own tables on postgres; empty on sqlite.
	Schema string `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	// table_prefix names the package's own tables on sqlite; empty on postgres.
	TablePrefix     string   `protobuf:"bytes,4,opt,name=table_prefix,json=tablePrefix,proto3" json:"table_prefix,omitempty"`
	LeaseGeneration int64    `protobuf:"varint,5,opt,name=lease_generation,json=leaseGeneration,proto3" json:"lease_generation,omitempty"`
	AdoptedTables   []string `protobuf:"bytes,6,rep,name=adopted_tables,json=adoptedTables,proto3" json:"adopted_tables,omitempty"`
	Views           []string `protobuf:"bytes,7,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeaseStorageResponse) Reset() {
	*x = LeaseStorageResponse{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseStorageResponse) ProtoMessage() {}

func (x *LeaseStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseStorageResponse.ProtoReflect.Descriptor instead.
func (*LeaseStorageResponse) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *LeaseStorageResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *LeaseStorageResponse) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *LeaseStorageResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *LeaseStorageResponse) GetTablePrefix() string {
	if x != nil {
		return x.TablePrefix
	}
	return ""
}

func (x *LeaseStorageResponse) GetLeaseGeneration() int64 {
	if x != nil {
		return x.LeaseGeneration
	}
	return 0
}

func (x *LeaseStorageResponse) GetAdoptedTables() []string {
	if x != nil {
		return x.AdoptedTables
	}
	return nil
}

func (x *LeaseStorageResponse) GetViews() []string {
	if x != nil {
		return x.Views
	}
	return nil
}

type BindRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PackageId      string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	PackageVersion string                 `protobuf:"bytes,2,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	// instance_id is unique per module process, for example the pod name.
	InstanceId string `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// advertise_addr is the host:port the kernel dials for ControlPackageHost.
	AdvertiseAddr string `protobuf:"bytes,4,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	// lease_id is the random per-process lease the module also reports from
	// Health.
	LeaseId string `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// image_digest is the module's reported OCI image digest. It is advisory:
	// the kernel cannot prove what a remote process runs.
	ImageDigest   string `protobuf:"bytes,6,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *BindRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *BindRequest) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *BindRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *BindRequest) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *BindRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *BindRequest) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

type BindResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_token authorizes every later bridge RPC of this instance when
	// presented as x-anix-bridge-session together with the same client
	// certificate.
	SessionToken            []byte `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	RouteGeneration         uint64 `protobuf:"varint,2,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	HeartbeatIntervalMillis int64  `protobuf:"varint,3,opt,name=heartbeat_interval_millis,json=heartbeatIntervalMillis,proto3" json:"heartbeat_interval_millis,omitempty"`
	SessionTtlMillis        int64  `protobuf:"varint,4,opt,name=session_ttl_millis,json=sessionTtlMillis,proto3" json:"session_ttl_millis,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *BindResponse) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *BindResponse) GetRouteGeneration() uint64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

func (x *BindResponse) GetHeartbeatIntervalMillis() int64 {
	if x != nil {
		return x.HeartbeatIntervalMillis
	}
	return 0
}

func (x *BindResponse) GetSessionTtlMillis() int64 {
	if x != nil {
		return x.SessionTtlMillis
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InFlight      uint64                 `protobuf:"varint,1,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetInFlight() uint64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RouteGeneration uint64                 `protobuf:"varint,1,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	// fenced means the session's generation is no longer current; the module
	// must stop serving it and Bind again.
	Fenced        bool `protobuf:"varint,2,opt,name=fenced,proto3" json:"fenced,omitempty"`
	Draining      bool `protobuf:"varint,3,opt,name=draining,proto3" json:"draining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetRouteGeneration() uint64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

func (x *HeartbeatResponse) GetFenced() bool {
	if x != nil {
		return x.Fenced
	}
	return false
}

func (x *HeartbeatResponse) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    []byte                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeRequest) GetCapability() []byte {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *InvokeRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseBody  []byte                 `protobuf:"bytes,1,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	StatusCode    uint32                 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       []*ResponseHeader      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeResponse) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *InvokeResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InvokeResponse) GetHeaders() []*ResponseHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// WebSocketFrame is available only on the private inherited bridge. The first
// client frame must be an open frame; every later frame is data or close.
type WebSocketFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*WebSocketFrame_Open
	//	*WebSocketFrame_Data
	//	*WebSocketFrame_Close
	Value         isWebSocketFrame_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketFrame) Reset() {
	*x = WebSocketFrame{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketFrame) ProtoMessage() {}

func (x *WebSocketFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketFrame.ProtoReflect.Descriptor instead.
func (*WebSocketFrame) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *WebSocketFrame) GetValue() isWebSocketFrame_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WebSocketFrame) GetOpen() *WebSocketOpen {
	if x != nil {
		if x, ok := x.Value.(*WebSocketFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *WebSocketFrame) GetData() []byte {
	if x != nil {
		if x, ok := x.Value.(*WebSocketFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *WebSocketFrame) GetClose() *WebSocketClose {
	if x != nil {
		if x, ok := x.Value.(*WebSocketFrame_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isWebSocketFrame_Value interface {
	isWebSocketFrame_Value()
}

type WebSocketFrame_Open struct {
	Open *WebSocketOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type WebSocketFrame_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type WebSocketFrame_Close struct {
	Close *WebSocketClose `protobuf:"bytes,3,opt,name=close,proto3,oneof"`
}

func (*WebSocketFrame_Open) isWebSocketFrame_Value() {}

func (*WebSocketFrame_Data) isWebSocketFrame_Value() {}

func (*WebSocketFrame_Close) isWebSocketFrame_Value() {}

type WebSocketOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    []byte                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketOpen) Reset() {
	*x = WebSocketOpen{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketOpen) ProtoMessage() {}

func (x *WebSocketOpen) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketOpen.ProtoReflect.Descriptor instead.
func (*WebSocketOpen) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *WebSocketOpen) GetCapability() []byte {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *WebSocketOpen) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type WebSocketClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketClose) Reset() {
	*x = WebSocketClose{}
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketClose) ProtoMessage() {}

func (x *WebSocketClose) ProtoReflect() protoreflect.Message {
	mi := &file_api_packagebridge_v1_package_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketClose.ProtoReflect.Descriptor instead.
func (*WebSocketClose) Descriptor() ([]byte, []int) {
	return file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *WebSocketClose) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WebSocketClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_packagebridge_v1_package_bridge_proto protoreflect.FileDescriptor

const file_api_packagebridge_v1_package_bridge_proto_rawDesc = "" +
	"\n" +
	")api/packagebridge/v1/package_bridge.proto\x12\x18anixops.packagebridge.v1\"\x19\n" +
	"\x17GetPackageConfigRequest\"\xfb\x01\n" +
	"\x18GetPackageConfigResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\x12c\n" +
	"\vroute_modes\x18\x03 \x03(\v2B.anixops.packagebridge.v1.GetPackageConfigResponse.RouteModesEntryR\n" +
	"routeModes\x1a=\n" +
	"\x0fRouteModesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13LeaseStorageRequest\"\xe3\x01\n" +
	"\x14LeaseStorageResponse\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x10\n" +
	"\x03dsn\x18\x02 \x01(\tR\x03dsn\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\x12!\n" +
	"\ftable_prefix\x18\x04 \x01(\tR\vtablePrefix\x12)\n" +
	"\x10lease_generation\x18\x05 \x01(\x03R\x0fleaseGeneration\x12%\n" +
	"\x0eadopted_tables\x18\x06 \x03(\tR\radoptedTables\x12\x14\n" +
	"\x05views\x18\a \x03(\tR\x05views\"\xdb\x01\n" +
	"\vBindRequest\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12'\n" +
	"\x0fpackage_version\x18\x02 \x01(\tR\x0epackageVersion\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0eadvertise_addr\x18\x04 \x01(\tR\radvertiseAddr\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x12!\n" +
	"\fimage_digest\x18\x06 \x01(\tR\vimageDigest\"\xc8\x01\n" +
	"\fBindResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\fR\fsessionToken\x12)\n" +
	"\x10route_generation\x18\x02 \x01(\x04R\x0frouteGeneration\x12:\n" +
	"\x19heartbeat_interval_millis\x18\x03 \x01(\x03R\x17heartbeatIntervalMillis\x12,\n" +
	"\x12session_ttl_millis\x18\x04 \x01(\x03R\x10sessionTtlMillis\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tin_flight\x18\x01 \x01(\x04R\binFlight\"r\n" +
	"\x11HeartbeatResponse\x12)\n" +
	"\x10route_generation\x18\x01 \x01(\x04R\x0frouteGeneration\x12\x16\n" +
	"\x06fenced\x18\x02 \x01(\bR\x06fenced\x12\x1a\n" +
	"\bdraining\x18\x03 \x01(\bR\bdraining\"g\n" +
	"\rInvokeRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\fR\n" +
	"capability\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x9a\x01\n" +
	"\x0eInvokeResponse\x12#\n" +
	"\rresponse_body\x18\x01 \x01(\fR\fresponseBody\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\rR\n" +
	"statusCode\x12B\n" +
	"\aheaders\x18\x03 \x03(\v2(.anixops.packagebridge.v1.ResponseHeaderR\aheaders\":\n" +
	"\x0eResponseHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb0\x01\n" +
	"\x0eWebSocketFrame\x12=\n" +
	"\x04open\x18\x01 \x01(\v2'.anixops.packagebridge.v1.WebSocketOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12@\n" +
	"\x05close\x18\x03 \x01(\v2(.anixops.packagebridge.v1.WebSocketCloseH\x00R\x05closeB\a\n" +
	"\x05value\"M\n" +
	"\rWebSocketOpen\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\fR\n" +
	"capability\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"<\n" +
	"\x0eWebSocketClose\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x82\x05\n" +
	"\x13KernelPackageBridge\x12[\n" +
	"\x06Invoke\x12'.anixops.packagebridge.v1.InvokeRequest\x1a(.anixops.packagebridge.v1.InvokeResponse\x12g\n" +
	"\rOpenWebSocket\x12(.anixops.packagebridge.v1.WebSocketFrame\x1a(.anixops.packagebridge.v1.WebSocketFrame(\x010\x01\x12y\n" +
	"\x10GetPackageConfig\x121.anixops.packagebridge.v1.GetPackageConfigRequest\x1a2.anixops.packagebridge.v1.GetPackageConfigResponse\x12m\n" +
	"\fLeaseStorage\x12-.anixops.packagebridge.v1.LeaseStorageRequest\x1a..anixops.packagebridge.v1.LeaseStorageResponse\x12U\n" +
	"\x04Bind\x12%.anixops.packagebridge.v1.BindRequest\x1a&.anixops.packagebridge.v1.BindResponse\x12d\n" +
	"\tHeartbeat\x12*.anixops.packagebridge.v1.HeartbeatRequest\x1a+.anixops.packagebridge.v1.HeartbeatResponseBJZHgithub.com/AnixOps/anix-control/sdk/api/packagebridge/v1;packagebridgev1b\x06proto3"

var (
	file_api_packagebridge_v1_package_bridge_proto_rawDescOnce sync.Once
	file_api_packagebridge_v1_package_bridge_proto_rawDescData []byte
)

func file_api_packagebridge_v1_package_bridge_proto_rawDescGZIP() []byte {
	file_api_packagebridge_v1_package_bridge_proto_rawDescOnce.Do(func() {
		file_api_packagebridge_v1_package_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_packagebridge_v1_package_bridge_proto_rawDesc), len(file_api_packagebridge_v1_package_bridge_proto_rawDesc)))
	})
	return file_api_packagebridge_v1_package_bridge_proto_rawDescData
}

var file_api_packagebridge_v1_package_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_packagebridge_v1_package_bridge_proto_goTypes = []any{
	(*GetPackageConfigRequest)(nil),  // 0: anixops.packagebridge.v1.GetPackageConfigRequest
	(*GetPackageConfigResponse)(nil), // 1: anixops.packagebridge.v1.GetPackageConfigResponse
	(*LeaseStorageRequest)(nil),      // 2: anixops.packagebridge.v1.LeaseStorageRequest
	(*LeaseStorageResponse)(nil),     // 3: anixops.packagebridge.v1.LeaseStorageResponse
	(*BindRequest)(nil),              // 4: anixops.packagebridge.v1.BindRequest
	(*BindResponse)(nil),             // 5: anixops.packagebridge.v1.BindResponse
	(*HeartbeatRequest)(nil),         // 6: anixops.packagebridge.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 7: anixops.packagebridge.v1.HeartbeatResponse
	(*InvokeRequest)(nil),            // 8: anixops.packagebridge.v1.InvokeRequest
	(*InvokeResponse)(nil),           // 9: anixops.packagebridge.v1.InvokeResponse
	(*ResponseHeader)(nil),           // 10: anixops.packagebridge.v1.ResponseHeader
	(*WebSocketFrame)(nil),           // 11: anixops.packagebridge.v1.WebSocketFrame
	(*WebSocketOpen)(nil),            // 12: anixops.packagebridge.v1.WebSocketOpen
	(*WebSocketClose)(nil),           // 13: anixops.packagebridge.v1.WebSocketClose
	nil,                              // 14: anixops.packagebridge.v1.GetPackageConfigResponse.RouteModesEntry
}
var file_api_packagebridge_v1_package_bridge_proto_depIdxs = []int32{
	14, // 0: anixops.packagebridge.v1.GetPackageConfigResponse.route_modes:type_name -> anixops.packagebridge.v1.GetPackageConfigResponse.RouteModesEntry
	10, // 1: anixops.packagebridge.v1.InvokeResponse.headers:type_name -> anixops.packagebridge.v1.ResponseHeader
	12, // 2: anixops.packagebridge.v1.WebSocketFrame.open:type_name -> anixops.packagebridge.v1.WebSocketOpen
	13, // 3: anixops.packagebridge.v1.WebSocketFrame.close:type_name -> anixops.packagebridge.v1.WebSocketClose
	8,  // 4: anixops.packagebridge.v1.KernelPackageBridge.Invoke:input_type -> anixops.packagebridge.v1.InvokeRequest
	11, // 5: anixops.packagebridge.v1.KernelPackageBridge.OpenWebSocket:input_type -> anixops.packagebridge.v1.WebSocketFrame
	0,  // 6: anixops.packagebridge.v1.KernelPackageBridge.GetPackageConfig:input_type -> anixops.packagebridge.v1.GetPackageConfigRequest
	2,  // 7: anixops.packagebridge.v1.KernelPackageBridge.LeaseStorage:input_type -> anixops.packagebridge.v1.LeaseStorageRequest
	4,  // 8: anixops.packagebridge.v1.KernelPackageBridge.Bind:input_type -> anixops.packagebridge.v1.BindRequest
	6,  // 9: anixops.packagebridge.v1.KernelPackageBridge.Heartbeat:input_type -> anixops.packagebridge.v1.HeartbeatRequest
	9,  // 10: anixops.packagebridge.v1.KernelPackageBridge.Invoke:output_type -> anixops.packagebridge.v1.InvokeResponse
	11, // 11: anixops.packagebridge.v1.KernelPackageBridge.OpenWebSocket:output_type -> anixops.packagebridge.v1.WebSocketFrame
	1,  // 12: anixops.packagebridge.v1.KernelPackageBridge.GetPackageConfig:output_type -> anixops.packagebridge.v1.GetPackageConfigResponse
	3,  // 13: anixops.packagebridge.v1.KernelPackageBridge.LeaseStorage:output_type -> anixops.packagebridge.v1.LeaseStorageResponse
	5,  // 14: anixops.packagebridge.v1.KernelPackageBridge.Bind:output_type -> anixops.packagebridge.v1.BindResponse
	7,  // 15: anixops.packagebridge.v1.KernelPackageBridge.Heartbeat:output_type -> anixops.packagebridge.v1.HeartbeatResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_packagebridge_v1_package_bridge_proto_init() }
func file_api_packagebridge_v1_package_bridge_proto_init() {
	if File_api_packagebridge_v1_package_bridge_proto != nil {
		return
	}
	file_api_packagebridge_v1_package_bridge_proto_msgTypes[11].OneofWrappers = []any{
		(*WebSocketFrame_Open)(nil),
		(*WebSocketFrame_Data)(nil),
		(*WebSocketFrame_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_packagebridge_v1_package_bridge_proto_rawDesc), len(file_api_packagebridge_v1_package_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_packagebridge_v1_package_bridge_proto_goTypes,
		DependencyIndexes: file_api_packagebridge_v1_package_bridge_proto_depIdxs,
		MessageInfos:      file_api_packagebridge_v1_package_bridge_proto_msgTypes,
	}.Build()
	File_api_packagebridge_v1_package_bridge_proto = out.File
	file_api_packagebridge_v1_package_bridge_proto_goTypes = nil
	file_api_packagebridge_v1_package_bridge_proto_depIdxs = nil
}
