apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anix-control.fullname" . }}
  labels:
    {{- include "anix-control.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
