{{- if not .Values.secrets.existingSecret }}
{{- range $key, $variable := .Values.secrets.files }}
{{- if not (index $.Values.secrets.values $key) }}
{{- fail (printf "secrets.values.%s is required (or set secrets.existingSecret)" $key) }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anix-control.secretName" . }}
  labels:
    {{- include "anix-control.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $variable := .Values.secrets.files }}
  {{ $key }}: {{ index $.Values.secrets.values $key | b64enc | quote }}
  {{- end }}
{{- end }}
