// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.2
// source: api/forward/v1/forward.proto

package forwardv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForwardControl_CreateRoute_FullMethodName    = "/anixops.forward.v1.ForwardControl/CreateRoute"
	ForwardControl_UpdateRoute_FullMethodName    = "/anixops.forward.v1.ForwardControl/UpdateRoute"
	ForwardControl_DeleteRoute_FullMethodName    = "/anixops.forward.v1.ForwardControl/DeleteRoute"
	ForwardControl_GetRoute_FullMethodName       = "/anixops.forward.v1.ForwardControl/GetRoute"
	ForwardControl_ListRoutes_FullMethodName     = "/anixops.forward.v1.ForwardControl/ListRoutes"
	ForwardControl_PlanRoute_FullMethodName      = "/anixops.forward.v1.ForwardControl/PlanRoute"
	ForwardControl_GetRouteStats_FullMethodName  = "/anixops.forward.v1.ForwardControl/GetRouteStats"
	ForwardControl_GetRouteHealth_FullMethodName = "/anixops.forward.v1.ForwardControl/GetRouteHealth"
	ForwardControl_DiagnoseRoute_FullMethodName  = "/anixops.forward.v1.ForwardControl/DiagnoseRoute"
)

// ForwardControlClient is the client API for ForwardControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ForwardControl is Control's forwarding API: route CRUD, a dry-run planner,
// statistics, health and end-to-end diagnosis. Control serves it to its own
// UI and API handlers, to the operator CLI ("anix-control forward ...") and
// to other AnixOps products. Every caller goes through Control; there is no
// node-side or standalone equivalent.
type ForwardControlClient interface {
	// CreateRoute validates and plans a route and stores it. request_id makes
	// a retry apply once. INVALID_ARGUMENT for a route that fails validation
	// or planning (the answer's violations say why), FAILED_PRECONDITION when
	// a port the route asks for is taken or a node lacks a capability the
	// route needs.
	CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error)
	// UpdateRoute replaces a route. expected_revision guards against a lost
	// update (ABORTED when it differs).
	UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error)
	// DeleteRoute removes a route; its hops leave every node's state in the
	// next generation, and its port allocations are released after a grace
	// period.
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
	// PlanRoute runs the planner without storing anything and answers the
	// hops each node would run. It is what the UI previews and what the
	// golden fixtures in contracts/forward/v1 record.
	PlanRoute(ctx context.Context, in *PlanRouteRequest, opts ...grpc.CallOption) (*PlanRouteResponse, error)
	// GetRouteStats answers the route's raw counters per hop and direction,
	// as nodes reported them. Billing multipliers are not applied here.
	GetRouteStats(ctx context.Context, in *GetRouteStatsRequest, opts ...grpc.CallOption) (*GetRouteStatsResponse, error)
	// GetRouteHealth answers the health of every upstream of every hop, with
	// the latest per-hop latency probes.
	GetRouteHealth(ctx context.Context, in *GetRouteHealthRequest, opts ...grpc.CallOption) (*GetRouteHealthResponse, error)
	// DiagnoseRoute runs an end-to-end check through the route's nodes:
	// listen ownership and port conflicts on each hop (nat table included),
	// reachability of each next hop, delivery proved on the last hop, and a
	// real UDP exchange for UDP routes.
	DiagnoseRoute(ctx context.Context, in *DiagnoseRouteRequest, opts ...grpc.CallOption) (*DiagnoseRouteResponse, error)
}

type forwardControlClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardControlClient(cc grpc.ClientConnInterface) ForwardControlClient {
	return &forwardControlClient{cc}
}

func (c *forwardControlClient) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRouteResponse)
	err := c.cc.Invoke(ctx, ForwardControl_CreateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardControlClient) UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRouteResponse)
	err := c.cc.Invoke(ctx, ForwardControl_UpdateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardControlClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, ForwardControl_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardControlClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, ForwardControl_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardControlClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, ForwardControl_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardControlClient) PlanRoute(ctx context.Context, in *PlanRouteRequest, opts ...grpc.CallOption) (*PlanRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanRouteResponse)
	err := c.cc.Invoke(ctx, ForwardControl_PlanRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardControlClient) GetRouteStats(ctx context.Context, in *GetRouteStatsRequest, opts ...grpc.CallOption) (*GetRouteStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteStatsResponse)
	err := c.cc.Invoke(ctx, ForwardControl_GetRouteStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardControlClient) GetRouteHealth(ctx context.Context, in *GetRouteHealthRequest, opts ...grpc.CallOption) (*GetRouteHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteHealthResponse)
	err := c.cc.Invoke(ctx, ForwardControl_GetRouteHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardControlClient) DiagnoseRoute(ctx context.Context, in *DiagnoseRouteRequest, opts ...grpc.CallOption) (*DiagnoseRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnoseRouteResponse)
	err := c.cc.Invoke(ctx, ForwardControl_DiagnoseRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardControlServer is the server API for ForwardControl service.
// All implementations must embed UnimplementedForwardControlServer
// for forward compatibility.
//
// ForwardControl is Control's forwarding API: route CRUD, a dry-run planner,
// statistics, health and end-to-end diagnosis. Control serves it to its own
// UI and API handlers, to the operator CLI ("anix-control forward ...") and
// to other AnixOps products. Every caller goes through Control; there is no
// node-side or standalone equivalent.
type ForwardControlServer interface {
	// CreateRoute validates and plans a route and stores it. request_id makes
	// a retry apply once. INVALID_ARGUMENT for a route that fails validation
	// or planning (the answer's violations say why), FAILED_PRECONDITION when
	// a port the route asks for is taken or a node lacks a capability the
	// route needs.
	CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error)
	// UpdateRoute replaces a route. expected_revision guards against a lost
	// update (ABORTED when it differs).
	UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error)
	// DeleteRoute removes a route; its hops leave every node's state in the
	// next generation, and its port allocations are released after a grace
	// period.
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	// PlanRoute runs the planner without storing anything and answers the
	// hops each node would run. It is what the UI previews and what the
	// golden fixtures in contracts/forward/v1 record.
	PlanRoute(context.Context, *PlanRouteRequest) (*PlanRouteResponse, error)
	// GetRouteStats answers the route's raw counters per hop and direction,
	// as nodes reported them. Billing multipliers are not applied here.
	GetRouteStats(context.Context, *GetRouteStatsRequest) (*GetRouteStatsResponse, error)
	// GetRouteHealth answers the health of every upstream of every hop, with
	// the latest per-hop latency probes.
	GetRouteHealth(context.Context, *GetRouteHealthRequest) (*GetRouteHealthResponse, error)
	// DiagnoseRoute runs an end-to-end check through the route's nodes:
	// listen ownership and port conflicts on each hop (nat table included),
	// reachability of each next hop, delivery proved on the last hop, and a
	// real UDP exchange for UDP routes.
	DiagnoseRoute(context.Context, *DiagnoseRouteRequest) (*DiagnoseRouteResponse, error)
	mustEmbedUnimplementedForwardControlServer()
}

// UnimplementedForwardControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwardControlServer struct{}

func (UnimplementedForwardControlServer) CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedForwardControlServer) UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoute not implemented")
}
func (UnimplementedForwardControlServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedForwardControlServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedForwardControlServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedForwardControlServer) PlanRoute(context.Context, *PlanRouteRequest) (*PlanRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanRoute not implemented")
}
func (UnimplementedForwardControlServer) GetRouteStats(context.Context, *GetRouteStatsRequest) (*GetRouteStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteStats not implemented")
}
func (UnimplementedForwardControlServer) GetRouteHealth(context.Context, *GetRouteHealthRequest) (*GetRouteHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteHealth not implemented")
}
func (UnimplementedForwardControlServer) DiagnoseRoute(context.Context, *DiagnoseRouteRequest) (*DiagnoseRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiagnoseRoute not implemented")
}
func (UnimplementedForwardControlServer) mustEmbedUnimplementedForwardControlServer() {}
func (UnimplementedForwardControlServer) testEmbeddedByValue()                        {}

// UnsafeForwardControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardControlServer will
// result in compilation errors.
type UnsafeForwardControlServer interface {
	mustEmbedUnimplementedForwardControlServer()
}

func RegisterForwardControlServer(s grpc.ServiceRegistrar, srv ForwardControlServer) {
	// If the following call panics, it indicates UnimplementedForwardControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwardControl_ServiceDesc, srv)
}

func _ForwardControl_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_CreateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).CreateRoute(ctx, req.(*CreateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardControl_UpdateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).UpdateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_UpdateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).UpdateRoute(ctx, req.(*UpdateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardControl_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardControl_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardControl_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardControl_PlanRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).PlanRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_PlanRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).PlanRoute(ctx, req.(*PlanRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardControl_GetRouteStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).GetRouteStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_GetRouteStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).GetRouteStats(ctx, req.(*GetRouteStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardControl_GetRouteHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).GetRouteHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_GetRouteHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).GetRouteHealth(ctx, req.(*GetRouteHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardControl_DiagnoseRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnoseRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardControlServer).DiagnoseRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardControl_DiagnoseRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardControlServer).DiagnoseRoute(ctx, req.(*DiagnoseRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardControl_ServiceDesc is the grpc.ServiceDesc for ForwardControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anixops.forward.v1.ForwardControl",
	HandlerType: (*ForwardControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoute",
			Handler:    _ForwardControl_CreateRoute_Handler,
		},
		{
			MethodName: "UpdateRoute",
			Handler:    _ForwardControl_UpdateRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _ForwardControl_DeleteRoute_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _ForwardControl_GetRoute_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _ForwardControl_ListRoutes_Handler,
		},
		{
			MethodName: "PlanRoute",
			Handler:    _ForwardControl_PlanRoute_Handler,
		},
		{
			MethodName: "GetRouteStats",
			Handler:    _ForwardControl_GetRouteStats_Handler,
		},
		{
			MethodName: "GetRouteHealth",
			Handler:    _ForwardControl_GetRouteHealth_Handler,
		},
		{
			MethodName: "DiagnoseRoute",
			Handler:    _ForwardControl_DiagnoseRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/forward/v1/forward.proto",
}

const (
	ForwardNode_GetCapabilities_FullMethodName = "/anixops.forward.v1.ForwardNode/GetCapabilities"
	ForwardNode_Apply_FullMethodName           = "/anixops.forward.v1.ForwardNode/Apply"
	ForwardNode_Observe_FullMethodName         = "/anixops.forward.v1.ForwardNode/Observe"
	ForwardNode_Probe_FullMethodName           = "/anixops.forward.v1.ForwardNode/Probe"
)

// ForwardNodeClient is the client API for ForwardNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ForwardNode is the node side: what an Agent's forwarding component does
// with its node's desired state. It is not a network listener. Control
// carries Apply as part of the node's configuration snapshot (config.v1),
// Observe as reports over the Agent stream (PackageReport), and Probe as a
// desired operation; the service exists so drivers, the conformance suite
// and the Agent share one typed boundary.
type ForwardNodeClient interface {
	// GetCapabilities answers what the node's drivers can do.
	GetCapabilities(ctx context.Context, in *GetNodeCapabilitiesRequest, opts ...grpc.CallOption) (*NodeCapabilities, error)
	// Apply makes the node run exactly the given state, replacing the
	// previous one atomically per engine. A state with no hops removes every
	// rule, service and object the drivers own. Applying an older generation
	// than the one applied is refused (FAILED_PRECONDITION).
	Apply(ctx context.Context, in *NodeForwardState, opts ...grpc.CallOption) (*ApplyResult, error)
	// Observe answers the node's counters and health now.
	Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*NodeForwardReport, error)
	// Probe runs one diagnostic step on the node.
	Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResult, error)
}

type forwardNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardNodeClient(cc grpc.ClientConnInterface) ForwardNodeClient {
	return &forwardNodeClient{cc}
}

func (c *forwardNodeClient) GetCapabilities(ctx context.Context, in *GetNodeCapabilitiesRequest, opts ...grpc.CallOption) (*NodeCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeCapabilities)
	err := c.cc.Invoke(ctx, ForwardNode_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardNodeClient) Apply(ctx context.Context, in *NodeForwardState, opts ...grpc.CallOption) (*ApplyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResult)
	err := c.cc.Invoke(ctx, ForwardNode_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardNodeClient) Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*NodeForwardReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeForwardReport)
	err := c.cc.Invoke(ctx, ForwardNode_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardNodeClient) Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeResult)
	err := c.cc.Invoke(ctx, ForwardNode_Probe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardNodeServer is the server API for ForwardNode service.
// All implementations must embed UnimplementedForwardNodeServer
// for forward compatibility.
//
// ForwardNode is the node side: what an Agent's forwarding component does
// with its node's desired state. It is not a network listener. Control
// carries Apply as part of the node's configuration snapshot (config.v1),
// Observe as reports over the Agent stream (PackageReport), and Probe as a
// desired operation; the service exists so drivers, the conformance suite
// and the Agent share one typed boundary.
type ForwardNodeServer interface {
	// GetCapabilities answers what the node's drivers can do.
	GetCapabilities(context.Context, *GetNodeCapabilitiesRequest) (*NodeCapabilities, error)
	// Apply makes the node run exactly the given state, replacing the
	// previous one atomically per engine. A state with no hops removes every
	// rule, service and object the drivers own. Applying an older generation
	// than the one applied is refused (FAILED_PRECONDITION).
	Apply(context.Context, *NodeForwardState) (*ApplyResult, error)
	// Observe answers the node's counters and health now.
	Observe(context.Context, *ObserveRequest) (*NodeForwardReport, error)
	// Probe runs one diagnostic step on the node.
	Probe(context.Context, *ProbeRequest) (*ProbeResult, error)
	mustEmbedUnimplementedForwardNodeServer()
}

// UnimplementedForwardNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwardNodeServer struct{}

func (UnimplementedForwardNodeServer) GetCapabilities(context.Context, *GetNodeCapabilitiesRequest) (*NodeCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedForwardNodeServer) Apply(context.Context, *NodeForwardState) (*ApplyResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedForwardNodeServer) Observe(context.Context, *ObserveRequest) (*NodeForwardReport, error) {
	return nil, status.Error(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedForwardNodeServer) Probe(context.Context, *ProbeRequest) (*ProbeResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Probe not implemented")
}
func (UnimplementedForwardNodeServer) mustEmbedUnimplementedForwardNodeServer() {}
func (UnimplementedForwardNodeServer) testEmbeddedByValue()                     {}

// UnsafeForwardNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardNodeServer will
// result in compilation errors.
type UnsafeForwardNodeServer interface {
	mustEmbedUnimplementedForwardNodeServer()
}

func RegisterForwardNodeServer(s grpc.ServiceRegistrar, srv ForwardNodeServer) {
	// If the following call panics, it indicates UnimplementedForwardNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwardNode_ServiceDesc, srv)
}

func _ForwardNode_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardNodeServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardNode_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardNodeServer).GetCapabilities(ctx, req.(*GetNodeCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardNode_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeForwardState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardNodeServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardNode_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardNodeServer).Apply(ctx, req.(*NodeForwardState))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardNode_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardNodeServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardNode_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardNodeServer).Observe(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardNode_Probe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardNodeServer).Probe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardNode_Probe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardNodeServer).Probe(ctx, req.(*ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardNode_ServiceDesc is the grpc.ServiceDesc for ForwardNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anixops.forward.v1.ForwardNode",
	HandlerType: (*ForwardNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _ForwardNode_GetCapabilities_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _ForwardNode_Apply_Handler,
		},
		{
			MethodName: "Observe",
			Handler:    _ForwardNode_Observe_Handler,
		},
		{
			MethodName: "Probe",
			Handler:    _ForwardNode_Probe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/forward/v1/forward.proto",
}
