// Package protocompat guards the wire compatibility of every AnixOps
// protobuf contract. The golden file lists each service method, message
// field and enum value with its number and type. Removing or changing a
// listed element breaks modules built against an older contract and always
// fails; additions fail until the golden file is regenerated with
//
//	go test ./internal/tests/protocompat -update
package protocompat

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	_ "github.com/AnixOps/anix-control/sdk/api/agent/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/identity/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/kernelidentity/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/kernelnodeops/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/kernelorder/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/kernelsettings/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/kernelsubscriber/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/kerneltelemetry/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/modulepki/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/packagebridge/v1"
	_ "github.com/AnixOps/anix-control/sdk/api/pluginhost/v1"
	_ "github.com/AnixOps/anix-control/v4/api/grpc/v2boardpb"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
)

var update = flag.Bool("update", false, "rewrite the golden file with additive changes")

// contractPackages are the protobuf packages whose wire format is a contract.
var contractPackages = []string{
	"anix.agent.v1",
	"anix.pluginhost.v1",
	"anixops.identity.v1",
	"anixops.kernelorder.v1",
	"anixops.kernelidentity.v1",
	"anixops.kernelnodeops.v1",
	"anixops.kernelsettings.v1",
	"anixops.kernelsubscriber.v1",
	"anixops.kerneltelemetry.v1",
	"anixops.modulepki.v1",
	"anixops.packagebridge.v1",
	"v2board",
}

func goldenPath(t *testing.T) string {
	t.Helper()
	path, err := filepath.Abs(filepath.Join("..", "..", "..", "contracts", "proto", "descriptors.golden"))
	require.NoError(t, err)
	return path
}

func TestProtoContractsOnlyGrow(t *testing.T) {
	current := describeContracts(t)
	raw, err := os.ReadFile(goldenPath(t))
	if err != nil && !*update {
		require.NoError(t, err, "missing golden file; run go test ./internal/tests/protocompat -update")
	}
	golden := map[string]bool{}
	for _, line := range strings.Split(string(raw), "\n") {
		if line = strings.TrimSpace(line); line != "" && !strings.HasPrefix(line, "#") {
			golden[line] = true
		}
	}
	currentSet := map[string]bool{}
	for _, line := range current {
		currentSet[line] = true
	}
	var removed, added []string
	for line := range golden {
		if !currentSet[line] {
			removed = append(removed, line)
		}
	}
	for _, line := range current {
		if !golden[line] {
			added = append(added, line)
		}
	}
	sort.Strings(removed)
	require.Empty(t, removed, "breaking protobuf contract changes: these elements were removed or changed")
	if len(added) == 0 {
		return
	}
	if !*update {
		t.Fatalf("protobuf contracts gained %d elements; review them and run go test ./internal/tests/protocompat -update:\n%s",
			len(added), strings.Join(added, "\n"))
	}
	content := "# Generated by go test ./internal/tests/protocompat -update. Lines may be added, never removed.\n" +
		strings.Join(current, "\n") + "\n"
	require.NoError(t, os.WriteFile(goldenPath(t), []byte(content), 0o600))
}

func describeContracts(t *testing.T) []string {
	t.Helper()
	wanted := map[protoreflect.FullName]bool{}
	for _, name := range contractPackages {
		wanted[protoreflect.FullName(name)] = true
	}
	var lines []string
	found := map[protoreflect.FullName]bool{}
	protoregistry.GlobalFiles.RangeFiles(func(file protoreflect.FileDescriptor) bool {
		if !wanted[file.Package()] {
			return true
		}
		found[file.Package()] = true
		services := file.Services()
		for i := 0; i < services.Len(); i++ {
			service := services.Get(i)
			methods := service.Methods()
			for j := 0; j < methods.Len(); j++ {
				method := methods.Get(j)
				lines = append(lines, fmt.Sprintf("rpc %s.%s(%s%s) returns (%s%s)", service.FullName(), method.Name(),
					streamPrefix(method.IsStreamingClient()), method.Input().FullName(),
					streamPrefix(method.IsStreamingServer()), method.Output().FullName()))
			}
		}
		lines = append(lines, describeMessages(file.Messages())...)
		lines = append(lines, describeEnums(file.Enums())...)
		return true
	})
	for name := range wanted {
		require.True(t, found[name], "contract package %s is not linked into the test", name)
	}
	sort.Strings(lines)
	return lines
}

func describeMessages(messages protoreflect.MessageDescriptors) []string {
	var lines []string
	for i := 0; i < messages.Len(); i++ {
		message := messages.Get(i)
		fields := message.Fields()
		for j := 0; j < fields.Len(); j++ {
			field := fields.Get(j)
			kind := field.Kind().String()
			switch field.Kind() {
			case protoreflect.MessageKind, protoreflect.GroupKind:
				kind = string(field.Message().FullName())
			case protoreflect.EnumKind:
				kind = string(field.Enum().FullName())
			}
			if field.IsMap() {
				kind = fmt.Sprintf("map<%s,%s>", field.MapKey().Kind(), mapValueKind(field.MapValue()))
			}
			oneof := ""
			if containing := field.ContainingOneof(); containing != nil && !containing.IsSynthetic() {
				oneof = " oneof " + string(containing.Name())
			}
			lines = append(lines, fmt.Sprintf("field %s.%s = %d %s %s%s", message.FullName(), field.Name(), field.Number(),
				field.Cardinality(), kind, oneof))
		}
		lines = append(lines, describeMessages(message.Messages())...)
		lines = append(lines, describeEnums(message.Enums())...)
	}
	return lines
}

func mapValueKind(field protoreflect.FieldDescriptor) string {
	switch field.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return string(field.Message().FullName())
	case protoreflect.EnumKind:
		return string(field.Enum().FullName())
	default:
		return field.Kind().String()
	}
}

func describeEnums(enums protoreflect.EnumDescriptors) []string {
	var lines []string
	for i := 0; i < enums.Len(); i++ {
		enum := enums.Get(i)
		values := enum.Values()
		for j := 0; j < values.Len(); j++ {
			lines = append(lines, fmt.Sprintf("enum %s.%s = %d", enum.FullName(), values.Get(j).Name(), values.Get(j).Number()))
		}
	}
	return lines
}

func streamPrefix(streaming bool) string {
	if streaming {
		return "stream "
	}
	return ""
}
